### ISSUE TITLE
Allow user to select the DNS resolver

### ISSUE THREAD

**Issue by JonathanDCohen** [Jigsaw-Code/outline-client#1014]
Currently we use the system resolver to resolve the access key hostname and then use a hardcoded list of DNS resolver IPs.  

Some users (eg https://github.com/Jigsaw-Code/outline-server/issues/872) could make use of choosing their own resolver.  We could support this in the UI.

**Comment by williamgh2019** [comment]
It is available yet? Than I could use outline and resolve my own DNS server to access my corporate network.

**Comment by bchiarini2** [comment]
Ideally we would want to set the DNS on the server.

**Comment by maddyhof** [comment]
Closing as duplicate of #568
