### ISSUE TITLE
It cannot be used on Mac OS 10.13.4

### ISSUE THREAD

**Issue by kongxian** [Jigsaw-Code/outline-client#102]
It cannot be used on Mac OS 10.13.4. A VPN configuration has been generated but the web page cannot be opened.It works fine On Mac OS 10.12.6

**Comment by alalamav** [comment]
Thanks for the feedback @kongxian and sorry you're experiencing this issue. 
When you say the web page cannot be opened, do you refer to the app's UI or the invitation? What version of the app are you running?

**Comment by kongxian** [comment]
@alalamav I apologize for my unclear description.The app works fine and the status is connected.The version of the app is the same as Apple Store‘s. It's Version 1.0.2. The fact that web pages cannot be opened means that when I use Safari, all HTTP requests fail. I guess the VPN failed to forward the request.When the status of the app is disconnected,all Http requests are fine.

**Comment by alalamav** [comment]
@kongxian, thanks for following up. Could you please reproduce this issue and submit feedback through the app? It would be useful if you could specify your GitHub username, this way I can cross-reference the logs.

**Comment by kongxian** [comment]
@alalamav Sorry, I have two networks, one is family and the other is work. This week I took the MacBook home to test and found that the app was working properly. The work network probably did something special. I will close this BUG and apologize for my carelessness
