### ISSUE TITLE
incompatible with shadowsocks-rust

### ISSUE THREAD

**Issue by KaraRyougi** [Jigsaw-Code/outline-client#1057]
It seems the current Outline client is not compatible with shadowsocks-rust, which is the branch that is being actively maintained. I got the following error on the server side when connecting using Outline:

```
ERROR udp server recv_from failed with error: invalid tag-in
WARN  handshake failed, maybe wrong method or key, or under reply attacks. peer: xx.xx.xx.xx
ERROR udp server recv_from failed with error: invalid tag-in
```

**Comment by Prajwal-Koirala** [comment]
Same here.

**Comment by fortuna** [comment]
Outline follows the Shadowsocks protocol and has worked with other clients and servers since the beginning. Perhaps you are using some plugin in your server? How did you configure it?

**Comment by Prajwal-Koirala** [comment]
> Outline follows the Shadowsocks protocol and has worked with other clients and servers since the beginning. Perhaps you are using some plugin in your server? How did you configure it?

Do u have any plans to support raspberry pi?
I want to deploy my outline server in a small raspberry pi but at the current time its not supported.

**Comment by fortuna** [comment]
Unfortunately we don't support raspberry pi out of the box. We would need at least an arm distribution.
A feature request for that already exists (https://github.com/Jigsaw-Code/outline-client/issues/816), so I'll close this one.

**Comment by KaraRyougi** [comment]
> Outline follows the Shadowsocks protocol and has worked with other clients and servers since the beginning. Perhaps you are using some plugin in your server? How did you configure it?

I do not use any plugins. My configuration is pretty straightforward - chacha20-poly1305 encrypted.
