### ISSUE TITLE
Unclear error when trying to use unsupported stream ciphers

### ISSUE THREAD

**Issue by joeytwiddle** [Jigsaw-Code/outline-client#1063]
### **Describe the bug**

Pasting access key does not add the server.

### **To Reproduce**

I'm on Android. I click "Add server" and it asks me for access key.

I paste an access key. For example, this one (which used to work in the past, although the server is gone now):

`ss://YWVzLTEyOC1jZmI6WWtnZmRoWkVSWEI2UUhUZHExQURANTQuMTc5LjE1MS4zNTo2NDQ2N`

### **Actual behaviour**

Immediately after pasting (no active submit), the access key dialog disappears silently, **but no server appears in the list**!

### **Expected behavior**

The server that I just added should appear in Outline, so I can click it to connect.

Or there should be an error message, indicating what is wrong with my access key, or at least that _something_ went wrong.

### **Client System (please complete the following information):**

 - Outline Client Version [e.g. 1.6.0]
 - Your Operating System: [e.g. Android Huawei Nova 3i]

### **Submit Feedback**

Done.

### **Additional context**

I tried clearing app data, uninstalling and reinstalling, but I'm still getting the same issue.

This might be the same problem experienced in #1056

**Comment by fortuna** [comment]
How did you generate that string? It doesn't seem to be properly encoded.
It should look like the examples here: https://shadowsocks.org/en/wiki/SIP002-URI-Scheme.html

**Comment by joeytwiddle** [comment]
I generated it using the `btoa()` method here: https://shadowsocks.org/en/config/quick-guide.html

But admittedly I wrote that bit of the docs, so I might have written it wrong!

I see now that the original [jQuery implementation](https://github.com/shadowsocks/shadowsocks-org/blob/64f49c4856ca7ff9b7bacfdd70d2a29ef1d291e6/src/js/custom.js#L39) on that same webpage strips the trailing `=`. Other than that, they look the same.

Either way, if the URL is invalid, I think Outline should provide some feedback. Such as "Invalid URL. Please use SIP002"

Or if the URL is valid, but something else goes wrong, a different error message.

**Comment by joeytwiddle** [comment]
[1.2.13](https://www.apkmirror.com/apk/jigsaw-llc/outline/outline-1-2-13-release/) is working as expected.

But if I then upgrade to 1.6.0 then the server card (which was added by 1.2.13) now says "Unsupported cipher" (we're using `aes-128-cfb`).

I believe that error should be displayed when I try to add the server in the latest version, rather than silent failure.
