### ISSUE TITLE
API

### ISSUE THREAD

**Issue by KrasProject2021** [Jigsaw-Code/outline-client#1064]
Hello! Do you have an API ? I want to write a script to create SS keys. I will be grateful for the answer !

**Comment by fortuna** [comment]
Yes. See https://github.com/Jigsaw-Code/outline-server/tree/master/src/shadowbox#access-keys-management-api

**Comment by fortuna** [comment]
You may be interested in this: https://www.reddit.com/r/outlinevpn/comments/nwu1se/the_outline_distribution_system_is_here_to_help/

**Comment by fortuna** [comment]
Also: https://github.com/database64128/shadowsocks-uri-generator#telegram-bot
