### ISSUE TITLE
Error when installing node dependence 

### ISSUE THREAD

**Issue by huypxgear** [Jigsaw-Code/outline-client#1112]
I got an error when running `npm install`
**Environment**
 - OS: macOs
 - NPM version: 8.1.2
 - Node.js version: v17.1.0
Error logs:
```
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: undefined
npm ERR! notsup Not compatible with your version of node/npm: undefined
npm ERR! notsup Required: {"node":"^16.13.0","npm":"^8.1.0"}
npm ERR! notsup Actual:   {"npm":"8.1.2","node":"v17.1.0"}
```

**Comment by legiorange** [comment]
change node.js version to 16.

**Comment by jyyi1** [comment]
Hi @huypxgear , as documented [here](https://github.com/Jigsaw-Code/outline-client#requirements-for-all-builds), could you please try node 16?

**Comment by fortuna** [comment]
Obsolete
