### ISSUE TITLE
Outline no longer work on Mac

### ISSUE THREAD

**Issue by hmzisb** [Jigsaw-Code/outline-client#1115]
Every time I try to connect it shows "Sorry, an unexpected error" message, tried reinstalling but still the problem is there. Happened after the last mac os update. Can you please look?

**Comment by chennien** [comment]
Since you're not able to force the program to restart. Keep restarting your mac usually solves the problem.

**Comment by ruslaniv** [comment]
Why is this happening? Why is there no way to restart the program? 
What **IS** the unexpected error? How can i troubleshoot it? 

It keeps happening even though I have not updated the mac or did anything else system-wise. 
![Screen Shot 2023-03-06 at 23 08 54](https://user-images.githubusercontent.com/7631314/223167137-d2482593-66e6-4e8a-a884-5be7a0b2694f.png)
