### ISSUE TITLE
Release Go stack

### ISSUE THREAD

**Issue by fortuna** [Jigsaw-Code/outline-client#1128]
The network stack is selected based on the `NETWORK_STACK` variable, which is [set by webpack](https://github.com/Jigsaw-Code/outline-client/blob/aabedadbe703345ff4e2663ec12fd1b8d0615a15/src/electron/electron_main.webpack.js#L42) and can be overridden with a env variable with the same name at build time.

We can migrate Linux and Windows independently by setting the env variable when calling the `release_{linux,windows}` action. We need a way to validate it's using the right stack, perhaps we can look at the debug logs.

- [x] Pre-check (Windows & Linux)
- [x] Update code repository
- [ ] Release pipeline dry run for Linux
- [ ] Post-validate and publish (Linux)
- [ ] Manual release for Windows
- [ ] Post-validate and publish (Windows)
- [ ] Delete `NETWORK_STACK`, https://github.com/Jigsaw-Code/outline-client/blob/master/src/electron/sslibev_badvpn_tunnel.ts and its dependencies 

@daniellacosse it may be helpful to prioritize linux in the release process, since it doesn't need to be signed and we can leverage the clean build from the CI. For Windows we currently have to build it locally anyway, so it's not blocked by the release process.

**Comment by daniellacosse** [comment]
I had intended to start with the linux process this week! So glad to hear we're on the same page about that.
