### ISSUE TITLE
Cannot rename an outline server

### ISSUE THREAD

**Issue by jyyi1** [Jigsaw-Code/outline-client#1131]
**Describe the bug**
We are not able to rename an outline server in the client.

**To Reproduce**

1. Start a new Outline instance
2. Make sure you have at least one outline server added
3. Click "..." -> "rename" to rename a server
4. Type a new name and click "SAVE"
5. Client says "Server renamed" but the name is not changed in the server list

**Expected behavior**
Server list should be updated with the new name.

**Client System (please complete the following information):**
 - Outline Client Version: Latest
 - Your Operating System: Windows 11

**Additional context**
The underlying data structure is updated because when you try to rename it again, the text in the dialog is the new name.

**Workaround**
Switch to another language, and server name will be updated.

**Comment by daniellacosse** [comment]
Probably caused this when migrating to TS - LMK if you have any questions
