### ISSUE TITLE
Outline

### ISSUE THREAD

**Issue by LiVanJam** [Jigsaw-Code/outline-client#1149]
**Describe the bug**

**To Reproduce**
How can the broken behavior be reproduced? 

**Expected behavior**
What behavior did you expect?

**Screenshots**

**Client System (please complete the following information):**
 - Outline Client Version [e.g. iOS 1.3.1]
 - Your Operating System: [e.g. iOS 14.2, Windows 10]

**Submit Feedback**
Please submit feedback through the app and label it with this issue number.

**Additional context**

**Comment by jyyi1** [comment]
Hi @LiVanJam , could you please fill in the bug template above so we can know more about the issue you've met?

**Comment by LiVanJam** [comment]
sorry,i do not know.

**Comment by jyyi1** [comment]
It seems not to be related to outline-client.
