### ISSUE TITLE
Clash

### ISSUE THREAD

**Issue by LiVanJam** [Jigsaw-Code/outline-client#1154]
https://github.com/yichengchen/clashX/releases/tag/1.90.0

**Comment by jyyi1** [comment]
@LiVanJam ，看上去你贴的这个clashX并没有使用Outline Client，所以你需要Outline Client解决什么问题？（也包括之前创建的两个Issue，我也没有找到和Outline Client关联的地方）

**Comment by jyyi1** [comment]
It seems not to be related to outline-client.
