### ISSUE TITLE
Blank app screen

### ISSUE THREAD

**Issue by ArsenBespalov** [Jigsaw-Code/outline-client#117]
I find this problem, and says this bug fixed in 1.1.0 version, but not for me, I see this:

![](https://camo.githubusercontent.com/c32f7c1c1c50d01efe4d9938929c548d4f82df1a/68747470733a2f2f736e61672e67792f426c4c6a30672e6a7067)

OS X: 10.11.6
Client: 1.1.0

**Comment by alalamav** [comment]
v1.1.0 was released prior to the fix. The fix will go out in __v1.1.1__.
