### ISSUE TITLE
Outline client macos dmg

### ISSUE THREAD

**Issue by AnonymousWebHacker** [Jigsaw-Code/outline-client#1177]
There are many users who would like to use Outline, but AppStore it is not available in many countries, including mine. I tried to search the internet for the dmg client, but only found the Outline manager. 

Could someone please upload the dmg client and share it?

**Comment by daniellacosse** [comment]
Correct me if I'm wrong @fortuna but does this run up against the apple ToS? If not, I can add it to `outline-releases` in https://github.com/Jigsaw-Code/outline-client/pull/1176

**Comment by AnonymousWebHacker** [comment]
It would be very good if in the releases, they put the dmg to install them

**Comment by fortuna** [comment]
As far as I remember, we can't use DMG because of the Network Extension entitlements and it has to be distributed via the Apple store.

**Comment by AnonymousWebHacker** [comment]
So is that more important, to people who can't install outline because the store is blocked for them?
hahah wow

**Comment by NetBUG** [comment]
> Correct me if I'm wrong @fortuna but does this run up against the apple ToS? If not, I can add it to `outline-releases` in #1176

That would be very nice.
Telegram, for example, distributes a specific non-MAS version without content filtering: https://github.com/overtake/TelegramSwift

**Comment by fortuna** [comment]
Unfortunately we don't have an Apple developer anymore, so we need to figure out how to generate the DMG properly. It seems we need to notarize it in order for the network permissions to work correctly.

If there are Apple experts here that can advise, that would be welcome.

**Comment by NetBUG** [comment]
[Outline.dmg.zip](https://github.com/Jigsaw-Code/outline-client/files/9140362/Outline.dmg.zip)
In fact, I managed to make a dmg file with Outline.app. 
Might help someone. It asks for permissions when launched and the respective permission is invoked.

**Comment by ramyareye** [comment]
I couldn't manage to download dmg file.
simply sent the Outline app from my application folder to my friend and it worked!

**Comment by ramyareye** [comment]
but why it's impossible to find the latest dmg file? only exe and apk is available!

**Comment by tyv** [comment]
Since there is still an issue for places where app store is not available. Are there any instructions to connect to outline created vpn via standard mac os interface or with openvpn?

**Comment by Simplici** [comment]
> [Outline.dmg.zip](https://github.com/Jigsaw-Code/outline-client/files/9140362/Outline.dmg.zip) In fact, I managed to make a dmg file with Outline.app. Might help someone. It asks for permissions when launched and the respective permission is invoked.

Thanks very much.
May you please generate a new version based on the latest source code?

**Comment by NetBUG** [comment]
Well, I took the ready build and put it into a folder
Is there a build for MacOS, or I need to build it from scratch?
I can try in the evening

**Comment by fortuna** [comment]
According to Apple, PacketTunnelProvider app extenstions are restricted to App store distribution only:

https://developer.apple.com/documentation/technotes/tn3134-network-extension-provider-deployment#Deploying-a-packet-tunnel-provider
<img width="820" alt="image" src="https://github.com/Jigsaw-Code/outline-client/assets/113565/c61e3272-7905-45d8-901a-a3c43aa35ea4">

That means we can't distribute our client as a DMG (they will probably fail to connect).

Perhaps we can investigate the system extension approach. That seems to be possible to distribute outside the App Store, but I don't really know how it works.

**Comment by fortuna** [comment]
I found this information, which may suggest it's possible to distribute the app outside the App Store:
https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_networking_networkextension#discussion
![image](https://github.com/Jigsaw-Code/outline-client/assets/113565/9d111443-b7e6-4960-9274-d32e6e0cb2fa)

My guess is that the Packet Tunnel Provider is more restricted than the Network Extension in general.

**Comment by fortuna** [comment]
The [Tailscale documentation](https://tailscale.com/kb/1065/macos-variants) also confirms that the app must be on the App Store to use the NetworkExtension.

It's possible to bypass that restriction if we implement the VPN as a System Extension, but [they are deprecated](https://developer.apple.com/support/kernel-extensions/).

**Comment by khantseithu** [comment]
> [Outline.dmg.zip](https://github.com/Jigsaw-Code/outline-client/files/9140362/Outline.dmg.zip) In fact, I managed to make a dmg file with Outline.app. Might help someone. It asks for permissions when launched and the respective permission is invoked.

you're a life saver

**Comment by arbass** [comment]
> [Outline.dmg.zip](https://github.com/Jigsaw-Code/outline-client/files/9140362/Outline.dmg.zip) In fact, I managed to make a dmg file with Outline.app. Might help someone. It asks for permissions when launched and the respective permission is invoked.

thanks a lot!

**Comment by Salfden** [comment]
> [Outline.dmg.zip](https://github.com/Jigsaw-Code/outline-client/files/9140362/Outline.dmg.zip) In fact, I managed to make a dmg file with Outline.app. Might help someone. It asks for permissions when launched and the respective permission is invoked.

Saved me!  Thanks a lot!

**Comment by AlexeyShaykov** [comment]
@NetBUG Hi and HELP! please provide new dmg file!! 

Please. Can`t install it from App Store

**Comment by RomanIzvozchikov** [comment]
Recently I installed TunnelBear VPN on my Mac (Sequoia 15.2) without AppStore using DMG file provided on [TunnelBear Downloads](https://www.tunnelbear.com/download) page. There is Network Extensions menu available on System Settings => General => Login Items and Extensions => Network Extensions. After installation of TunnelBear VPN user should enable TunnelBear VPN in Network Extensions menu to make able TunnelBear VPN modify NE settings. It won't work without enabling this option. I don't know whether previous macOS versions contain this option, but probably now we don't need to store Outline VPN Mac desktop app in AppStore to have the ability to modify macOS network extensions settings.

I added some screenshots to make this point more clear.

<img width="827" alt="Screenshot 2025-01-06 at 10 09 54" src="https://github.com/user-attachments/assets/b5021d23-183a-4557-82e8-4a69fac4d342" />
<img width="827" alt="Screenshot 2025-01-06 at 10 10 02" src="https://github.com/user-attachments/assets/fc08e374-374c-4d73-b989-42927cc92a63" />
<img width="827" alt="Screenshot 2025-01-06 at 10 10 06" src="https://github.com/user-attachments/assets/47ddc536-696b-431e-8e01-3a8a64d79ebe" />
<img width="827" alt="Screenshot 2025-01-06 at 10 24 02" src="https://github.com/user-attachments/assets/1784e0fb-2fad-4a4a-aa1b-df4c956ee7d7" />

**Comment by AlexeyShaykov** [comment]
@RomanIzvozchikov downloaded, instaled but no connection.

**Comment by wang2code** [comment]
I'm using macOS 1.14.1 with the Network System Extension to create a DMG. The VPN connects just fine, but apps can't seem to connect to the internet. For example, Safari says 'Cannot connect to server,' even though ping works fine. Weirdly, when I open Proxyman, everything works perfectly—Safari can browse the web, and Spotify works like usual.


Anyone have any other ideas? Which way should I go to fix this?

**Comment by notpushkin** [comment]
@fortuna 

> It's possible to bypass that restriction if we implement the VPN as a System Extension, but [they are deprecated](https://developer.apple.com/support/kernel-extensions/).

I think you’re confusing system and kernel extensions – the later are deprecated, with the former intended as the replacement for. Tailscale docs sum that up quite nicely:

> In macOS 10.15, Apple added support for the [system extensions](https://developer.apple.com/system-extensions) approach to implement VPNs. System extensions offer a more secure alternative to the legacy Kernel Extensions technology previously used by many security and networking tools on older macOS versions. These extensions run with root privileges but remain within a sandbox, ensuring that Tailscale operates isolated from the macOS kernel. A key advantage of system extensions is their ability to be distributed outside of the Mac App Store.

And in fact Tailscale still recommends their standalone build over the Mac App Store one. Maybe using the system extension approach could work for Outline, too?

**Comment by fortuna** [comment]
Thanks @notpushkin , it seems I was confused with system and kernel extensions.

Based on @RomanIzvozchikov experience [above](https://github.com/Jigsaw-Code/outline-apps/issues/1177#issuecomment-2572465935), it looks like the user has to manually enable the system extension, so there's a trade-off there.

In any case, it's not clear to me when a NetworkExtension is an app or system extension, and I don't know what changes would have to be made to make our extension work as a system extension, and how to effectively keep sharing code between iOS and macOS with mac Catalyst.

This is not on our priority list, so we will need someone else to figure it out and share a proposal.

**Comment by ohnorobo** [comment]
FYI Amnezia is also able to provide a PKG https://github.com/amnezia-vpn/amnezia-client/releases/download/4.8.12.9/AmneziaVPN_4.8.12.9_macos.pkg

**Comment by fortuna** [comment]
> FYI Amnezia is also able to provide a PKG https://github.com/amnezia-vpn/amnezia-client/releases/download/4.8.12.9/AmneziaVPN_4.8.12.9_macos.pkg

@ohnorobo What's the user experience like?

**Comment by RomanIzvozchikov** [comment]
> Thanks [@notpushkin](https://github.com/notpushkin) , it seems I was confused with system and kernel extensions.
> 
> Based on [@RomanIzvozchikov](https://github.com/RomanIzvozchikov) experience [above](https://github.com/Jigsaw-Code/outline-apps/issues/1177#issuecomment-2572465935), it looks like the user has to manually enable the system extension, so there's a trade-off there.
> 
> In any case, it's not clear to me when a NetworkExtension is an app or system extension, and I don't know what changes would have to be made to make our extension work as a system extension, and how to effectively keep sharing code between iOS and macOS with mac Catalyst.
> 
> This is not on our priority list, so we will need someone else to figure it out and share a proposal.

Just want to let you know that Apple deletes any VPN apps by requests from governments (like Belarus, Russia and so on). I can't download Surfshark, Tunnelbear VPN apps from Belarussian AppStore and mac AppStore. So it is just a time based question, when Outline VPN will be deleted from AppStore of such countries.

From my perspective you need to reprioritize this.

**Comment by fortuna** [comment]
@RomanIzvozchikov I'm aware of that. Outline, however, is in a different position: unlike a regular VPN, the Outline Client doesn't come with an embedded service, which makes it compliant with the regulations (as draconian as they are).
