### ISSUE TITLE
getting this error at run time linux

### ISSUE THREAD

**Issue by patsonkaushik** [Jigsaw-Code/outline-client#1181]
npm run action src/electron/start  linux command run but issue in lunix 
![WhatsApp Image 2022-02-15 at 11 56 17 AM](https://user-images.githubusercontent.com/77775964/154005717-21bbbecb-7644-49a3-8c49-f722830f8069.jpeg)

**Comment by daniellacosse** [comment]
Hey - it seems the error coming from the JS above is cut off - do you mind pasting the full text?

**Comment by patsonkaushik** [comment]
Screenshort of full text
![22](https://user-images.githubusercontent.com/77775964/155076345-806c400a-9333-45c1-8a49-f046f9d26138.jpeg)

**Comment by patsonkaushik** [comment]
node version -:16.13.0

**Comment by maddyhof** [comment]
Closing as obsolete
