### ISSUE TITLE
SetSystemProxy.exe triggering malware alert

### ISSUE THREAD

**Issue by justshrey** [Jigsaw-Code/outline-client#12]
Hey

Been trying to download this Outline-Client,exe and i keep getting an alert on my anti virus. Have narrowed it down to SetSystemProxy.exe

Ran this through online malware analysis and it keep saying its infected. Its mostly is a false positive, but thought it good to bring to attention since most non-technical users might freak at this. 

Would like your inputs. 

Here are some reports

https://vicheck.ca/htmlreport.php?SHA=9633560ad4f17effc050d832590835ce727d31762b574c5dc88c3697a3aa0391

![image](https://user-images.githubusercontent.com/1253625/37731831-bb3293ec-2d5c-11e8-93b4-7d67e263af85.png)

https://www.virustotal.com/#/file/9633560ad4f17effc050d832590835ce727d31762b574c5dc88c3697a3aa0391/detection

( I know there are more engines which classify this as a virus. Kaspersky for sure does. )

**Comment by neoexa** [comment]
While installing the client, Kaspersky detected the file _setsystemproxy.exe_ as a _Trojan.Win32.Snojan.ceco_ and deleted it, therefore my client app is not working.

**Comment by jeremyverda** [comment]
Hello,

I have the same issue with Bitdefender.
It's recognized as "Trojan.GenericKD.30445288".

**Comment by leifrogers** [comment]
same - with windows defender identifying it as _Trojan:Win32/Spursint.F!cl_

**Comment by trevj** [comment]
All, many thanks for the feedback.

We have just pushed a new version of Outline for Windows which should help with If you close and restart Outline, it should automatically download and install the update. Please let us know if you still have problems after the update. To verify you're running the new version, 1.0.1, open the About page from the side menu.

**Comment by trevj** [comment]
All, a couple of days ago we pushed another Windows client update which should help further with the issues you've been seeing. Again, restart Outline and wait for a message confirming that an update has been downloaded. This is client version 1.0.2.

**Comment by alalamav** [comment]
I think this issue has been fixed since signing the binary. Closing now, but feel free to reopen.
