### ISSUE TITLE
Is it possible to minimize outline client to system tray?

### ISSUE THREAD

**Issue by limonte** [Jigsaw-Code/outline-client#120]
I'd expect Outline Windows client to be here: 
![image](https://user-images.githubusercontent.com/6059356/40537572-3bebdfaa-604a-11e8-9517-7b02e7cd43fb.png)

Instead of

![image](https://user-images.githubusercontent.com/6059356/40537616-5086c02e-604a-11e8-9168-b0df3b27f460.png)

Is it possible?

**Comment by fortuna** [comment]
Not yet, but that's something we want to do

**Comment by alalamav** [comment]
Thanks for the feedback, @limonte. This is tracked in #20.
