### ISSUE TITLE
Windows Client Release Process

### ISSUE THREAD

**Issue by fortuna** [Jigsaw-Code/outline-client#1212]

**Comment by jyyi1** [comment]
TODO items:

- [x] Cross-platform signing tools (jsign) and scripts preparation
- [x] Can sign Windows executables using physical USB EV certificate in Windows/macOS
- [ ] (WIP) Cloud HSM preparation
- [ ] Certificate issuing from CA to Cloud HSM
- [ ] Scripts updated to leverage Cloud HSM based certificate

**Comment by fortuna** [comment]
Tracking internally
