### ISSUE TITLE
Push current Linux client to S3

### ISSUE THREAD

**Issue by fortuna** [Jigsaw-Code/outline-client#1240]
It seems the Linux client is not updated on S3, based on what I saw at https://github.com/Jigsaw-Code/outline-client/issues/1089.

We need to:
- [x] Push the current client to S3
- [x] Make sure the release process updates S3

/cc @jyyi1 @daniellacosse

**Comment by daniellacosse** [comment]
https://github.com/marketplace/actions/upload-s3

**Comment by fortuna** [comment]
Let's make sure Windows is also covered

**Comment by fortuna** [comment]
It seems this is the URL: https://github.com/Jigsaw-Code/outline-client/blob/b967567f1a62c718df55e1fe9051ea0b5e28ebd1/scripts/get_electron_build_flags.mjs#L39

But we also have:
- https://github.com/Jigsaw-Code/outline-releases/blob/master/client/latest.yml
- https://github.com/Jigsaw-Code/outline-releases/blob/master/client/latest-linux.yml

Are those even being used?
We should pick either S3 or Github. It doesn't really make sense to have both, I think.
@alalamav do you have more insight here?

**Comment by daniellacosse** [comment]
If we can get away with just github that would be my vote. Fewer moving parts and we can merge repos once we add shallow cloning/pruning.

**Comment by jyyi1** [comment]
There is already an [action to do that in outline-releases](https://github.com/Jigsaw-Code/outline-releases/blob/master/.github/workflows/upload_linux_client_to_s3.yml). We just need to confirm whether that works. But now it will only be triggered when you push Linux binaries in outline-releases.
