### ISSUE TITLE
Linux client does not work for Ubuntu for the first time

### ISSUE THREAD

**Issue by jyyi1** [Jigsaw-Code/outline-client#1269]
**Describe the bug**
I am not able to connect to the VPN server the first time I run Outline client. After restarting the client, it works.

**To Reproduce**
1. Using a clean Ubuntu machine
2. Double click Outline-Client.AppImage
3. Type in the root password if prompted
4. Though the UI shows connected, actually it is not
5. You will not be able to disconnect as well
6. Not able to quit as well

**Expected behavior**
We should successfully connect to the VPN server.

**Screenshots**
![image](https://user-images.githubusercontent.com/93548144/164537316-cbaca118-2a3e-4727-99a6-cc2c63fe178d.png)

**Client System (please complete the following information):**
 - Outline Client Version 1.4.0 and 1.7.0-dev
 - Your Operating System: Ubuntu 20.04

**Comment by aaaamirabbas** [comment]
This problem exists in the following versions and I tested it.

**Ubuntu 20.04
Ubuntu 21.10
Ubuntu 22.04
PopOS 22.04**

Please fix this bug.
