### ISSUE TITLE
User online indicator, key activation once

### ISSUE THREAD

**Issue by ogienkoS** [Jigsaw-Code/outline-client#1270]
Dear developers, I would really like to see two features:

1) User online indicator.
2) Using the access key once, so that there is no way to activate it again.

**Comment by bemasc** [comment]
It sounds like you are asking for features in the server manager.  This issue tracker is for the Outline Client.

I think your requests are covered by these two server feature requests:
* https://github.com/Jigsaw-Code/outline-server/issues/214
* https://github.com/Jigsaw-Code/outline-server/issues/546
