### ISSUE TITLE
Adding access key is not working; doesn't show version number on interface

### ISSUE THREAD

**Issue by annyw** [Jigsaw-Code/outline-client#1277]
**Describe the bug**
can't add a server

**To Reproduce**
1. copy access key
2. paste on access key input 
3. didn't give any feedback

**Expected behavior**
1. paste on access key input 
2. add a server

**Screenshots**
![2022-04-29 00 19 03](https://user-images.githubusercontent.com/19884001/165798635-e134fe96-0f4a-48d8-b247-5c5bc0df860b.jpg)

**Client System (please complete the following information):**
 - Outline Client Version: 1.5.0 (just download from app store)
 - Your Operating System: macOS 10.12.6

**Comment by Mahmood10marde** [comment]
Bj JV v

**Comment by Mahmood10marde** [comment]
Vgf
