### ISSUE TITLE
Client for wireless routers

### ISSUE THREAD

**Issue by ghost** [Jigsaw-Code/outline-client#133]
I suggest creating a client for wireless routers that at least supports DD-WRT and OpenWRT, the most common custom router firmwares.

**Comment by studentmain** [comment]
Use shadowsocks-libev, you may need use base64 decoder to decode ss url. Outline client is for device with GUI, a client for CLI is too hard ( if not impossible ) for Electron.

But a simple client use ncurse or some other thing is OK. Manage multiple server with configuration file is boring.

**Comment by YegorIevlev** [comment]
@studentmain I would like it to redirect all traffic, including UDP traffic generated by router using tun2socks, instead of using transparent proxying. This requires a tun2socks build with Outline modifications to allow UDP redirection. I think the client simply needs a LuCI frontend for OpenWRT for GUI. DD-WRT version doesn't need a GUI.

**Comment by YegorIevlev** [comment]
@studentmain Would be cool to have pfSense/FreeBSD client. It doesn't need a GUI.

**Comment by studentmain** [comment]
Just keep thing simple, a *nix client with ncurse 'gui'. Web UI can be
optional. But, ummmm... I think we must do it ourselves... This project is
for device with GUI, not for device which only have terminal.
If you need client for *nix now, you still can use ss-libev and ss-qt5
(which have a GUI). You said that you want traffic from router itself go
through shadowsocks, maybe you need iptables to do some redirect.

Yegor Ievlev <notifications@github.com> 于 2018年6月17日周日 20:34写道：

**Comment by YegorIevlev** [comment]
@studentmain Only `tun2socks` allows to redirect UDP traffic originating from the router. Using UDP transparent proxying doesn't allow that.

**Comment by trevj** [comment]
@YegorIevlev Thanks for using Outline and for your suggestion! We are open to new platforms but as @studentmain rightly points out, Electron is not going to run very well on a device like a router. I do think a Shadowsocks-powered router is a neat idea, though.

**Comment by Mygod** [comment]
Just to mention this is already possible: https://github.com/shadowsocks/luci-app-shadowsocks

Also possible: [sharing VPNs with a rooted Android phone].

**Comment by YegorIevlev** [comment]
@Mygod This solution doesn't handle UDP traffic. Thanks for the link. I wanted to get a travel router because I didn't knew that Android phone is enough.

**Comment by Mygod** [comment]
Assuming you're talking about luci-app-shadowsocks, README says you need to have `iptables-mod-tproxy, ip` to use UDP traffic.
