### ISSUE TITLE
Does Outline Manager have a function to limit the usage time of tokens? Similar to data limit, is there a time limit？

### ISSUE THREAD

**Issue by ChenforCode** [Jigsaw-Code/outline-client#1332]
for example, we can set a expire time for a token,  such as 1 day, after 1 day, this token will be not available.
Sincerely waiting for your replay, thanks!

**Comment by bemasc** [comment]
No, the Outline Manager does not have such a feature.  However, the Outline Server accesses the Outline manager via REST API that supports creating and destroying Access Keys, so you can automate this externally by sending a deletion command at the appropriate time.
