### ISSUE TITLE
Long server name cause layout problem.

### ISSUE THREAD

**Issue by studentmain** [Jigsaw-Code/outline-client#136]
![img_20180619_111058](https://user-images.githubusercontent.com/17123090/41573913-a127a87a-73b1-11e8-8480-242681e70de7.jpg)
![img_20180619_111025](https://user-images.githubusercontent.com/17123090/41573914-a16321ca-73b1-11e8-9b2f-9e6a03a536c8.jpg)
![img_20180619_111149](https://user-images.githubusercontent.com/17123090/41573915-a19c9838-73b1-11e8-9a73-027267562525.jpg)

Mi 5X, MIUI9.5, Outline 1.1.1
I try to parse multiple ss link like this:
```
ss://base64-1@ip1:port1#server1
ss://base64-2@ip2:port2#server2
ss://base64-3@ip3:port3#server3
ss://base64-4@ip4:port4#server4
ss://base64-5@ip5:port5#server5
```

**Comment by ky0nch3ng** [comment]
Rename it to solved.

**Comment by trevj** [comment]
@studentmain Thanks for trying Outline and for reporting this. We probably should truncate extremely long server names.

**Comment by lgg** [comment]
@trevj i've just tested this issue and now server name is truncated to 100 symbols. I thinks it's fixed now.

**Comment by lgg** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/word-break
I was choosing between: `break-word` and `break-all` and choose `break-word` because Cordova and Electron is based on Chromium(https://caniuse.com/#search=word-break)
