### ISSUE TITLE
Can't find the `connect` button

### ISSUE THREAD

**Issue by fengjiachun** [Jigsaw-Code/outline-client#1372]
**Describe the bug**
In the first two lines of this list, I can't find the `connect` button, maybe there is some format that restricts it, the line is too short for the button to show.

<img width="350" alt="image" src="https://user-images.githubusercontent.com/3860496/182058978-90454959-5b06-4f11-9768-616aabc08c2a.png">

**To Reproduce**
<img width="346" alt="image" src="https://user-images.githubusercontent.com/3860496/182059096-f522cf52-4073-45bf-b1f7-a3bbcea58524.png">

**Expected behavior**
What behavior did you expect?

**Screenshots**

**Client System (please complete the following information):**
 - Outline Client Version [1.7.1]
 - Your Operating System: [MacOS Monterey 12.5, M1]

**Submit Feedback**
Please submit feedback through the app and label it with this issue number.

**Additional context**

**Comment by daniellacosse** [comment]
Workaround for now - add spaces to your server names
