### ISSUE TITLE
iOS build fails due to Node.js 10 incompatibility

### ISSUE THREAD

**Issue by zfavourite99** [Jigsaw-Code/outline-client#138]
yarn run v1.7.0
$ /Users/zbf/Downloads/outline-client-daily-2018-06-14/node_modules/.bin/gulp build --platform=ios
gulp[39202]: ../src/node_contextify.cc:628:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
 1: node::Abort() [/usr/local/bin/node]
 2: node::InternalCallbackScope::~InternalCallbackScope() [/usr/local/bin/node]
 3: node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 4: v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/bin/node]
 5: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 6: v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x10a3f2c8427d
 8: 0x10a3f2c8f755
 9: 0x10a3f2d0bc20
10: 0x10a3f2c944f7
11: 0x10a3f2c944f7
12: 0x10a3f2c944f7
error Command failed with signal "SIGABRT".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by itmihang** [comment]
about ----> Assertion `args[1]->IsString()' failed.
try to `yarn upgrade gulp`

**Comment by trevj** [comment]
@zfavourite99 Thanks for trying Outline! Sorry you've been having problems building it. I believe your problem is due to incompatibility with Node.js 10+. I recently merged https://github.com/Jigsaw-Code/outline-client/pull/175 which should address this. Can you please pull the latest code and try again?

**Comment by trevj** [comment]
@zfavourite99 Please re-open if you continue to experience build errors.
