### ISSUE TITLE
Authorization of Digital Ocean on macOS is stuck

### ISSUE THREAD

**Issue by larsboehnke** [Jigsaw-Code/outline-client#139]
I set up Outline on a macOS machine and signed in to my Digital Ocean account. However, once Outline asks me to grant permissions I am stuck, I can see no way how to proceed.

![image](https://user-images.githubusercontent.com/11321756/41676209-17c6ba84-74c5-11e8-9696-1a9798c4d6f1.png)

**Comment by alalamav** [comment]
Hi @larsboehnke, thanks for the feedback. We have rolled out an improved OAuth flow for DigitalOcean in the [Outline Manager v1.1.2](https://github.com/Jigsaw-Code/outline-releases/tree/master/manager). This issue is fixed there.
