### ISSUE TITLE
can't send email on iOS while connected with Outline server

### ISSUE THREAD

**Issue by davidwerent** [Jigsaw-Code/outline-client#1393]
**Describe the bug**
 while the connection to Outline server is established, can't send email from native iOS app. 
 All letters is stucked in outcoming folder, until you turn off VPN

**To Reproduce**
use iphone with native mail app and try to send some mail

**Expected behavior**
a letter will be send instantly while vpn is on

**Screenshots**

**Client System (please complete the following information):**
 - Outline Client Version iOS 1.7.2
 - Your Operating System: iOS 15.3+

**Submit Feedback**
issue № 00058880

**Comment by alexsok-bit** [comment]
all works. I successfully sent 2 emails from yahoo to icloud and back.
