### ISSUE TITLE
The access key is invalid. (Win11 Client)

### ISSUE THREAD

**Issue by jean-louis1776** [Jigsaw-Code/outline-client#1397]
### Describe the bug
Windows 11. The client worked properly, but for a week now it has been impossible to connect to the server. Access keys to the server are also on 4 phones, clients connect to the server without problems. This problem is only on the computer. Error Message (The error is written in Russian, so I translated it into English): "The access key is invalid. If this error occurs again, contact the server administrator".

### To Reproduce
An error appeared unexpectedly and by itself.

### Expected behavior
The client was expected to connect me to the server as other clients are working properly

### Screenshots
![screenshot](https://user-images.githubusercontent.com/79199806/188270717-560c1dfc-1b4b-435e-a856-a13e5493f4ec.jpg)

### Client System (please complete the following information):
 - Outline Client Version - 1.7.1
 - Your Operating System: Windows 11 21H2

**Comment by maddyhof** [comment]
Thanks for reaching out. The Outline team does not provide access keys to users. For troubleshooting support, please contact the server manager who provided your key.
