### ISSUE TITLE
Server address is no longer copyable

### ISSUE THREAD

**Issue by fortuna** [Jigsaw-Code/outline-client#1411]
We can no longer select and copy the IP address and port number on the server card. This makes it harder to debug, since we need to manually type the address.

@daniellacosse this is a regression, it did not use to be like that. I imagine it's an easy fix?

**Comment by daniellacosse** [comment]
I think I already fixed this - current master (not released yet):

<img width="594" alt="Screen Shot 2022-09-30 at 13 20 27" src="https://user-images.githubusercontent.com/3759828/193258931-e1110f5d-133d-4fa1-98cb-f253675c61ac.png">

**Comment by daniellacosse** [comment]
This should be the version we're currently QAing

**Comment by fortuna** [comment]
Ah, I thought you had fixed it. Thanks!
