### ISSUE TITLE
Outline in GCP does not work in Iran. It seems that GCP servers are not accessible from IRAN, but digital ocean works

### ISSUE THREAD

**Issue by amirjalali1** [Jigsaw-Code/outline-client#1413]

**Comment by euphoria360** [comment]
Yeah they are blocked. since looooooong time ago! Google is acting like A$#holes unfortunately!
BTW i didnt have any luck setting up Outline Server on my VPS tonight. Clients get connected but no data transfer happens.
I dont know if its caused by a setup error or Islamic Regime DPI $hit is blocking shadowsocks

**Comment by shahesam84** [comment]
Same problem, successfully connected but no up/down, also existing on DO servers.

**Comment by morybest** [comment]
Irancell and IR-TCI(Mokhaberat) banned shadow socks , but still we can use outline "Hamrah1" mobile operator  . Friends in Iran please put your experience about this . which server worked for you . we  are using amazon digital ocean now.

**Comment by M-Amrollahi** [comment]
> ssfully connected but no up/down, also existing on DO server

True, there is no transfer but it seems it is connected.

**Comment by NavidV** [comment]
I have a server located in US which is not working for Iran now. How if we have teh server outside of US for exampel in Asia or EU ?

**Comment by Ebaharloo** [comment]
Nonworking! Amazon, google! Server in us or India! Nonworking!

**Comment by damoontahmasbi** [comment]
I had no luck so far with GCP or AWS. 
I have tried GCP servers in India and Germany, and I've tried  AWS servers in India and Poland.

**Comment by saeidkhoorani** [comment]
I prefer Linode for it, and connected properly!

**Comment by PICLTD** [comment]
There's a solution, you need to use mask to hide provided premium IP by google, use static based on your verified IP then it's okay, but if you're gonna contribute it, then it will be banned again, so configure load balancer using UDP and reserved for the TCP, ping it first to make sure it works then reserve it. you've other solution to use HA, it's little bit costly. Digital Ocean or Amazon is also okay but the big benefit with the Google Cloud, is that if you're fine with a US IP, you can use the free tier, and run your VPN non-stop for free. The benefit of Digital Ocean, though - is that you have a fixed price for any location. So for $6 you can get a VPN anywhere Digital Ocean has a location. Or for $0 you can get a Google Cloud VPN in the US. Both with 1GB of bandwidth, and you'll pay extra for going over that. Good luck guys. 👍

**Comment by saeidkhoorani** [comment]
Thanks a lot for the solution, I'll update you about it!

**Comment by EhsanMehryaar** [comment]
> Thanks a lot for the solution, I'll update you about it!

Any luck?

**Comment by ghatighorias** [comment]
No success for me either. I have checked with people in Iran and am afraid the issue is not server at all. it is with the new method that the Iran government is battling VPNs. they are fluctuating the speed of the internet so much that most VPNs can't establish a secure connection. A more flexible Vpn like express-vpn is working without much problem while the outline fails to establish the basic connection.

**Comment by Darklight007** [comment]
Any update please?

**Comment by hashemhaghighat** [comment]
من به تازگی چندین سرور اوت لاین ساختم اما فقط روی اپراتور همراه اول کار میکند!
به تازگی با شخصی آشنا شدم که کلید دسترسی میفروشد که روی همه اپراتور ها کار میکند
او از hetzner استفاده میکند برای ساخت سرور و از آی پی آلمان

I just made several outline servers but it only works on the first mobile operator!
I recently met someone who sells an access key that works on all operators
He uses Hetzner to build the server and the German IP
