### ISSUE TITLE
Download apps directly

### ISSUE THREAD

**Issue by hooshyar** [Jigsaw-Code/outline-client#1415]
I want to be able to download apps directly, without the need for app stores. 
I tried to build the .IPA for a friend to put in on google drive but, the IPA throws exceptions.

**Comment by daniellacosse** [comment]
Just out of curiosity, what exceptions were thrown?

**Comment by amirqasemi74** [comment]
app store is filter in iran. please provide direct download for mac os

**Comment by vohuman** [comment]
Yes, I want to send apk file to my family in Iran but google play store is blocked in Iran by the government, even I heard the whole Google is blocked

**Comment by daniellacosse** [comment]
Check out github.com/Jigsaw-Code/outline-releases. There are raw binaries there you can install. Let us know if that's blocked, too
