### ISSUE TITLE
M1 mac support?

### ISSUE THREAD

**Issue by wyntrson** [Jigsaw-Code/outline-client#1419]
It has been years but outline didn’t update the mac client to support Apple Silicon devices.

**Comment by zhqu1148980644** [comment]
My M2 mac works, you can install from app store.

**Comment by gut4** [comment]
https://github.com/Jigsaw-Code/outline-client/issues/940

**Comment by fortuna** [comment]
Duplicate of https://github.com/Jigsaw-Code/outline-client/issues/940

**Comment by steveg-sjg** [comment]
Use the ShadowSock client it works on M1/M2 and connects to Outline Servers as they use the same protocol, also import Outline keys for connections. https://shadowsocks.org/ https://github.com/shadowsocks/ShadowsocksX-NG/releases
