### ISSUE TITLE
Installion fails with error code 2

### ISSUE THREAD

**Issue by ITheEqualizer** [Jigsaw-Code/outline-client#1428]
**Describe the bug**
When I try to install the client on my PC, it says that the installation has failed with error code 2.
It has something to do with the TAP driver.

**To Reproduce**
Simply try to install.

**Expected behavior**
To finish the installation.

**Screenshots**
https://i.imgur.com/f6J9RJ2.png

**Client System (please complete the following information):**
 - Outline Client Version - Windows (Latest)
 - Your Operating System: Windows 10

**Comment by jyyi1** [comment]
Hi @ITheEqualizer, sorry about the inconvenience. Could you please double check which components failed to be installed? The following screenshots of the system components are expected.

1. <img width="762" alt="image" src="https://user-images.githubusercontent.com/93548144/197594224-59b6c097-0439-433c-a344-b0e5f5031f21.png">
2. <img width="890" alt="image" src="https://user-images.githubusercontent.com/93548144/197594993-aeba4811-2424-42dc-a9c6-12a93b3600c1.png">
3. <img width="563" alt="image" src="https://user-images.githubusercontent.com/93548144/197594861-019c104c-a8f9-468c-8a23-69a3634ed828.png">
