### ISSUE TITLE
How do I fix Failed to Starting Shadowbox for installing Outline ?

### ISSUE THREAD

**Issue by mojtabahakimian** [Jigsaw-Code/outline-client#1429]
The issue tracker is not for questions. Please ask questions at support@getoutline.org.
I have a VPS with below detail :

- (VPS in Europe)

- Ubuntu 18.04 -

- SSH Port is "2233"

I want to make the settings to install the outline , so I followed this steps

In this link : https://habr.com/en/post/448108/

docker is enabled successfully :

https://i.postimg.cc/xd7mLcSy/Screenshot-53.png

when I paste and run this command : sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"

I get this error :

https://i.postimg.cc/J4cjSrbM/Screenshot-52.png

root@VMID-3789:~# sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_serve [r.sh](https://r.sh/))"

> Verifying that Docker is installed .......... OK

> Verifying that Docker daemon is running ..... OK

> Setting PUBLIC_HOSTNAME to external IP ...... OK

> Creating persistent state dir ............... OK

> Generating secret key ....................... OK

> Generating TLS certificate .................. OK

> Generating SHA-256 certificate fingerprint .. OK

> Writing config .............................. OK

> Starting Shadowbox .......................... FAILED

> The container name "shadowbox" is already in use by another container. This ma y happen when running this script multiple times. We will attempt to remove the existing container and restart it. Would you like to proceed? [Y/n] y

> Removing shadowbox container ................ OK

> Restarting shadowbox ........................ OK

> Starting Watchtower ......................... FAILED

Unable to find image 'containrrr/watchtower:latest' locally

docker: Error response from daemon: Head "https://registry-1.docker.io/v2/containrrr/watchtower/manifests/latest": Get "https://auth.docker.io/token?scope=repository%3Acontainrrr%2Fwatchtower%3Apull&service=registry.docker.io": dial tcp: lookup [auth.docker.io](https://auth.docker.io/): Temporary failure in name resolution.

See 'docker run --help'.

Sorry! Something went wrong. If you can't figure this out, please copy and paste all this output into the Outline Manager screen, and send it to us, to see if we can help you.

Full log: /tmp/outline_logkUE

What Do I do ?

please guide me

related link:

- https://www.ashokkuikel.com/how-to-install-outline-server-on-ubuntu-20-04/

-https://www.reddit.com/r/outlinevpn/comments/oxn9hx/cannot_install_outline_server_to_ubuntu_20042_lts/

- https://github.com/Jigsaw-Code/outline-server/blob/master/src/server_manager/install_scripts/install_server.sh

**Comment by mojtabahakimian** [comment]
also : 
> Starting Shadowbox .......................... FAILED
docker: Error response from daemon: Conflict. The container name "/shadowbox" is already in use by container "45d40e1a60e42bd60bf55fe47e2e500b6a7cfea03f1f21b7635e5d9004edb992". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.

Sorry! Something went wrong. If you can't figure this out, please copy and paste all this output into the Outline Manager screen, and send it to us, to see if we can help you.
Full log: /tmp/outline_log4m0

**Comment by mojtabahakimian** [comment]
This is the list of commands that I execute in order : 
```
sudo -- sh -c 'apt-get update; apt-get upgrade -y; apt-get dist-upgrade -y; apt-get autoremove -y; apt-get autoclean -y'

sudo curl -sS https://get.docker.com/ | sh

sudo systemctl start docker

sudo systemctl enable docker

sudo sudo systemctl status docker

sudo wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh | bash
```
I reset the server and tested again but this time with ubuntu 20, now in this command "`sudo curl -sS https://get.docker.com/ | sh`" it gave me this error
that's why I went to install the doctor in another way by this link : [https://www.simplilearn.com/tutorials/docker-tutorial/how-to-install-docker-on-ubuntu](url)

my steps in the video : 
[https://easyupload.io/dqy792](url)

Full text of all the commands I used : 
`login as: root
root@92.119.59.85's password:
Welcome to Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0-72-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Mon Oct 10 06:43:04 UTC 2022

  System load:  0.07              Processes:             138
  Usage of /:   7.5% of 28.90GB   Users logged in:       0
  Memory usage: 9%                IPv4 address for eth0: 92.119.59.85
  Swap usage:   0%

 * Super-optimized for small spaces - read how we shrank the memory
   footprint of MicroK8s to make it the smallest full K8s around.

   https://ubuntu.com/blog/microk8s-memory-optimisation

0 updates can be applied immediately.

New release '22.04.1 LTS' available.
Run 'do-release-upgrade' to upgrade to it.


*** System restart required ***
Last login: Mon Oct 10 06:32:38 2022 from 5.124.144.154
root@VMID-3789:~# sudo -- sh -c 'apt-get update; apt-get upgrade -y; apt-get dis                                                                                                                     t-upgrade -y; apt-get autoremove -y; apt-get autoclean -y'
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Hit:3 http://security.ubuntu.com/ubuntu focal-security InRelease
Get:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Fetched 222 kB in 1s (263 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
Try Ubuntu Pro beta with a free personal subscription on up to 5 machines.
Learn more at https://ubuntu.com/pro
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
Try Ubuntu Pro beta with a free personal subscription on up to 5 machines.
Learn more at https://ubuntu.com/pro
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
root@VMID-3789:~# sudo curl -sS https://get.docker.com/ | sh
# Executing docker install script, commit: 4f282167c425347a931ccfd95cc91fab041d4                                                                                                                     14f
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-http                                                                                                                     s ca-certificates curl >/dev/null
+ sh -c mkdir -p /etc/apt/keyrings && chmod -R 0755 /etc/apt/keyrings
+ sh -c curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | gpg --dearmo                                                                                                                     r --yes -o /etc/apt/keyrings/docker.gpg
curl: (6) Could not resolve host: download.docker.com
gpg: no valid OpenPGP data found.
root@VMID-3789:~#  sudo apt-get remove docker docker-engine docker.io
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package docker-engine
root@VMID-3789:~#  sudo apt-get update
Hit:1 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Reading package lists... Done
root@VMID-3789:~# sudo apt install docker.io
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  bridge-utils containerd dns-root-data dnsmasq-base libidn11 pigz runc
  ubuntu-fan
Suggested packages:
  ifupdown aufs-tools cgroupfs-mount | cgroup-lite debootstrap docker-doc
  rinse zfs-fuse | zfsutils
The following NEW packages will be installed:
  bridge-utils containerd dns-root-data dnsmasq-base docker.io libidn11 pigz
  runc ubuntu-fan
0 upgraded, 9 newly installed, 0 to remove and 0 not upgraded.
Need to get 69.2 MB of archives.
After this operation, 334 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://archive.ubuntu.com/ubuntu focal/universe amd64 pigz amd64 2.4-1 [57                                                                                                                     .4 kB]
Get:2 http://archive.ubuntu.com/ubuntu focal/main amd64 bridge-utils amd64 1.6-2                                                                                                                     ubuntu1 [30.5 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 runc amd64 1.1.0                                                                                                                     -0ubuntu1~20.04.1 [3892 kB]
Get:4 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 containerd amd64                                                                                                                      1.5.9-0ubuntu1~20.04.4 [33.0 MB]
Get:5 http://archive.ubuntu.com/ubuntu focal/main amd64 dns-root-data all 201905                                                                                                                     2802 [5300 B]
Get:6 http://archive.ubuntu.com/ubuntu focal/main amd64 libidn11 amd64 1.33-2.2u                                                                                                                     buntu2 [46.2 kB]
Get:7 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 dnsmasq-base amd                                                                                                                     64 2.80-1.1ubuntu1.5 [315 kB]
Get:8 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 docker.io am                                                                                                                     d64 20.10.12-0ubuntu2~20.04.1 [31.8 MB]
Get:9 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 ubuntu-fan all 0                                                                                                                     .12.13ubuntu0.1 [34.4 kB]
Fetched 69.2 MB in 4s (16.5 MB/s)
Preconfiguring packages ...
Selecting previously unselected package pigz.
(Reading database ... 94915 files and directories currently installed.)
Preparing to unpack .../0-pigz_2.4-1_amd64.deb ...
Unpacking pigz (2.4-1) ...
Selecting previously unselected package bridge-utils.
Preparing to unpack .../1-bridge-utils_1.6-2ubuntu1_amd64.deb ...
Unpacking bridge-utils (1.6-2ubuntu1) ...
Selecting previously unselected package runc.
Preparing to unpack .../2-runc_1.1.0-0ubuntu1~20.04.1_amd64.deb ...
Unpacking runc (1.1.0-0ubuntu1~20.04.1) ...
Selecting previously unselected package containerd.
Preparing to unpack .../3-containerd_1.5.9-0ubuntu1~20.04.4_amd64.deb ...
Unpacking containerd (1.5.9-0ubuntu1~20.04.4) ...
Selecting previously unselected package dns-root-data.
Preparing to unpack .../4-dns-root-data_2019052802_all.deb ...
Unpacking dns-root-data (2019052802) ...
Selecting previously unselected package libidn11:amd64.
Preparing to unpack .../5-libidn11_1.33-2.2ubuntu2_amd64.deb ...
Unpacking libidn11:amd64 (1.33-2.2ubuntu2) ...
Selecting previously unselected package dnsmasq-base.
Preparing to unpack .../6-dnsmasq-base_2.80-1.1ubuntu1.5_amd64.deb ...
Unpacking dnsmasq-base (2.80-1.1ubuntu1.5) ...
Selecting previously unselected package docker.io.
Preparing to unpack .../7-docker.io_20.10.12-0ubuntu2~20.04.1_amd64.deb ...
Unpacking docker.io (20.10.12-0ubuntu2~20.04.1) ...
Selecting previously unselected package ubuntu-fan.
Preparing to unpack .../8-ubuntu-fan_0.12.13ubuntu0.1_all.deb ...
Unpacking ubuntu-fan (0.12.13ubuntu0.1) ...
Setting up runc (1.1.0-0ubuntu1~20.04.1) ...
Setting up dns-root-data (2019052802) ...
Setting up libidn11:amd64 (1.33-2.2ubuntu2) ...
Setting up bridge-utils (1.6-2ubuntu1) ...
Setting up pigz (2.4-1) ...
Setting up containerd (1.5.9-0ubuntu1~20.04.4) ...
Created symlink /etc/systemd/system/multi-user.target.wants/containerd.service →                                                                                                                      /lib/systemd/system/containerd.service.
Setting up docker.io (20.10.12-0ubuntu2~20.04.1) ...
Adding group `docker' (GID 119) ...
Done.
Created symlink /etc/systemd/system/multi-user.target.wants/docker.service → /li                                                                                                                     b/systemd/system/docker.service.
Created symlink /etc/systemd/system/sockets.target.wants/docker.socket → /lib/sy                                                                                                                     stemd/system/docker.socket.
Setting up dnsmasq-base (2.80-1.1ubuntu1.5) ...
Setting up ubuntu-fan (0.12.13ubuntu0.1) ...
Created symlink /etc/systemd/system/multi-user.target.wants/ubuntu-fan.service →                                                                                                                      /lib/systemd/system/ubuntu-fan.service.
Processing triggers for systemd (245.4-4ubuntu3.18) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for dbus (1.12.16-2ubuntu2.2) ...
Processing triggers for libc-bin (2.31-0ubuntu9.9) ...
root@VMID-3789:~# sudo snap install docker
docker 20.10.14 from Canonical✓ installed
root@VMID-3789:~# docker --version
Docker version 20.10.12, build 20.10.12-0ubuntu2~20.04.1
root@VMID-3789:~# sudo docker run hello-world
Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": dial                                                                                                                      tcp: lookup registry-1.docker.io: Temporary failure in name resolution.
See 'docker run --help'.
root@VMID-3789:~# sudo docker images
REPOSITORY   TAG       IMAGE ID   CREATED   SIZE
root@VMID-3789:~# sudo docker ps -a
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
root@VMID-3789:~# sudo docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
root@VMID-3789:~# sudo systemctl start docker
root@VMID-3789:~# sudo systemctl enable docker
root@VMID-3789:~# sudo sudo systemctl status docker
● docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset>
     Active: active (running) since Mon 2022-10-10 06:44:42 UTC; 1min 34s ago
TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com
   Main PID: 37091 (dockerd)
      Tasks: 9
     Memory: 31.1M
     CGroup: /system.slice/docker.service
             └─37091 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/con>

Oct 10 06:44:41 VMID-3789 dockerd[37091]: time="2022-10-10T06:44:41.103402978Z">
Oct 10 06:44:41 VMID-3789 dockerd[37091]: time="2022-10-10T06:44:41.103420727Z">
Oct 10 06:44:41 VMID-3789 dockerd[37091]: time="2022-10-10T06:44:41.103435459Z">
Oct 10 06:44:41 VMID-3789 dockerd[37091]: time="2022-10-10T06:44:41.103958822Z">
Oct 10 06:44:41 VMID-3789 dockerd[37091]: time="2022-10-10T06:44:41.551277421Z">
Oct 10 06:44:41 VMID-3789 dockerd[37091]: time="2022-10-10T06:44:41.942637585Z">
Oct 10 06:44:41 VMID-3789 dockerd[37091]: time="2022-10-10T06:44:41.966893543Z">
Oct 10 06:44:41 VMID-3789 dockerd[37091]: time="2022-10-10T06:44:41.967453845Z">
Oct 10 06:44:42 VMID-3789 systemd[1]: Started Docker Application Container Engi>
Oct 10 06:44:42 VMID-3789 dockerd[37091]: time="2022-10-10T06:44:42.016205940Z">

root@VMID-3789:~# sudo wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/o                                                                                                                     utline-server/master/src/server_manager/install_scripts/install_server.sh | bash
> Verifying that Docker is installed .......... OK
> Verifying that Docker daemon is running ..... OK
> Setting PUBLIC_HOSTNAME to external IP ...... OK
> Creating persistent state dir ............... OK
> Generating secret key ....................... OK
> Generating TLS certificate .................. OK
> Generating SHA-256 certificate fingerprint .. OK
> Writing config .............................. OK
> Starting Shadowbox .......................... FAILED
Unable to find image 'quay.io/outline/shadowbox:stable' locally
stable: Pulling from outline/shadowbox
cbdbe7a5bc2a: Pulling fs layer
8f3938f7d3bd: Pulling fs layer
6e3c12f5dc10: Pulling fs layer
ce0cb7a9eeee: Pulling fs layer
90580165d776: Pulling fs layer
1ed2bec38931: Pulling fs layer
93243a5b7df3: Pulling fs layer
7c7f63422259: Pulling fs layer
70c3ffa1c0bf: Pulling fs layer
bb6b8fb81cb5: Pulling fs layer
5a0f6aeaf89b: Pulling fs layer
53bbf77f5c86: Pulling fs layer
ce0cb7a9eeee: Waiting
70c3ffa1c0bf: Waiting
bb6b8fb81cb5: Waiting
1ed2bec38931: Waiting
93243a5b7df3: Waiting
7c7f63422259: Waiting
53bbf77f5c86: Waiting
6e3c12f5dc10: Verifying Checksum
6e3c12f5dc10: Download complete
cbdbe7a5bc2a: Verifying Checksum
cbdbe7a5bc2a: Download complete
ce0cb7a9eeee: Verifying Checksum
ce0cb7a9eeee: Download complete
cbdbe7a5bc2a: Pull complete
8f3938f7d3bd: Verifying Checksum
8f3938f7d3bd: Download complete
90580165d776: Verifying Checksum
90580165d776: Download complete
93243a5b7df3: Verifying Checksum
93243a5b7df3: Download complete
1ed2bec38931: Verifying Checksum
1ed2bec38931: Download complete
7c7f63422259: Verifying Checksum
7c7f63422259: Download complete
70c3ffa1c0bf: Verifying Checksum
70c3ffa1c0bf: Download complete
bb6b8fb81cb5: Verifying Checksum
bb6b8fb81cb5: Download complete
53bbf77f5c86: Verifying Checksum
53bbf77f5c86: Download complete
8f3938f7d3bd: Pull complete
6e3c12f5dc10: Pull complete
ce0cb7a9eeee: Pull complete
90580165d776: Pull complete
5a0f6aeaf89b: Verifying Checksum
5a0f6aeaf89b: Download complete
1ed2bec38931: Pull complete
93243a5b7df3: Pull complete
7c7f63422259: Pull complete
70c3ffa1c0bf: Pull complete
bb6b8fb81cb5: Pull complete
5a0f6aeaf89b: Pull complete
53bbf77f5c86: Pull complete
Digest: sha256:e98e7673eed63bf4871e07c934a7694e592686860119f0d871e14f8ad56f45e5
Status: Downloaded newer image for quay.io/outline/shadowbox:stable
docker: Error response from daemon: error while creating mount source path '/opt                                                                                                                     /outline/persisted-state': mkdir /opt/outline: read-only file system.

Sorry! Something went wrong. If you can't figure this out, please copy and paste                                                                                                                      all this output into the Outline Manager screen, and send it to us, to see if w                                                                                                                     e can help you.
Full log: /tmp/outline_logdWB
root@VMID-3789:~# sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"
> Verifying that Docker is installed .......... OK
> Verifying that Docker daemon is running ..... OK
> Setting PUBLIC_HOSTNAME to external IP ...... OK
> Creating persistent state dir ............... OK
> Generating secret key ....................... OK
> Generating TLS certificate .................. OK
> Generating SHA-256 certificate fingerprint .. OK
> Writing config .............................. OK
> Starting Shadowbox .......................... FAILED
docker: Error response from daemon: Conflict. The container name "/shadowbox" is already in use by container "680efebdf0ea24286df766cb6bb164e685b3a510e6b12a2633d0cdf04ca330f9". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.

Sorry! Something went wrong. If you can't figure this out, please copy and paste all this output into the Outline Manager screen, and send it to us, to see if we can help you.
Full log: /tmp/outline_logHO1
root@VMID-3789:~#
`

**Comment by rohanmehra20** [comment]
Thank you for reaching out! If this is still an issue for you, please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.
