### ISSUE TITLE
Outline VPN doesn't work on Windows 10. 

### ISSUE THREAD

**Issue by twilight-slider** [Jigsaw-Code/outline-client#1433]
**Describe the bug**
I am unable to connect to my VPN server. It just says connecting and disconnects

**To Reproduce**

1. Go to 'outline VPN client'
2. Click on 'connect'
3. See error

**Expected behavior**
It should connect to VPN

**Screenshots**
![изображение](https://user-images.githubusercontent.com/62907995/195341412-640a79a7-585b-44d0-8e9a-366a6e4fac7c.png)

**Client System (please complete the following information):**
 - Outline Client Version 1.7.1
 - Your Operating System: Windows 10 Pro

**Additional context**
Tried and didn't help:
- turn off firewall (windows firewall)
- turn off antivirus (defender)
- reinstall client
- reinstall server

**Additional**
Another windows-computer or another-os-devices works with my Outline server correctly.
Looks like a problem with system.

**Comment by twilight-slider** [comment]
**Resolved:**

1. **Delete adapter**: Control Panel\Network and Internet\Network Connections\outline-tap0 , will appear error about "...not properly installed... " or smth like.
2. **Install Outline-client via Administrator** (over existing)
3. **Reboot**

**Comment by shahryarjb** [comment]
@twilight-slider unfortunately it did not work for me, I deleted the adaptor and deleted the app from control panel and re-installed as administrator. But after connecting, it just returned to timeout.

**Comment by twilight-slider** [comment]
@shahryarjb 
did it work anytime?
try turn off the firewall

**Comment by shahryarjb** [comment]
@twilight-slider I did these 
1. delete adaptor.
2. re-install as administrator.
3. offline all the firewall.
4. edit DNS
5. Enable and disable ipv6.
Even re-install network driver! I can be able to use another software and event I can connect to the server with outline, but after connecting I get timeout.

**Comment by AungWinnHtut** [comment]
i have same issue right now
