### ISSUE TITLE
Can't connect with win10...

### ISSUE THREAD

**Issue by Namvarii** [Jigsaw-Code/outline-client#1443]
**Describe the bug**
I wonder i can't connect to any server with Windows 10 x64, but it's ok with Android phone.
Two of them are in same network. even i change network nothing happen with pc, i can't connect anyway...

**Screenshots**
Sorry, an unexpected error occurred. Quitting and restarting may help. If this happens again, please submit feedback.
![image](https://user-images.githubusercontent.com/50305913/196773481-28d99fde-f05f-4b40-a6b5-650f5e046f0c.png)

**Client System (please complete the following information):**
 -  Version 1.8.0
 -  Win 10 x64

**Comment by KilledDebtor** [comment]
1.6.0 working well,try it.

**Comment by Namvarii** [comment]
> 1.6.0 working well,try it.

Yes, thanks,
https://github.com/Jigsaw-Code/outline-client/releases/tag/windows-v1.6.0

This version works for me.
