### ISSUE TITLE
Problem installing Outline.

### ISSUE THREAD

**Issue by Tosh0kan** [Jigsaw-Code/outline-client#1451]
**Describe the bug**
Installation fails, with the message "let us know that OutlineService failed to install". The odd thing is, the program appears to be installed, because I can open it after exiting the error window, but it can't connect to any server.

**To Reproduce**
Uninstall Outline then try to reinstall it. 

**Expected behavior**
Working installation

**Screenshots**
https://i.imgur.com/ZTGKPcG.png

**Client System (please complete the following information):**
 - 1.7.1
 - Windows 10

**Comment by Tosh0kan** [comment]
![](https://i.imgur.com/Vm08dRs.png)
![](https://i.imgur.com/w6cjxrS.png)

The only component that seems to have failed in installing was the service, as it wasn't present in the list.

**Comment by jyyi1** [comment]
Thanks @Tosh0kan. Did the service files successfully copied to the destination? (the default locations are:)

* `C:\Program Files (x86)\Outline\OutlineService.exe`
* `C:\Program Files (x86)\Outline\install_windows_service.bat`

The second file (`install_windows_service.bat`) is our installation script to register `OutlineService.exe` to Windows as a service. We had some reports saying that it might be blocked by some anti-virus software. But to double confirm, could you please run it manually and to see whether there are any errors.

**Comment by Tosh0kan** [comment]
Both files were in the aforementioned folder. When I ran the batch file, the service wouldn't start, but after trying it again, but this time using the "run as administrator" option, it worked and now `OutlineService`shows up in the services list and now I can connect to servers just fine. Thank you!

**Comment by jyyi1** [comment]
Thanks @Tosh0kan for the confirmation. I will resolve this issue now.

**Comment by teacherlove** [comment]
Happened to me and could not connect to server due to admin permission
After running the bat file, t started to working.

Running on windows
