### ISSUE TITLE
Outline Client has stopped working after updating Windows 11, 21H2 to Windows 11, 22H2

### ISSUE THREAD

**Issue by mamaly12** [Jigsaw-Code/outline-client#1452]
Hi,

After updating my windows 11, version 21H2 to windows 11, version 22H2, I faced this error:

"Sorry, an unexpected error occurred. Quitting and restarting may help. If this happens again, please submit feedback."

I tried to uninstall outline and even delete its adapter and reinstall it again, but I still got this error.
 
Could anyone please help me to solve that issue?

**Comment by mamaly12** [comment]
Thanks, @jyyi1,

There's no error in the event log:
![image](https://user-images.githubusercontent.com/7683251/197600354-3fd48087-1d6a-4f1f-baec-b5a81c062281.png)

and the service is running :
![image](https://user-images.githubusercontent.com/7683251/197600508-29931a4b-d574-474c-84ac-16dddf115d7d.png)

But as you can see I still get the same error:
Sorry, an unexpected error occurred. Quitting and restarting may help. If this happens again, please submit feedback.

An interesting thing is I don't have this problem with the Outline android version on my phone.

**Comment by jyyi1** [comment]
Thanks @mamaly12 for the information, then I think we need to get the logs from the client. If you are using PowerShell (which should be the default Terminal in Windows 11), please restart Outline client using the following PowerShell commands (typically the outline installation path is `C:\Program Files (x86)\Outline`):

```powershell
PS C:\....> cd "<your outline installation path>"
PS C:\....\Outline> $Env:OUTLINE_DEBUG="true"
PS C:\....\Outline> .\Outline.exe
```

Then try to connect to the server again, there should be some errors printed to PowerShell. If you want, you can also get some UI logs by clicking menu item "Developer" -> "Toggle Developer Tools".

**Comment by mamaly12** [comment]
@jyyi1 I got this error :

![image](https://user-images.githubusercontent.com/7683251/197605440-714c77fa-0bfd-4391-8808-654e4b1952a2.png)

**Comment by jyyi1** [comment]
@mamaly12 This is expected, please try to connect to the server.

**Comment by mamaly12** [comment]
exactly, I created the connection_store folder manually and I tried to connect to the server:

![image](https://user-images.githubusercontent.com/7683251/197606264-d37be0e4-11b3-42ce-82b9-a0e43f64e25c.png)

@jyyi1

**Comment by jyyi1** [comment]
Thanks @mamaly12 , ah i see. This should be the same issue as #1449 , which occurs in a new component we introduced in this release. We will try to fix it ASAP, but for now I think the workaround would be using an old version (1.7.0 should be good). Again, sorry about the inconvenience.
