### ISSUE TITLE
Build on MacOS failed on master branch

### ISSUE THREAD

**Issue by hamed-nasrollahi** [Jigsaw-Code/outline-client#1472]
building in macOS from the master branch fails with the error below: 

> warning: Run script build phase 'Copy www directory' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Outline' from project 'Outline')
>   warning: Run script build phase 'Remove unused framework architectures' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Outline' from project 'Outline')
>   ** BUILD FAILED **
>   The following build commands failed:
>    SwiftEmitModule normal x86_64 Emitting\ module\ for\ VpnExtension (in target 'VpnExtension' from project 'Outline')
>   (1 failure)
>   node:internal/process/esm_loader:94
>       internalBinding('errors').triggerUncaughtException(
>                                 ^
>   Error: xcodebuild: Command failed with exit code 65
>       at ChildProcess.whenDone (/Users/administrator/Documents/outline-client/node_modules/cordova-common/src/superspawn.js:136:25)
>       at ChildProcess.emit (node:events:390:28)
>       at maybeClose (node:internal/child_process:1064:16)
>       at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
>     code: 65
>   }
>   Thrown at:
>       at whenDone (/Users/administrator/Documents/outline-client/node_modules/cordova-common/src/superspawn.js:136:25)
>       at emit (node:events:390:28)
>       at maybeClose (node:internal/child_process:1064:16)
>       at ChildProcess._handle.onexit (node:internal/child_process:301:5)
> ▶ action(cordova/build): ❌ Failed.

**Environment**
 - OS: [macOS 13.1
 - NPM version (`npm --version`) 8.1.0
 - Node.js version 16.13.0

**Comment by fortuna** [comment]
That's odd, the CI was working, I believe.
In any case, it seems to be working now, and it will be more reliable after https://github.com/Jigsaw-Code/outline-client/pull/1527
