### ISSUE TITLE
no way to create an access key

### ISSUE THREAD

**Issue by wopeizl** [Jigsaw-Code/outline-client#1474]
**Describe the bug**
How to create an access key??? The link on the main page just out of work, more importantly there is no clear way to tell how to make it maually, .......

Some page said that ss://base64(ciphermethod:password)@ip:port ... ennnn, not working !!!

**Comment by Amirali-Amirifar** [comment]
By checking the source code, you can see that 
```
import {makeConfig, SIP002_URI} from 'outline-shadowsocksconfig';
let accessUrl = SIP002_URI.stringify(
      makeConfig({
        host: hostname,
        port: portNumber,
        method: encryptionMethod,
        password: password,
        outline: 1,})
);
```
you can learn more about `SIP002_URI()` and `makeConfig()` in https://github.com/Jigsaw-Code/outline-shadowsocksconfig/blob/master/src/shadowsocks_config.ts

**Comment by jyyi1** [comment]
Hi @wopeizl , please download the [Outline Manager app](https://getoutline.org/get-started/#step-1), and create a key within it ([this document might help](https://support.getoutline.org/s/article/manage-access-to-server?language=en_US#:~:text=Create%20keys%3A%20Click%20the%20small,messaging%20system%20of%20your%20choice.)].
