### ISSUE TITLE
Outline Client app adds itself to Windows 10 Autorun every time it connects to a server

### ISSUE THREAD

**Issue by macsunmood** [Jigsaw-Code/outline-client#1478]
**Describe the bug**
Outline Client app adds itself to Windows Autorun every time it connects to a server. This is displayed by an app called Autorun Organizer, which sends a notification every time the connection is established.
Outline adds the same `C:\Program Files (x86)\Outline\Outline.exe --autostart` string to windows registry each time.

**To Reproduce**
Connect to a server (push the button and wait for successful connection).

**Client System (please complete the following information):**
 - Outline Client Version: 1.8.1
 - Operating System: Windows 10 21H2

**Comment by maddyhof** [comment]
Tagging as a feature request to provide an option to disable auto-run on the Windows Client.

**Comment by maddyhof** [comment]
Since we already have this logged as a feature request (https://github.com/Jigsaw-Code/outline-client/issues/1478) I will close this issue.
