### ISSUE TITLE
DNS Error when connected to server on Windows ver. 1.8.1

### ISSUE THREAD

**Issue by r1chbrown** [Jigsaw-Code/outline-client#1481]
**Describe the bug**
When I connect to my Outline server on Windows at version 1.8.1, the status in the Outline app is 'Connected', but when I go to any website in the browser – I got DNS Error. 

But if I disconnect from the Outline server and connect again – everything will be OK.
I tried to reproduce this bug on my Windows 10 laptop and on Windows Server 2019 at Amazon several times, and each time this bug appears.

If I downgrade to 1.8.0 – all works fine.

**To Reproduce**
How can the broken behavior be reproduced? 
Install Outline 1.8.1 to Windows, add server, connect to it, see status "Connected", go to browser and visit any URL, receive DNS error. IP urls (like http://1.1.1.1) works good.

**Screenshots**
Here are 2 screenshots - before connecting and after.

<img width="1728" src="https://user-images.githubusercontent.com/63267104/202875917-97b39167-12e3-4f44-aed8-058d178956d3.png">
<img width="1728" src="https://user-images.githubusercontent.com/63267104/202875922-39a3796e-9f68-43c3-9650-2e1a8701af70.png">

**Client System (please complete the following information):**
 - Outline Client Version Windows ver. 1.8.1
 - Your Operating System: Windows 10 ver. 22H2, Windows Server 2019 Datacenter ver. 1809

**Comment by vyacheslavslava** [comment]
The same problem 1.8.1 on Windows Server 2019.
Outline 1.8.0 works perfectly fine.

 
<img width="696" alt="image" src="https://user-images.githubusercontent.com/32650052/202819437-c0f1899f-6f20-4cc7-ba5e-8b91cb3a5efa.png">

**Comment by maddyhof** [comment]
Can you please re-test this on Windows Client version 1.9.1 and see if it is still occurring? Thanks for your assistance.

**Comment by vyacheslavslava** [comment]
1.10.1 the same problem
![telegram-cloud-photo-size-2-5238032017466182008-y](https://user-images.githubusercontent.com/32650052/226148306-56b61b51-5f7d-4fa9-a0de-9b49034dbff1.jpg)

**Comment by maddyhof** [comment]
Thank you for re-testing, and I'm sorry you're having this issue! Please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.
