### ISSUE TITLE
iOS/master: Can not establish connection to the server

### ISSUE THREAD

**Issue by bi-kh** [Jigsaw-Code/outline-client#1489]
**Describe the bug**
Can not establish connection to the server. 
Error message: "Sorry, an unexpected error occurred."

**To Reproduce**
Try connecting to any server.

**Expected behavior**
Successful connection.

**Screenshots**
n/a

**Client System (please complete the following information):**
 - Outline Client Version: built from the master branch
 - Operating System: iOS 15.5

**Submit Feedback**
n/a

**Additional context**
n/a

**Comment by idev-software-group** [comment]
It is going to be happen when we want to switch between some other Key Servers .
