### ISSUE TITLE
Supporting older android devices

### ISSUE THREAD

**Issue by balkan** [Jigsaw-Code/outline-client#149]
Android SDK 23 seems to be minimum requirement for outline client, any reason for this?

is it possible to older android devices like api version 16, is it a problem with the libraries being used or any other reason?

**Comment by alalamav** [comment]
Hi @balkan, technically 21 is the minimum supported SDK. Unfortunately, older versions do not support the required VPN APIs, in particular [allowBypass](https://developer.android.com/reference/android/net/VpnService.Builder.html#allowBypass()). We use SDK 23, as it is the latest Lollipop SDK.
