### ISSUE TITLE
Beginer Question about electron/build

### ISSUE THREAD

**Issue by elisebai** [Jigsaw-Code/outline-client#150]
So the problem is pretty simple. I ran ' yarn do electron/build' and it shows all done with not error. I was expecting the program to be compiled with an exe file but didn't find any.

Sorry for this dumb question, but it seems I still need to do something, can I get some instructions?

Thanks, lots of love!

**Comment by alalamav** [comment]
Hi @elisebai, please run `yarn do electron/run` to run the Windows client. `yarn do electron/build` only builds the app without running or packaging it.
Let me know if that helps; otherwise feel free to re-open this issue.
