### ISSUE TITLE
Version 1.9.0 does not work on Windows.

### ISSUE THREAD

**Issue by silmooninc** [Jigsaw-Code/outline-client#1535]
The Outline Windows client software is automatically updated to version 1.9.0, but after this version update, trying to connect will find that it has been connected, but it is not actually connected, the corresponding network adapter is also in the unconnected state, only the client status is displayed as connected, which should be a bug.

Microsoft Windows 11

**Comment by babribeiro** [comment]
Same here. It seems the TAP adapter no longer works/connects
Windows 10

**Comment by 777Infiniti** [comment]
Same for me 
after updating for Version 1.9.0  app stopped work  on Windows 10

**Comment by EngineExt** [comment]
Same for me.
Windows 10 22H2 and Outline Version 1.9.0

**Comment by Akvilan** [comment]
The same. 
Ive tried next: 
Reboot PC
Delete outline
delete TAP 
Drop to the base settings Network and brandmower
reboot 
reinstall from scratch. 

the decision that helped me was download previous release

**Comment by sazonovanton** [comment]
Same, downgrading is only solution (deleted 1.9.0 and installed 1.7.1), but Outline constantly tries to upgrade itself. 
Windows 11 (22H2)

**Comment by kurgera** [comment]
Same, Windows 11 (22H2)

**Comment by heXile** [comment]
+ Windows 10 (22H2)

**Comment by themahdavi** [comment]
Same, Windows 11 (22H2)

**Comment by goodrobin** [comment]
Same, Windows 11 (22H2)

**Comment by Zazzix** [comment]
1.8.1 works fine, the latest - no

**Comment by themahdavi** [comment]
Version 1.9 not listed in releases  and not work !

**Comment by Akvilan** [comment]
Does someone knows how to reject automatic update?

**Comment by themahdavi** [comment]
> Does someone knows how to reject automatic update?

when close outline show YES/No page to install application select NO to reject update!

**Comment by EngineExt** [comment]
> Does someone knows how to reject automatic update?

Win+R → %USERPROFILE%\AppData\Local\outline-client-updater\
Delete folder pending.
Create txt file with name pending and delete her extension (or download it from the [link](https://bit.ly/3VVDgRz) add it to the folder outline-client-updater)

**Comment by sazonovanton** [comment]
> The same for me Windows 10 build 19044.2364
> 
> And I found some interesting behavior:
> 
> 1. Connect to any Outline server
> 2. Open any browser
> 3. Go to any website (let's say google.com)
> 4. You'll get the error (DNS problem or something)
> 5. Disconnect from the Outline server
> 6. Refresh the page with google.com
> 7. Connect to the Outline server
> 8. Refresh the page with google.com
> 9. It's work! Now you can search throw the google. But you won't open any websites from the search results because of the same error from the 4 point
> 
> It seems like outline somehow remembers DNS names and allows you to use these settings on a future session

For me it shows as connected and internet works, but my IP does not change

**Comment by Squawk-7700** [comment]
Same, Win10 22H2

**Comment by tinycrate** [comment]
Same, Win11 22H2

**Comment by larryro** [comment]
Same, Win11 22H2

**Comment by myozawlatt** [comment]
Same, Windows 11 (22H2)

**Comment by abivos** [comment]
That's smells fishy, are we sure that update servers wasn't compromised? Doesn't see any info from developers, no version in releases page, strange UAC request after update...

**Comment by cloud-66** [comment]
I agree. it looks strange, but there is pull request about 1.9 version #1495

**Comment by themahdavi** [comment]
merge Nov 29, 2022  but why 2023 receive update !!!! is strange ...

**Comment by SadeghSalman** [comment]
Any update ? 1.9 is still not working on windows platform

**Comment by fortuna** [comment]
Thanks for the feedback. We will revert the release soon.

**Comment by jyyi1** [comment]
**Status Update**

We have fixed the issue and released a new version `v1.9.1` for Windows. You can either download the new version from the website, or simply launch Outline Client app to get the update.

Again, sorry about the inconvenience.

**Comment by jyyi1** [comment]
> That's smells fishy, are we sure that update servers wasn't compromised? Doesn't see any info from developers, no version in releases page, strange UAC request after update...

Sorry about the confusion. The [GitHub releases in this repository](https://github.com/Jigsaw-Code/outline-client/releases) is not the source of truth (though sometimes we will update it). We will only publish the app update to our internal storage (in AWS S3), and Outline Client will fetch that location to get the update automatically. We have another repository outline-releases which contains [the S3 location just mentioned](https://github.com/Jigsaw-Code/outline-releases/blob/master/client/latest.yml), but it is for legacy apps as well.

**Comment by SadeghSalman** [comment]
I updated from 1.8.1 to 1.9.1 and it works fine. Thanks Team

**Comment by alexmeku1rubedogames** [comment]
1.9.1 still not work

**Comment by fortuna** [comment]
Fixed at 1.9.1: https://github.com/Jigsaw-Code/outline-releases/pull/193
