### ISSUE TITLE
ALL Outline users use the same encryption password?

### ISSUE THREAD

**Issue by anon-wang** [Jigsaw-Code/outline-client#154]
Just came upon this code block and it really worries me. Could someone explain a little bit and ease my mind? 

[link to the code below](https://github.com/Jigsaw-Code/outline-client/blob/6a1e879fc4fcd066a4ee59e22549f2926ccb0009/third_party/shadowsocks-libev/docker/alpine/docker-compose.yml)
```
shadowsocks:
  image: shadowsocks-libev
  ports:
    - "8388:8388/tcp"
    - "8388:8388/udp"
  environment:
    - METHOD=aes-256-cfb
    - PASSWORD=9MLSpPmNt
  restart: always

**Comment by alalamav** [comment]
Hi @anon-wang, short answer: no. The repository that hosts the code to create and manage Outline servers is https://github.com/Jigsaw-Code/outline-server/. You will see that every access key to a sever uses a unique password. 
The code that you linked is an example configuration in shadowsocks-libev for [using docker compose to manage a server](https://github.com/Jigsaw-Code/outline-client/tree/6a1e879fc4fcd066a4ee59e22549f2926ccb0009/third_party/shadowsocks-libev/docker/alpine#use-docker-compose-to-manage-optional).
