### ISSUE TITLE
Broken GUI on M2

### ISSUE THREAD

**Issue by ain** [Jigsaw-Code/outline-client#1544]
**Describe the issue**

## Steps to reproduce

1. Build the project on macOS, e.g. `npm run action cordova/build macos`
2. Run `Outline.app` from `/Users/.../Library/Developer/Xcode/DerivedData/macos-hhpoqalgexeuxvgcafckgwaoshcp/Build/Products/Debug/`

## What happens?

GUI broken, no action possible:

<img width="441" alt="Screenshot 2023-01-09 at 13 10 13" src="https://user-images.githubusercontent.com/370576/211305868-4bc864a3-2aab-48fe-939d-a72550dc1dbb.png">

## What should happen?

App should run with functional GUI.

**Environment**
 - OS: `Apple M2, macOS 13.0.1`
 - NPM version (`npm --version`): `8.19.2`
 - Node.js version: `v16.18.1`

**Additional context**
Built from the latest `master`, e1ff07c5419d29b4e3253f49e7fc4d4489c26cd4

**Comment by levanid** [comment]
I have also broken notification on M1 Pro. When outline starts it shows some kind of notification balloon which is wrongly positioned out of the screen border 
Here's the screenshot 
<img width="97" alt="image" src="https://user-images.githubusercontent.com/21140063/211536427-9dc966ba-1bc1-4e74-845b-d3182806f4a6.png">

**Comment by fortuna** [comment]
It turns out the app is broken on debug builds only. The web code is triggering some invalid assert that busts the whole thing.

It's fine with release builds, which you can do with:
```
SENTRY_DSN=https://f@o00000.ingest.sentry.io/000000 npm run action cordova/setup macos -- --buildMode=release --versionName=0.0.0-dev && > open ./src/cordova/apple/macos.xcworkspace
```

> **Note**
> You should use your own `SENTRY_DSN` for your release
