### ISSUE TITLE
how do I join the team "Jigsaw Operation LLC"? 

### ISSUE THREAD

**Issue by woodymoo** [Jigsaw-Code/outline-client#156]
I have developer account, but I don't know how to do the following?
does some give me a picture demo?

Click "Outline" in the left navigation bar:
Under "Signing" select "Jigsaw Operations LLC"

**Comment by alalamav** [comment]
Hi @woodymoo, I recommend you create an App ID (with the appropriate entitlements) for the project on your Apple developer account and modify the Outline and VpnExtension targets in the generated Xcode project to match the ID. You will have to register the device(s) you want to use for development. You may also need to change the code signing options to match your development team.

Let me know if that works, and feel free to re-open this issue with further questions.
