### ISSUE TITLE
Does outline support simple-obfs?

### ISSUE THREAD

**Issue by samurai00** [Jigsaw-Code/outline-client#159]
Does outline.app for macOS support simple-obfs which is a SIP003 plugin?

**Comment by studentmain** [comment]
no

afon <notifications@github.com> 于 2018年7月8日周日 22:31写道：

**Comment by samurai00** [comment]
Do you have any plan to support?

**Comment by studentmain** [comment]
Ask developer.
But personnally I'd prefer use v2ray.

afon <notifications@github.com> 于 2018年7月8日周日 23:29写道：

**Comment by alalamav** [comment]
Hi @samurai00, as @studentmain said, Outline does not support simple-obfs/SIP003. There are no immediate plans to support it, but we'll take your feedback into consideration in the future.
