### ISSUE TITLE
Issue with Outline Client that prioritizes cached Dynamic Key over the online version to get the latest changes

### ISSUE THREAD

**Issue by maximumpxy** [Jigsaw-Code/outline-client#1591]
**Describe the bug**

When we update the IP address or other access key details inside the a hosted Dynamic Key, the Outline Client will prioritize using the cached key instead of checking the JSON file, and as a result throws an error. 

With this bug, the full functionality of the Dynamic Keys are discarded, and they turn into a semi-Dynamic Keys since it still needs the user to modify the URL and add the modified key again, explained below.

**To Reproduce**

You can simply host a JSON file as described in: [https://www.reddit.com/r/outlinevpn/wiki/index/dynamic_access_keys/](Outline Dynamic Keys - Reddit.com)

```
{
	"server": "<IP Address>",
	"server_port": <Port Number>,
	"password": "<Decoded Base-64 Password>",
	"method": "chacha20-ietf-poly1305"
}
```

Then, connect using the Outline Client. 

Once connected, for instance:
- Revoke the previous session from Outline Manager and add a new one, and reflect the decoded base-64 password to the hosted JSON file; and/or,
- Change the IP address of this file; and/or,
- Modify any other details

Finally, attempt to reconnect from Outline Client, and you would notice the Invalid Key error.

**This can be temporarily fixed by adding a `?` at the end of the Dynamic Key. Outline would then attempt to take the key from the URL.** If there are any other changes inside the Dynamic Key, you would need to add/remove question marks in order for the Outline Client to ignore the cached access key.

**Expected behavior**
It is expected that Outline Client differentiate between a Static and Dynamic key, and if it sees `ssconf://` at the beginning of a key, it prioritizes the online version to the cached one. If the Dynamic Key is not accessible after few retries, it then attempt to use the cached version. **This way, the Dynamic Key would be fully autonomous and bound to the latest version of the hosted JSON file.**

**Screenshots**
N/A

**Client System (please complete the following information):**
 - Outline Client Version: The latest Outline Clients
 - Your Operating System: All Platforms

**Submit Feedback**
Done

**Additional context**
None

**Comment by fortuna** [comment]
@maximumpxy can you share the relevant headers from your webserver response? Your caching parameters may be misconfigured. Perhaps you set the `max-age` too high?

We use the browser `fetch` function, which by default will fetch the new resource if the cached one is stale, as described in https://developer.mozilla.org/en-US/docs/Web/API/Request/cache

More on HTTP Caching at https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching

**Comment by maximumpxy** [comment]
> @maximumpxy can you share the relevant headers from your webserver response? Your caching parameters may be misconfigured. Perhaps you set the `max-age` too high?
> 
> We use the browser `fetch` function, which by default will fetch the new resource if the cached one is stale, as described in https://developer.mozilla.org/en-US/docs/Web/API/Request/cache
> 
> More on HTTP Caching at https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching

Thanks for your reply. 
Here is the storage server's response, where the .JSON file containing the Dynamic Key is hosted:

```
Server: <...>
Date: Tue, 14 Mar 2023 16:38:00 GMT
Content-Type: binary/octet-stream
Connection: keep-alive
Keep-Alive: timeout=65
last-modified: Thu, 09 Mar 2023 14:06:26 GMT
x-rgw-object-type: Normal
etag: "<...>"
x-amz-request-id: <...>
access-control-allow-origin: *
access-control-allow-credentials: true
access-control-allow-headers: Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range
access-control-allow-methods: GET,POST,OPTIONS,PUT,DELETE,PATCH
X-XSS-Protection: 1; mode=block
AR-SID: 4101
AR-ATIME: 0.242
AR-CACHE: BYPASS
AR-Request-ID: <...>
Accept-Ranges: bytes
Content-Length: 125
```

And, in the Storage Panel, caching is set to `OFF ` for that specific domain.

As initially reported, the main issue is that the Outline Client only fetches **a single key once**, regardless of its type, which can be either Dynamic or Static. 

To reproduce this, you can simply add a Dynamic Key and host it on your webserver/storage server, and then, you would notice only upon adding the key inside the Outline Client, it attempts to `GET` the dynamic key once. In the next attempts, it will only use the cached version without any `GET` calls. So, it clearly won't check if **the cached one is stale**. 

As highlighted previously, what we expect is that Outline Client does the followings, all of which should be integrated in the Outline Client and not the Outline Server:

1- To differentiate between Dynamic and Static Keys; and,
2- If it deals with a Dynamic Key, always attempt to fetch a new key from the webserver/storage server where the JSON file is hosted; and,
3- If it deals with a Dynamic Key, save the cached key for the Dynamic Keys, and only use it if the webserver is not responding

**Comment by ch3rrydrunk** [comment]
The issue remains on an iOS client

**Comment by bestmgmt** [comment]
> Version 1.11 with the fix has been released!

Thank you for the update, @fortuna .

I've seen the update on Apple's App Store few days ago. 

Could you please let me know when the Outline 1.11 update is expected to be added to the release section of the GitHub repository?

That information would be very helpful.

**Comment by fortuna** [comment]
@bestmgmt we announce releases on https://www.reddit.com/r/outlinevpn/

You can see the [iOS](https://apps.apple.com/us/app/outline-app/id1356178125) and [macOS](https://apps.apple.com/us/app/outline-app/id1356178125) version history on the App Store

For [Android](https://play.google.com/store/apps/details?id=org.outline.android.client&pli=1), the Play Store shows the latest version

Unfortunately we don't currently have a way to show all the history on Windows and Linux, but that's something we can consider adding. Thanks for the feedback.

**Comment by manhte2** [comment]
I hosted dynamickeyfile.json on my self host which enabled CORS for nginx but client till could not load VPN configuration !
Any one know how to fix it ?
appreciate

**Comment by Qvvan** [comment]
@manhte2 Did you fix it?

**Comment by manhte2** [comment]
> @manhte2 Did you fix it?

not bro, I give up and hosted .json file in S3
