### ISSUE TITLE
[Potential Obstacle]How do you deal with GPL?

### ISSUE THREAD

**Issue by lexrus** [Jigsaw-Code/outline-client#16]
AFAIK, libs licensed under GPL are not suitable to App Store.

**Comment by bemasc** [comment]
The Outline Client's license is Apache 2: https://github.com/Jigsaw-Code/outline-client/blob/master/LICENSE

Is there a specific library you are concerned about?

**Comment by lexrus** [comment]
https://github.com/Jigsaw-Code/outline-client/blob/master/third_party/libev/LICENSE
https://github.com/Jigsaw-Code/outline-client/blob/master/third_party/shadowsocks-libev/LICENSE
https://github.com/Jigsaw-Code/outline-client/blob/master/third_party/Potatso/LICENSE

**Comment by sandrigo** [comment]
Thank you for your comment. Our understanding is that Apple's developer terms don't prohibit the inclusion of free and open source software in iOS apps.
