### ISSUE TITLE
Failed to handle connection: System.IO.IOException: Pipe is broken.

### ISSUE THREAD

**Issue by myozawlatt** [Jigsaw-Code/outline-client#1612]
**Describe the bug**
Outline Client for Windows is failed to connect any server for 3 days.
Event log says "Failed to handle connection: System.IO.IOException: Pipe is broken.".

**Screenshots**
<img width="267" alt="image" src="https://user-images.githubusercontent.com/20241314/229675458-6df2f813-8af3-4c9c-8503-9bbc6deaaf5e.png">

<img width="558" alt="image" src="https://user-images.githubusercontent.com/20241314/229675171-8773753b-729d-4afa-b144-d4b0dee339b3.png">

**Client System (please complete the following information):**
 - Outline Client Version [Windows 1.10.1 ]
 - Your Operating System: [Windows 11]

**Comment by maddyhof** [comment]
Please see troubleshooting instructions [here](https://github.com/Jigsaw-Code/outline-client/issues/1452#issuecomment-1289401954), and reach out to [customer support](https://support.getoutline.org/s/contactsupport) if you have further issues.
