### ISSUE TITLE
Installer cannot install TAP Adapter (error code 1) - Outline 1.10.1 - Windows 11 (ARM)

### ISSUE THREAD

**Issue by xngoli** [Jigsaw-Code/outline-client#1621]
When installing Outline 1.10.1 on my Surface (Pro 9 5G, Windows 11 on ARM, 22H2, latest updates), the installer fails to install the adapter with an error code 1.
![image](https://user-images.githubusercontent.com/17217834/235215166-0106f585-c1ae-452b-9b20-b5a3801b2aba.png)
Rerunning the installer multiple times doesn't help. Removing and reinstalling doesn't help either.
Get-NetAdapter in Powershell (run as an administrator) doesn't show any adapters other than the ones for hardware. 
![image](https://user-images.githubusercontent.com/17217834/235216060-f230b4a2-ac70-4937-9116-5fe4a9f05463.png)

**Comment by maddyhof** [comment]
Thanks for reaching out. Please try the suggestions in #1103 and #1222 and let us know if that addresses the issue.
