### ISSUE TITLE
Ошибка при запуске Shadowsocks-4.4.1.0

### ISSUE THREAD

**Issue by AleksTKD** [Jigsaw-Code/outline-client#1636]
Ранее использовал и все было хорошо. Затем переустановил систему и программа перестала запускаться. 
Особых навыков программирования нет, поэтому если кто то знает как решить данную проблему буду очень благодарен!
Базовая система Виндовс 11 про, ранее на  ней все так же работало, после переустановки появилась такая ошибка.

![111](https://github.com/Jigsaw-Code/outline-client/assets/133577277/0eff59d1-b799-40a9-9036-d2ab5f97aa22)

**Comment by maddyhof** [comment]
Hi @AleksTKD. Are you using Outline at all in this process? From what we can see you're setting up a Shadowsocks server and using the Shadowsocks client, so that doesn't seem to involve Outline. Thanks!

**Comment by AleksTKD** [comment]
Спасибо, получилось разобраться самому.

**Comment by slesh57** [comment]
> Спасибо, получилось разобраться самому.

расскажи как разобрался?

**Comment by kukech-web** [comment]
плюсую, расскажи как исправить
