### ISSUE TITLE
how to change server without create new key

### ISSUE THREAD

**Issue by hamedefatian** [Jigsaw-Code/outline-client#1639]
hi 
i create a server and create  key with some day limite 
i want to know if my server was filtered from my isp how can i change my server without create key and send to my friends.
for example in v2ray when we sent x-ui.db to other server and change only cdn.

how can i do this ...

**Comment by maddyhof** [comment]
We recommend using dynamic keys for this purpose, since you can update which server the key points to without having to reissue the keys. You can find more information about how to set this up [here](https://www.reddit.com/r/outlinevpn/wiki/index/dynamic_access_keys/).
