### ISSUE TITLE
youtube comment error "failed to post comment"

### ISSUE THREAD

**Issue by balayanv** [Jigsaw-Code/outline-client#1652]
When connected to self hosted outline vpn i will always get an error when trying to comment on youtube.
No other functionality is broken, you watch videos just fine, do anything else but this one thing.
This was present in older mac versions as well as new. I do not think its OS related.

**Comment by balayanv** [comment]
i have attempted to fix this in the source code but with no success, hope someone else can help me.
My outline server is hosted on digital ocean, frankfurt region (but other regions suffer the same issue).
I doubt its the cloud hosting that causes this but do try on your setups...

**Comment by maddyhof** [comment]
Thanks for reaching out. Sometimes traffic from cloud providers like Digital Ocean can be blocked by certain apps or sites that are trying to prevent bots. This is not a bug with Outline itself, though we're sorry for the inconvenience caused.

**Comment by do02fw** [comment]
> When connected to self hosted outline vpn i will always get an error when trying to comment on youtube. No other functionality is broken, you watch videos just fine, do anything else but this one thing. This was present in older mac versions as well as new. I do not think its OS related.
You can try using a third-party client to see if it's a client problem.

**Comment by balayanv** [comment]
thanks, i'm not sure why that didnt cross my mind, i'll self host it on my own server
