### ISSUE TITLE
YouTube speed is slow, but speedtest is fast

### ISSUE THREAD

**Issue by do02fw** [Jigsaw-Code/outline-client#1657]
**Describe the bug**
When I watch YouTube it's slow, but speedtest is fast, and when I download files it's fast, if I change the outline client to v2rayNG client and use outline's server, watching YouTube becomes fast, I think there's something wrong with outline's client.

**To Reproduce**
How can the broken behavior be reproduced? 
Use outline client on Android and connect to the server, open speedtest to test the speed, remember the result of the test, open YouTube to watch 4k video and check the network speed, you will find that the speed of watching the video is very slow, when you download v2rayNG client and connect to outline server to watch YouTube 4k video, you will find the speed is very fast.
**Expected behavior**
What behavior did you expect?
Fix the problem of slow speed of watching video.
**Screenshots**
![Screenshot_20230705_123250](https://github.com/Jigsaw-Code/outline-client/assets/138294823/e130d4cc-5c33-46e2-b475-0e5f1fb827da)
![Screenshot_20230705_123430](https://github.com/Jigsaw-Code/outline-client/assets/138294823/c7d1b1f9-513e-4d6d-9360-1b5440437252)
![Screenshot_20230705_123455_Outline](https://github.com/Jigsaw-Code/outline-client/assets/138294823/9732ad66-501c-4feb-b76f-83a43919c6db)
![Screenshot_20230705_123513](https://github.com/Jigsaw-Code/outline-client/assets/138294823/97216aa1-c13e-49aa-adc6-5fc7cf07e396)

**Client System (please complete the following information):**
 - Outline Client Version [e.g. iOS 1.3.1]
 - Your Operating System: [e.g. iOS 14.2, Windows 10]
 - Android 13，Samsung Galaxy s23，edge canary browser

**Submit Feedback**
Please submit feedback through the app and label it with this issue number.

**Additional context**

**Comment by do02fw** [comment]
I'm using the 1.11.0 client, my cloud provider is VMISS.COM, and I don't have this problem with openvpn and wireguard, but outline has this problem, including when I use v2ray.

**Comment by do02fw** [comment]
> Thanks for that information. Does this happen for any other video streaming sites, or only YouTube?

I have tested other streaming sites and I only use YouTube.

**Comment by maddyhof** [comment]
To confirm, when you tested the other streaming sites, did they perform well?

**Comment by do02fw** [comment]
> 要确认,当你测试其他流媒体站点时,它们表现好吗?

我通过apkpure.com下载文件的时候速度很快，目前没有别的流媒体网站可以测试

**Comment by jyyi1** [comment]
Thanks @do02fw for the confirmation, this issue might be related to UDP traffic, because YouTube is using QUIC protocol which is based on UDP. Would you please try disabling UDP traffic in your server (VMISS)? Then YouTube will fallback to the TCP stream.

Also wanna know more things about how did you use Outline Keys with v2ray or wireguard? Because I don't think we support their key format.

**Comment by do02fw** [comment]
I am using openvpn and I found that YouTube is using HTTP3 protocol, if I disable UDP it will slow down, so I can't disable it, can you support UDP traffic?

**Comment by jyyi1** [comment]
Actually we support UDP traffic (if you are using Outline Manager to setup the Outline server). One more question: how do you connect openvpn to outline server? Did you decode the Outline Key by yourself?

I asked this because the OpenVPN might use a different protocol, network configuration or decoding algorithms which might cause the performance difference, but we need to further investigate it if that is the case.

**Comment by do02fw** [comment]
No, I'm using the openvpn client, I opened the developer mode of my browser and saw that YouTube uses the http3 protocol, but it's slow if you use outline.

**Comment by do02fw** [comment]
Can outline use the UDP protocol throughout to transfer data? It would be faster.

**Comment by jyyi1** [comment]
> No, I'm using the openvpn client, I opened the developer mode of my browser and saw that YouTube uses the http3 protocol, but it's slow if you use outline.

But OpenVPN should not be able to connect to Outline Server directly. So you are not using the same server, right?

> Can outline use the UDP protocol throughout to transfer data? It would be faster.

Yes. Outline doesn't have any restrictions. But your cloud provider may have some.
