### ISSUE TITLE
ERROR:ssl_client_socket_impl.cc(999) on Windows 7

### ISSUE THREAD

**Issue by cornzzy** [Jigsaw-Code/outline-client#1659]
**Describe the bug**
Trying to connect on Windows 7 machine to a dynamic access link (the domain has https), logs the following in DEBUG mode (powershell):
```
[608:0706/142716.463:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error
01
```

**To Reproduce**
I don't think if it happens on every Windows 7 machine. I simply connect, the UI says Sorry, Unexpected error... and the cli logs the above error.

**Client System:**
 - Outline Client Windows 1.10.1
 - Your Operating System: Windows 7

**Additional context**
I'm guessing the app can't handle https/ssl request to a ssconf://asd.com/asd.json dynamic access link. Is the machine missing something?

**Comment by cornzzy** [comment]
Is version 1.11.0 installer available?

**Comment by maddyhof** [comment]
Yes, the installer is available at https://getoutline.org/get-started/#step-3, click Windows, then click Get Outline Client.
