### ISSUE TITLE
The Outline keeps to tell there is updated version to be installed once close the app, but it keeps failing to uninstall the old

### ISSUE THREAD

**Issue by kevy8707** [Jigsaw-Code/outline-client#1668]
**Describe the bug**
When open the Outline, it will tell there is new version to be installed, but when close the app, it failed to uninstall the old app files as below,
![image](https://github.com/Jigsaw-Code/outline-client/assets/46775272/b57f4a9a-1636-48ea-abe5-13076d5c95c6)

**To Reproduce**
How can the broken behavior be reproduced? 

**Expected behavior**
It won't pop out the update message

**Screenshots**
![image](https://github.com/Jigsaw-Code/outline-client/assets/46775272/423803e8-b0f5-4067-ba12-f907182a026c)

**Client System (please complete the following information):**
 - Outline Client Version 1.10.1
 - Your Operating System: Windows 10

**Submit Feedback**
Please submit feedback through the app and label it with this issue number.

**Additional context**
The version should already be the latest one, I tried to uninstall it directly and download the installer and re-install

**Comment by dexedrine-01** [comment]
Same problem.

> delete the cache folder (...\AppData\Local\outline-client-updater 

It is not help.

**Comment by jyyi1** [comment]
hi @dexedrine-01 , please "uninstall Outline", and then reinstall it.

**Comment by dexedrine-01** [comment]
I did that for about 5 times. It is not help.

**Comment by kevy8707** [comment]
Uninstall the outline and go to \AppData\Local\outline-client-updater\pending and install from the package from there.



Kevin Yang
SHORELIGHT |  Senior Desktop Support Specialist
+86 18121007969 | ***@***.******@***.***> | shorelight.com<http://www.shorelight.com/>

[signature_1034637981]

[signature_1155640839]<https://www.linkedin.com/company/shorelight/>  [signature_1190072227] <https://www.instagram.com/shorelightco/>   [signature_3166320455] <https://www.facebook.com/ShorelightEducation/>   [signature_3866694986] <https://www.youtube.com/channel/UC89S1OS4ej37XKYCWIn7j6Q>
