### ISSUE TITLE
Error when building Android on Windows

### ISSUE THREAD

**Issue by GitCod-Man** [Jigsaw-Code/outline-client#1670]
**Describe the issue**
build with error

**Environment**
 - OS: windows10
 - NPM version (`9.8)
 - Node.js version(18.16)

**Additional context**
I am building an Android application on Windows, but an error occurred：
  
▶ action(cordova/build):
  ▶ action(www/build):
  ▶ action(www/build): � Success! (27308ms)
  ▶ action(cordova/setup):
    ▶ action(www/build):
    ▶ action(www/build): � Success! (27184ms)
    Copying Android third party libraries...
  ERROR(spawn_stream): node --trace-uncaught E:\vpnnnnnn\outline-client-client_android\src\cordova\build.action.mjs android failed w
ith exit code 1. Printing stderr:
    ERROR(spawn_stream): node --trace-uncaught E:\vpnnnnnn\outline-client-client_android\src\cordova\setup.action.mjs android failed
 with exit code 1. Printing stderr:
    �����﷨����ȷ��
  ▶ action(cordova/setup): ❌ Failed.
▶ action(cordova/build): ❌ Failed.

**Comment by jyyi1** [comment]
Reproduced:

```
▶ action(cordova/build):
  Running [node '--trace-uncaught' 'C:\src\outline-client\src\cordova\build.action.mjs' 'android']
  ▶ action(www/build):
    Running [node '--trace-uncaught' 'C:\src\outline-client\src\www\build.action.mjs' 'android']
  ▶ action(www/build): 🎉 Success! (20646ms)
  ▶ action(cordova/setup):
    Running [node '--trace-uncaught' 'C:\src\outline-client\src\cordova\setup.action.mjs' 'android']
    ▶ action(www/build):
      Running [node '--trace-uncaught' 'C:\src\outline-client\src\www\build.action.mjs' 'android']
    ▶ action(www/build): 🎉 Success! (20934ms)
    Copying Android third party libraries...
  ERROR(spawn_stream): node --trace-uncaught C:\src\outline-client\src\cordova\build.action.mjs android failed with exit code 1. Printing stderr:
    ERROR(spawn_stream): node --trace-uncaught C:\src\outline-client\src\cordova\setup.action.mjs android failed with exit code 1. Printing stderr:
    The syntax of the command is incorrect.
  ▶ action(cordova/setup): ❌ Failed.
▶ action(cordova/build): ❌ Failed.
```
