### ISSUE TITLE
Outline Client service fails to start on Windows

### ISSUE THREAD

**Issue by e-nurtin** [Jigsaw-Code/outline-client#1694]
Outline just cycles a message whenever connect button is pressed
_1. We will initialize Outline, which may require admin permissions. Would you like to proceed ?_ 
_2. Outline has successfully initialized, please try again to connect to server._

Client version - 1.10.1

OS Info - 

Edition	Windows 10 Education
Version	22H2
OS build	19045.3324
Experience	Windows Feature Experience Pack 1000.19041.1000.0

-----------------------------------------------

Already tried uninstalling the network adapter Tap v9

Also submitted a ticket with reference number 00552120 on 10th Aug 2023.

Adding some pictures for further clarification and the Error from the Event viewer -> System

![event_viewer_error](https://github.com/Jigsaw-Code/outline-client/assets/113053333/232a6a1b-7a18-4d3b-a357-8a590609f767)
![Question](https://github.com/Jigsaw-Code/outline-client/assets/113053333/e40b45ea-887f-41f0-82f7-2ead585684c3)
![cycle](https://github.com/Jigsaw-Code/outline-client/assets/113053333/db5dc4c9-546d-4eec-9f0b-6de9f6cb240b)

**Comment by maddyhof** [comment]
I've escalated your ticket reference number to customer support. Thanks for your patience.
