### ISSUE TITLE
Always on VPN support to android

### ISSUE THREAD

**Issue by manojprithvee** [Jigsaw-Code/outline-client#17]

**Comment by fortuna** [comment]
To make sure we understand, do you mean automatically on after a phone reboot?

**Comment by fortuna** [comment]
Some relevant reference: https://developer.android.com/reference/android/app/admin/DevicePolicyManager.html#setAlwaysOnVpnPackage(android.content.ComponentName,%20java.lang.String,%20boolean)

**Comment by manojprithvee** [comment]
There is a options in the newer version of android which has the ability to
connect to VPN always meaning it will not send data through normal isp when
VPN is switching between WiFi and data.

**Comment by alalamav** [comment]
Thank you for the feedback, @manojprithvee. We are rolling out this feature soon.

**Comment by eleith** [comment]
this looks to have been released on june 6th: https://play.google.com/store/apps/details?id=org.outline.android.client&hl=en_US

**Comment by manojprithvee** [comment]
Super

**Comment by alalamav** [comment]
This feature was released in v1.1.1 (see #97).
