### ISSUE TITLE
Update the outline

### ISSUE THREAD

**Issue by omid2s** [Jigsaw-Code/outline-client#1716]
I installed version 1.10.1. It is the latest version that is available on GitHub. When I open Outline, a window opens and says that a new version of Outline has been downloaded, and after restarting Outline, is installed.

But the outline cannot be updated to the new version and a window opens saying:
failed to uninstall old application files.please running the installer again.:2

[[URL=https://uupload.ir/][IMG]https://s6.uupload.ir/files/1_n9lo.jpg[/IMG][/URL]](url)

But I don't know where the new version of Outline is downloaded on my hard drive.

Please investigate this issue
thank you

**Comment by jyyi1** [comment]
Hi @omid2s , sorry about the inconvenience. Could you please try the workaround mentioned in this issue? https://github.com/Jigsaw-Code/outline-client/issues/1643#issuecomment-1639240133 Thanks.

**Comment by jyyi1** [comment]
Mark as a duplication of https://github.com/Jigsaw-Code/outline-client/issues/1727
