### ISSUE TITLE
npm ERR! notsup Actual:   {"npm":"10.1.0","node":"v20.6.1"} build fail

### ISSUE THREAD

**Issue by dylu9988** [Jigsaw-Code/outline-client#1739]
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: outline-client@0.0.0
npm ERR! notsup Not compatible with your version of node/npm: outline-client@0.0.0
npm ERR! notsup Required: {"node":"^18.16.0","npm":"^9.5.1"}
npm ERR! notsup Actual:   {"npm":"10.1.0","node":"v20.6.1"}

**Comment by stazherkb** [comment]
Having the same trouble, Day 3. Debian 12 (vbox), clear installation.

[badeng.log](https://github.com/Jigsaw-Code/outline-client/files/12833099/badeng.log)

**Comment by stazherkb** [comment]
For some [stupid] reason, the npm i command only works if you have nodejs and npm versions close to required {"node":"^18.16.0","npm":"^9.5.1"}.

So the solution here is to **downgrade** your nodejs version:
`npm install -g n
n 18.16.0`

**Comment by jyyi1** [comment]
Hi, Outline Client requires a specific version of node to be installed. @dylu9988, please reference to the comment by @stazherkb to install a specific version of node. We also recommend to use [`nvm`](https://github.com/nvm-sh/nvm) to manage the node installations.
