### ISSUE TITLE
https://registry.npmjs.org/Electron   No longer exists

### ISSUE THREAD

**Issue by dylu9988** [Jigsaw-Code/outline-client#1741]
PS E:\github\outline-client> npm install -g Electron
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/Electron - Not found
npm ERR! 404
npm ERR! 404  'Electron@*' is not in this registry.
npm ERR! 404 This package name is not valid, because
npm ERR! 404  1. name can no longer contain capital letters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in: C:\Users\Administrator\AppData\Local\npm-cache\_logs\2023-10-04T12_35_51_841Z-debug-0.log
PS E:\github\outline-client> npm install
(node:20012) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by jyyi1** [comment]
Hi @dylu9988 ,

It should be [`electron`](https://www.npmjs.com/package/electron) instead of `Electron`. And we do not require a global installed electron when you build Outline Client, you can run `npm install` directly.
