### ISSUE TITLE
Outline Client custom branding?

### ISSUE THREAD

**Issue by fortuna** [Jigsaw-Code/outline-client#1759]
### Discussed in https://github.com/Jigsaw-Code/outline-sdk/discussions/78

<div type='discussions-op-text'>

<sup>Originally posted by **SiteSplat** September 22, 2023</sup>
Any plans for the outline client to have options to ship it with custom branding?
Something as simple as a color scheme and logo. 
</div>

**Comment by maddyhof** [comment]
Thanks for reaching out. We're tracking this issue in #1758 so I'll close this as a duplicate.
