### ISSUE TITLE
is it for real?

### ISSUE THREAD

**Issue by kpma1985** [Jigsaw-Code/outline-client#1766]
![grafik](https://github.com/Jigsaw-Code/outline-client/assets/4441318/48a35b86-0e8e-439c-b8ba-e60995a006ae)

:D

**Comment by maddyhof** [comment]
Thanks for reaching out. I want to make sure I understand your question. We don't publish released on GitHub anymore, but you can get the latest release [here](https://getoutline.org/get-started/#step-3). Feel free to reopen this ticket if you have additional questions.
