### ISSUE TITLE
DNS requests time out on Windows Client

### ISSUE THREAD

**Issue by kastashov** [Jigsaw-Code/outline-client#1777]
**Describe the bug**

When Windows client is connected to the Outline server, DNS requests from OS time out..

**To reproduce**

1. Connect to Outline server on Windows.
2. Open cmd
3. Type nslookup google.com

nslookup google.com
DNS request timed out.
    timeout was 2 seconds.
Server:  UnKnown
Address:  192.168.1.1

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
 Request to UnKnown timed-out

**Expected behavior**

When client is disconnected from the Outline server:

nslookup google.com
Server:  RT-AC5300
Address:  192.168.1.1

Non-authoritative answer:
Name:    google.com
Addresses:  2404:6800:4015:801::200e
          142.250.70.174

**Client system (please complete the following information):**
 - Outline Client Version 1.12.1
 - Windows 10

**Comment by kastashov** [comment]
I removed 1.12.1 and installed 1.10.1, the issue still persists.
Feels like it's something not right with the configuration coming from the server?

**Comment by jyyi1** [comment]
It seems the DNS server is configured as `192.168.1.1`. Could you please double check why Windows is not using the public accessible DNS server `9.9.9.9` we configured? Do you have other network adapters that have higher priority than the Outline's one?

**Comment by kastashov** [comment]
Yeah, Ethernet metric was set manually to 10, Outline was set to auto. 
I manually set Outline metric to less than that of Ethernet, the problem was resolved.

**Comment by jyyi1** [comment]
I'm glad the workaround is working. Yes, this is a known issue tracked here: https://github.com/Jigsaw-Code/outline-client/issues/1235 .
