### ISSUE TITLE
100% CPU usage even when not connected (macOS Sonoma)

### ISSUE THREAD

**Issue by piskov** [Jigsaw-Code/outline-client#1786]
macOS Sonoma 14.2 Beta (23C5047e)
macbook air m1 16GB
outline client 1.11.0 (468085)

Outline is destroying battery with using 100% of one core even when not connected.

<img width="842" alt="Screenshot 2023-11-19 at 14 12 25" src="https://github.com/Jigsaw-Code/outline-client/assets/4349021/a8ae682f-eb85-4cab-995b-8bc45c898523">

Here is sampling trace:
[Sample of Outline.txt](https://github.com/Jigsaw-Code/outline-client/files/13402974/Sample.of.Outline.txt)

**Comment by maddyhof** [comment]
Thanks for reaching out! We're working on a version of Outline Client that supports M1s macOS Sonoma. We're hoping that'll fix the issue, but if it persists after that release we're happy to investigate it further.

**Comment by piskov** [comment]
@maddyhof this is something new (i.e. a few weeks at most) — maybe something on apple’s part with the latest macOS public beta.

**Comment by piskov** [comment]
@maddyhof yep, it’s a [regression in webkit ](https://bugs.webkit.org/show_bug.cgi?id=264534)so any webview app (effing electron, my ass) affected. Should be fixed in next macos beta.
