### ISSUE TITLE
Can't access local IP addresses (affects Chromecast use, and others)

### ISSUE THREAD

**Issue by oleiolei** [Jigsaw-Code/outline-client#18]
My router uses 192.168.1.1 for administration, I can't open that page after my computer is connected to the proxy server. However, the router page can be opened in a browser when proxy of that browser is disabled, so It would be great if local sites are proxy-free so that we can see them while we have open Internet.

I suggest that you add local IP addresses to Windows proxy bypass setting, like what Shadowsocks Windows client does in regards to proxy configuration. It works.

This is configuration of Shadowsocks Windows client: 
`localhost;127.*;10.*;172.16.*;172.17.*;172.18.*;172.19.*;172.20.*;172.21.*;172.22.*;172.23.*;172.24.*;172.25.*;172.26.*;172.27.*;172.28.*;172.29.*;172.30.*;172.31.*;172.32.*;192.168.*`

**Comment by trevj** [comment]
@oleiolei Many thanks for the report. We'll take this into consideration.

**Comment by Kaless1n** [comment]
@trevj  No changes yet?

**Comment by trevj** [comment]
@Kaless1n I'm afraid we haven't made progress on this issue yet, sorry.

**Comment by trevj** [comment]
I'm happy to say @alalamav has implemented this and it's been rolled out on all platforms:
- https://github.com/Jigsaw-Code/outline-client/releases/tag/windows-v1.2.17
- https://github.com/Jigsaw-Code/outline-client/releases/tag/ios-v1.2.1
- https://github.com/Jigsaw-Code/outline-client/releases/tag/android-v1.2.6
