### ISSUE TITLE
Better status/stlying

### ISSUE THREAD

**Issue by Kief5555** [Jigsaw-Code/outline-client#1809]
**What would you like the app to enable you to do?**
- Dark mode
- Stlying fixes for notched devices
- Status and ping of the servers you have

**Comment by Kief5555** [comment]
> Yeah, the UI of the app really needs an overhaul. I appreciate your feedback. Do you mind breaking this up into individual issues? It's very difficult for us to prioritize otherwise.

Sure!

I would 

1. Prioritize making errors more know. I had 3 VPs, tried connecting in China and all illegal configuration but no info on what's wrong. When out of China, works just fine.

2. Ping to the server or their availability. Pretty standard to see which is best to connect to. 

3. Just more toggle features. Maybe TCP toggle or a special feature. Basically more control on the client and info.

**Comment by Kief5555** [comment]
Opened:

#1819 
#1820 
#1821

**Comment by Feniksovich** [comment]
Real essential improvements
+1
