### ISSUE TITLE
Android client VPN permission error

### ISSUE THREAD

**Issue by ky0nch3ng** [Jigsaw-Code/outline-client#182]
![Imgur](https://i.imgur.com/kXXzwAV.jpg)

System VPN Settings has no Outline options to setting?

![Imgur](https://i.imgur.com/ziXxfEr.jpg)

https://developer.android.com/reference/android/net/VpnService

**Comment by ky0nch3ng** [comment]
Please trun off  `Always-On VPN Mode`

**Comment by mistycarlyle31** [comment]
Allways in VPN now what?😈

Misty n aj

**Comment by ky0nch3ng** [comment]
@mistycarlyle31 
On android 8.0+, the second pictrue in my issue, have a option "always-on vpn" in this vpn app setting, this function means connected vpn on lockscreen is working.
