### ISSUE TITLE
Custom routing exception

### ISSUE THREAD

**Issue by mortezabahrami** [Jigsaw-Code/outline-client#1837]
I know that the Outline client does not connect to private IP address ranges through VPN, but it would be great to add custom routing exceptions that don't route through VPN. Also if we could add exceptions based on countries' IP databases, that would be awesome. (for example for banking apps)

**Comment by Korb** [comment]
> the Outline client does not connect to private IP address ranges through VPN

In ProtonVPN this feature is explicitly stated in the settings:

> LAN connections: allows you to connect to printers, speakers, and other devices in your device's local network.

Having not seen a similar setting in the Outline mobile app, I assumed that the app was blocking local connections by redirecting all traffic from the device through the VPN.  Perhaps this should be explicitly displayed, for example, with a non-toggleable "Apply to local connections" switch.
