### ISSUE TITLE
ReInstall outLine Manager

### ISSUE THREAD

**Issue by sbruens** [Jigsaw-Code/outline-client#1923]
### Discussed in https://github.com/Jigsaw-Code/outline-sdk/discussions/191

<div type='discussions-op-text'>

<sup>Originally posted by **@alexsandrskopin** February 28, 2024</sup>
I reinstalled outline manager, how can I get login information (to connect to my server)? I don't want to reinstall the entire server. I just want to connect the manager (how to get the magic green line) which appears after installing the server</div>

**Comment by ieya100** [comment]
+1
