### ISSUE TITLE
Windows client add system tray?

### ISSUE THREAD

**Issue by ky0nch3ng** [Jigsaw-Code/outline-client#20]
![](https://www.howtogeek.com/wp-content/uploads/2016/10/ximg_580ab50544559.png.pagespeed.gp+jp+jw+pj+ws+js+rj+rp+rw+ri+cp+md.ic.fBZadZVl5t.png)

**Comment by carlparte** [comment]
Support with greatest like!

**Comment by alalamav** [comment]
This feature has been released on the [Windows client v1.1.2](https://github.com/Jigsaw-Code/outline-releases/blob/master/client/Outline-Client.exe?raw=true).
