### ISSUE TITLE
[Bug]:  Fail to install Tap in windows 11 

### ISSUE THREAD

**Issue by betoeu** [Jigsaw-Code/outline-client#2012]
### Application

Outline Client

### Describe the bug

when installing the outline client it shows a message:
Sorry, we could not configure your system to connect to Outline. Please try running the installer again. If you cannot install Outline, please get in touch with us and let us know that the TAP device falied to install with error code 1
![erroTap1](https://github.com/Jigsaw-Code/outline-apps/assets/2381323/b101b4db-4af4-4036-9471-6ad64fa8b9b7)

### Steps to reproduce

Start the installer and the at the begin alreday shows the errors mssage

### What did you expect to happen?

to install tap driver

### What actually happened?

Installed the outline without the tap driver

### Outline Version

1.13.0.0

### What operation system are you using?

Windows

### Operating System Version

Windows 11

**Comment by cornzzy** [comment]
Version 1.13.0 doesn't install on windows. 

First uninstall the broken driver installed by 1.13.0 installer by going to Device Manager, under Network adapters, right-click on Unknown device and uninstall.

Then you need to find and install the previous version.
