### ISSUE TITLE
Invalid Access Key using Windows client

### ISSUE THREAD

**Issue by lezhangisu** [Jigsaw-Code/outline-client#205]
Hi, I just set up my own outline server on my own server. Everything was great, I can connect from OSX , Android and iOS without a problem. 

However, when I tried to connect from windows client, it throws me an error "It seems like your access key is invalid..... please contact your service admin"
<img width="339" alt="screen shot 2018-08-08 at 9 25 39 pm" src="https://user-images.githubusercontent.com/14080603/43874461-a311de86-9b51-11e8-9a3b-8f1b2850aa9f.png">

I tried with 3 different windows machines (win10 and win7) with all my 5 keys and all won't work, but they work just fine on other platforms. Can anyone help me, please?

Thanks

**Comment by trevj** [comment]
@lezhangisu thanks for trying Outline.

Sorry you've been having trouble on Windows. Two questions:
- Which version of the client are you running (select About from the left-hand side menu)?
- Do you have a firewall running on your Windows machine?

**Comment by lezhangisu** [comment]
@trevj 
Thanks for your attention. Answers to your questions:
1. It was Windows version 1.2.2, and I tried v1.2.3 today, still no luck.
2. I turned off the windows firewall and it's still not working. 

Your help is highly appreciated.

**Comment by trevj** [comment]
@lezhangisu Thanks for trying 1.2.3. I'm afraid there was a major bug in that release. Can you please try 1.2.4?:
https://github.com/Jigsaw-Code/outline-client/releases/tag/windows-v1.2.4

If you still have problems with 1.2.4 then you can help us debug by submitting feedback:
* try to connect
* after it fails, click Submit Feedback from the left-hand side menu

Thanks again!

**Comment by ercxar** [comment]
I got this error when my network blocked the IP address of my VPS which I was using for outline. I don't know how did they detect that! I had to change the IP address of my VPS to circumvent this issue.

Suggestion: (I have a very limited knowledge, but aren't you able to make a difference when you don't receive any data back from the server and when the access key is actually invalid?) and I'm pretty positive if you block the IP address of outline server you will receive invalid access key error.

**Comment by trevj** [comment]
@ercxar How they detect that is, indeed, the question :-)

Regarding error messaging, when Outline can't reach your server at all it should display this message:
> We can’t seem to connect to your server. Please check that you are connected to the internet and try again.

Is that not what you're seeing?

**Comment by trevj** [comment]
@ercxar I'm going to close this due to inactivity but if you'd like to discuss further, please do re-open.
