### ISSUE TITLE
Add outline-server alias？

### ISSUE THREAD

**Issue by ky0ncheng** [Jigsaw-Code/outline-client#21]
such as
```
ss://{hash}@{ip}:{port}#{alias}
```

**Comment by studentmain** [comment]
ss original alias is supported
`ss://{hash}@{ip}:{port}#{alias}`

**Comment by ky0ncheng** [comment]
@studentmain I known, your protocol format is compatible with ss original.

**Comment by trevj** [comment]
@ky0ncheng Thanks for the report. As @studentmain points out, Outline does support URLs in that format. via our parsing library here:
https://github.com/Jigsaw-Code/outline-shadowsocksconfig
