### ISSUE TITLE
client fail on chrome os

### ISSUE THREAD

**Issue by sailosha** [Jigsaw-Code/outline-client#217]
OS: chrome os 69.0.3497.21  dev 64bit

Issue: chrome os didn't recognize outline TCP/UDP forward through chrome. It will use the original IP on the browser, but the app in the system is using outline server IP. 
The browser IP check is my original IP, but the app is outline VPN IP. 
I tried both play store release and newest release on the github, it doesn't work. My server doesn't have any issue.

**Comment by bemasc** [comment]
Looks like this is [an open Chrome OS bug](https://crbug.com/866179).

**Comment by sailosha** [comment]
@bemasc Thanks so much.

**Comment by trevj** [comment]
@sailosha Delighted to hear it.
