### ISSUE TITLE
please support download from the org site directly

### ISSUE THREAD

**Issue by cnBruceHong** [Jigsaw-Code/outline-client#235]
we can't download the outline app from apple store in China.
please support download from the org site directly.
thanks!

**Comment by studentmain** [comment]
https://github.com/Jigsaw-Code/outline-releases

**Comment by studentmain** [comment]
可能你需要搞一个香港账号

**Comment by alalamav** [comment]
Unfortunately, the Outline macOS client must be distributed through the Mac App Store, given that it requires NetworkExtension entitlements (see answer 8 on [this thread](https://forums.developer.apple.com/thread/67613)).
