### ISSUE TITLE
could I invited to join the "Jigsaw Operations LLC" apple developer team?

### ISSUE THREAD

**Issue by Rezhe** [Jigsaw-Code/outline-client#236]
<img width="367" alt="screen shot 2018-08-27 at 11 50 38 am" src="https://user-images.githubusercontent.com/30205820/44670078-babc9880-a9ef-11e8-8e11-d3f26c11fe7c.png">
I try to change the user interface in this project, There are 1 error may be caused  by Development provisioning profile, if so, Is there a someway that I can join the team, thanks very much!

**Comment by Rezhe** [comment]
@alalamav thanks for respond, I registered for Apple Developer account and new app id called org.outline.ios.client, configured Network Extensions then pop out that message, does it that means I should still need to be invited to join the group, if so, what information should I provide for u guys? :D 
<img width="430" alt="screen shot 2018-08-28 at 7 54 37 pm" src="https://user-images.githubusercontent.com/30205820/44757279-41f73280-aafc-11e8-94fe-f582381b6ff1.png">

**Comment by Rezhe** [comment]
@alalamav Hi, thanks for respond, there are still some problem need to be fixed.
First, I registered a App ID called "org.outline.ios.client", is turns out error below:
<img width="430" alt="screen shot 2018-08-28 at 7 54 37 pm" src="https://user-images.githubusercontent.com/30205820/44801554-62200380-ab87-11e8-9fd4-1282640e6b21.png">
Then I created a unique one and getting error like that:
<img width="430" alt="screen shot 2018-08-29 at 12 29 36 pm" src="https://user-images.githubusercontent.com/30205820/44801638-9398cf00-ab87-11e8-9124-f6f9666caaba.png">

On the Buildtime, I get 8 error while I use Xcode 9.4.1(swift 4.1.3), It is mostly about "ConnectionStore".
And when I try to use Xcode 9.2 as the doc says, "ConnectionStore" error fixed, but those error turns out:
<img width="270" alt="screen shot 2018-08-29 at 12 33 22 pm" src="https://user-images.githubusercontent.com/30205820/44801851-2e91a900-ab88-11e8-8160-95320976884c.png">
[Build target VpnExtension_2018-08-29T11-32-24.txt](https://github.com/Jigsaw-Code/outline-client/files/2332970/Build.target.VpnExtension_2018-08-29T11-32-24.txt)

```
ld: warning: ignoring file /Users/ruizhewang/Desktop/outline-client/platforms/ios/Outline/Plugins/cordova-plugin-outline/Shadowsocks_iOS.framework/Shadowsocks_iOS, missing required architecture x86_64 in file /Users/ruizhewang/Desktop/outline-client/platforms/ios/Outline/Plugins/cordova-plugin-outline/Shadowsocks_iOS.framework/Shadowsocks_iOS (2 slices)
ld: warning: ignoring file /Users/ruizhewang/Desktop/outline-client/platforms/ios/Outline/Plugins/cordova-plugin-outline/PacketProcessor_iOS.framework/PacketProcessor_iOS, missing required architecture x86_64 in file /Users/ruizhewang/Desktop/outline-client/platforms/ios/Outline/Plugins/cordova-plugin-outline/PacketProcessor_iOS.framework/PacketProcessor_iOS (2 slices)
Undefined symbols for architecture x86_64:
  "_start_ss_local_server_with_callback", referenced from:
      -[Shadowsocks startShadowsocks] in Shadowsocks.o
  "_OBJC_CLASS_$_TunnelInterface", referenced from:
      objc-class-ref in PacketTunnelProvider.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
My Environmental configuration is
Mac os Mojave 10.14
Xcode 9.2
Command_Line_Tools_macOS_10.13_for_Xcode_10_Beta_6
Node v10.9.0

**Comment by alalamav** [comment]
@Rezhe, you need to select a unique bundle ID, for example unique.outline.ios.client - org.outline.ios.client is already used by our iOS client. For the VpnExtension target, please append VpnExtension to the bundle ID you created, i.e. unique.outline.ios.client.VpnExtension. You also need to create a unique ID for the group, i.e. group.unique.outline.ios.client. Then, generate the provisioning profiles on your Apple developer account.

As for the build errors, the project supports Xcode 9.2. We still need to upgrade to the latest version of Swift. 

> On the Buildtime, I get 8 error while I use Xcode 9.4.1(swift 4.1.3), It is mostly about "ConnectionStore".
And when I try to use Xcode 9.2 as the doc says, "ConnectionStore" error fixed, but those error turns out.

Try running `yarn run clean && yarn` before rebuilding the project. It seems like the third party dependencies have not been updated.

**Comment by Rezhe** [comment]
@alalamav Thanks very much! problem being solved :D
