### ISSUE TITLE
windows client: "Not able to configure routing tables successfully"

### ISSUE THREAD

**Issue by birdmoney11** [Jigsaw-Code/outline-client#251]
Using ShadowSocks installed on VPS and I get the "We were not able to configure your routing tables successfully......" message when using the Windows Outline Client. 

I am able to connect to the same ShadowSocks server on my mobile phone.

**Comment by studentmain** [comment]
Paste output of `route print` command here.
What's your client version?
How do you connect to Internet?

**Comment by YoulianBoshi** [comment]
same question

**Comment by birdmoney11** [comment]
``===========================================================================
Interface List
  5...00 ac 49 0f 87 63 ......VPN Client Adapter - VPN2
 13...00 ff 57 12 fb 59 ......ExpressVPN Tap Adapter
 16...00 16 6f e4 41 80 ......Microsoft Wi-Fi Direct Virtual Adapter #2
 11...02 16 6f e4 41 7f ......Microsoft Hosted Network Virtual Adapter
  3...50 46 5d 44 76 c6 ......Qualcomm Atheros AR8161 PCI-E Gigabit Ethernet Controller (NDIS 6.30)
 15...00 ff 6c d7 d5 29 ......Kaspersky Security Data Escort Adapter
 18...00 ac c1 ff 07 61 ......VPN Client Adapter - VPN
  2...00 16 6f e4 41 7f ......Intel(R) Dual Band Wireless-AC 7260
  1...........................Software Loopback Interface 1
===========================================================================

IPv4 Route Table
===========================================================================
Active Routes:
Network Destination        Netmask          Gateway       Interface  Metric
          0.0.0.0          0.0.0.0      192.168.1.1    192.168.1.170     35
          0.0.0.0        128.0.0.0     10.131.0.177     10.131.0.178      6
       10.131.0.1  255.255.255.255     10.131.0.177     10.131.0.178      6
     10.131.0.176  255.255.255.252         On-link      10.131.0.178    261
     10.131.0.178  255.255.255.255         On-link      10.131.0.178    261
     10.131.0.179  255.255.255.255         On-link      10.131.0.178    261
     45.41.185.87  255.255.255.255      192.168.1.1    192.168.1.170     36
        127.0.0.0        255.0.0.0         On-link         127.0.0.1    331
        127.0.0.1  255.255.255.255         On-link         127.0.0.1    331
  127.255.255.255  255.255.255.255         On-link         127.0.0.1    331
        128.0.0.0        128.0.0.0     10.131.0.177     10.131.0.178      6
      192.168.1.0    255.255.255.0         On-link     192.168.1.170    291
    192.168.1.170  255.255.255.255         On-link     192.168.1.170    291
    192.168.1.255  255.255.255.255         On-link     192.168.1.170    291
        224.0.0.0        240.0.0.0         On-link         127.0.0.1    331
        224.0.0.0        240.0.0.0         On-link     192.168.1.170    291
        224.0.0.0        240.0.0.0         On-link      10.131.0.178    261
  255.255.255.255  255.255.255.255         On-link         127.0.0.1    331
  255.255.255.255  255.255.255.255         On-link     192.168.1.170    291
  255.255.255.255  255.255.255.255         On-link      10.131.0.178    261
===========================================================================
Persistent Routes:
  None

IPv6 Route Table
===========================================================================
Active Routes:
 If Metric Network Destination      Gateway
  1    331 ::1/128                  On-link
  1    331 ff00::/8                 On-link
===========================================================================
Persistent Routes:
  None

``

I am using Outline Version 1.2.8, and I connect to the internet via 5ghz WiFI. I have also tried at coffee shops and other methods.

**Comment by studentmain** [comment]
Seems you have another VPN installed... Are they working when you try Outline? Obviously, they can't work at same time.

**Comment by trevj** [comment]
@birdmoney11 Thanks for trying Outline - sorry you've been having trouble with the new Windows client. The output of `route print` tells me two things:
1. you have other VPN software installed (should not be a problem unless, as @studentmain notes, it's active)
2. there is no interface for Outline

Can you please try installing Outline again, and tell me if the installer tells you that it cannot configure Outline correctly? I think that must have somehow happened.

**Comment by OneSecure** [comment]
我已经试过 你的发行包. 就 [v1.1.2](https://github.com/Jigsaw-Code/outline-client/releases/tag/windows-v1.1.2) 可以正常使用. 其他的都没戏. 可惜的是, 用着 `v1.1.2` 当时没事, 但退出以后, 软件就自动更新到当前版本, 就出现了 `Not able to configure routing tables successfully` 错误. 可以对比这两个提交, 参照着修正错误.

**Comment by studentmain** [comment]
@OneSecure 这东西的机制在1.2以后有了彻底的变化。以前是学ss windows，现在是学openvpn。对比两个提交没什么意思，已经确定是新版本的路由表处理机制还不太完善。
把`route print`的输出粘出来看看究竟是什么情况。

**Comment by studentmain** [comment]
#234 #251 #262, seems it became a serious problem now...

**Comment by studentmain** [comment]
@OneSecure 是的，1.2.0才加入了TAP驱动，之前是学ss-windows直接改系统代理。

**Comment by OneSecure** [comment]
那问题复杂了. ssTap 软件是使用的 openVPN 的驱动成功搞通. 可惜作者已经彻底不玩了. 只能啃 openVPN 的源码去了.

**Comment by studentmain** [comment]
> 使用的OpenVPN的驱动
@OneSecure 现在就是这样做的，问题不在驱动，在于负责处理路由表的OutlineService服务不能应对复杂情况。

**Comment by yywudi** [comment]
是的，同样SSTAP可以安装成功的机器，Outline在安装的时候就会报错 "Could not rename the TAP device"
生成了Tap的虚拟网卡，但是看报错似乎并没有对虚拟网卡的重命名和后续配置。
所以在连接的时候，一直无法配置tap 网卡，无法处理路由表。
怀疑权限，安装和运行都已经管理员权限，问题依旧

**Comment by trevj** [comment]
@birdmoney11 Can you confirm other VPN software was inactive when you ran `route print`? Looking at it again just now, I think there **is** other VPN software active (on the `10.131.0.177` interface). If you reboot your computer, does Outline then connect?

**Comment by trevj** [comment]
@birdmoney11 Regarding the lack of an Outline interface in `route print`, we improved the TAP device installer in 1.2.10. Can you please try again?:
https://github.com/Jigsaw-Code/outline-client/releases/tag/windows-v1.2.10

**Comment by trevj** [comment]
@yywudi Thanks for the feedback. I'm using Google Translate to read your message so apologies if I'm wrong but, as per my comment in https://github.com/Jigsaw-Code/outline-client/issues/251#issuecomment-421417268, 1.2.10 includes an improved TAP device installer. Can you please try again?:
https://github.com/Jigsaw-Code/outline-client/releases/tag/windows-v1.2.10

**Comment by OneSecure** [comment]
经过测试 [v 1.2.11](https://github.com/Jigsaw-Code/outline-client/releases/tag/windows-v1.2.11) 在真机上可以成功连接. 但在 vmware 虚拟机上连接失败. 原因还是路由表问题. 
![bbbb](https://user-images.githubusercontent.com/16576155/45586362-d5b46580-b928-11e8-9eb7-664af191a652.png)
这是成功连上后 路由表里多出来的东西.
```
IPv4 Route Table
================================================================
Active Routes:
Network Destination        Netmask          Gateway       Interface  Metric
          0.0.0.0        128.0.0.0        10.0.85.1        10.0.85.2      0
        10.0.85.0    255.255.255.0         On-link         10.0.85.2    256
        10.0.85.2  255.255.255.255         On-link         10.0.85.2    256
      10.0.85.255  255.255.255.255         On-link         10.0.85.2    256
   xxx.xxx.xxx.xxx  255.255.255.255      192.168.0.1    192.168.0.104    100
        128.0.0.0        128.0.0.0        10.0.85.1        10.0.85.2      0
        224.0.0.0        240.0.0.0         On-link         10.0.85.2    256
  255.255.255.255  255.255.255.255         On-link         10.0.85.2    256
=================================================================
Persistent Routes:
  Network Address          Netmask  Gateway Address  Metric
   xxx.xxx.xxx.xxx  255.255.255.255      192.168.0.1       0
          0.0.0.0        128.0.0.0        10.0.85.1       0
        128.0.0.0        128.0.0.0        10.0.85.1       0
================================================================
Persistent Routes:
 If Metric Network Destination      Gateway
  0      0 fc00::/7                 On-link
  0      0 2000::/4                 On-link
  0      0 3000::/4                 On-link
=================================================================
```

由于虚拟机里连接老是失败, 无法比较 路由表 的变化.

**Comment by OneSecure** [comment]
问题也许找到了. 在 虚拟机的 win 7 上, 服务运行失败. 请找出失败原因.
![image](https://user-images.githubusercontent.com/16576155/45592867-e2c66880-b9ab-11e8-8ace-e042beca597b.png)

**Comment by birdmoney11** [comment]
@trevj Okay I tried installing the v1.2.10 but I ran into an error at the end of the installation process. It says: 
Sorry, we should not configure your system to connect to Outline. Please try running the installer again.

```
If you still cannot install Outline plese get in touch with us and let us know that the TAP device failed to install with this error: Device node created. Install is complete when drivers are installed...
Updating drivers for tap0901 from C:\Program Files
(x86)\Outline\tap-windows6\amd64\OemVista.inf.
Drivers installed sucessfully.
Could not create TAP device.
```
Second try I get a different error:
```

Sorry, we should not configure your system to connect to Outline. Please try running the installer again.

If you still cannot install Outline plese get in touch with us and let us know that the TAP device failed to install with this error: Device node created. Install is complete when drivers are installed...
Updating drivers for tap0901 from C:\Program Files
(x86)\Outline\tap-windows6\amd64\OemVista.inf.
Drivers installed successfully.
'powershell' is not recognized as an internal or external command, operable program or batch file.
New TAP device name:
Could not rename TAP device.
```

**Comment by trevj** [comment]
@birdmoney11 Thanks for the update. For some reason, the installer cannot run a necessary Powershell script. Two questions:
- have you enabled/disabled Powershell on your machine?
- do you have any anti-virus/anti-malware software on your machine?

Thanks for working through this with us!

**Comment by trevj** [comment]
@OneSecure Good to hear you can now connect on your host machine. Thanks for the debugging info. Regarding the VM, the output of `route print` tells me that there is no default gateway on the `192.168.0.1` interface. I don't know how that could have happened: Outline should refuse to connect in that scenario, yet I see it tried to configure its routes. Can you try disabling the virtual network card, then re-enabling it?

BTW, I will look into ATL services a little more, thanks.

**Comment by birdmoney11** [comment]
@trevj I do have anti-virus, it's Kaspersky. As for Powershell, I have no idea, never used that function before.

**Comment by lgg** [comment]
@trevj faced the same error.
Win 7 x64;
iOS Client in the same network works fine
**Currrent laptop** works fine with Outline 2 month ago, then reinstalled server and updated Clients(iOS works fine) and faced this error.

Trying installing 1.2.10:
![image](https://user-images.githubusercontent.com/12018713/45924058-a55b6100-befe-11e8-9cb6-ce74847e053c.png)

**Comment by lgg** [comment]
@trevj noted that after every install try i had new adapter in network list. 
Maybe error with renaming TAP device is relative to enconding? 

hmm i can't delete them:

![image](https://user-images.githubusercontent.com/12018713/45924080-316d8880-beff-11e8-9517-a05520f1619b.png)

**Comment by lgg** [comment]
@trevj `route print`

No other VPN is enabled.

```
===========================================================================
Список интерфейсов
 81...00 ff 69 8b 23 3e ......TAP-Windows Adapter V9 #7
 77...00 ff d5 a9 a4 ee ......TAP-Windows Adapter V9 #6
 34...00 ff 6b 2a cc 74 ......TAP-Windows Adapter V9 #3
 33...00 ff da e3 1b 00 ......TAP-Windows Adapter V9 #2
 17...54 ee 75 24 9a 5f ......Realtek PCIe GBE Family Controller
 16...14 2d 27 fa 8a 15 ......Microsoft Virtual WiFi Miniport Adapter
 11...14 2d 27 fa 8a 15 ......Плата адаптера 1x1 11b/g/n Wireless LAN PCI Express Half Mini Card
 19...0a 00 27 00 00 13 ......VirtualBox Host-Only Ethernet Adapter
 20...0a 00 27 00 00 14 ......VirtualBox Host-Only Ethernet Adapter #2
 22...00 50 56 c0 00 01 ......VMware Virtual Ethernet Adapter for VMnet1
 23...00 50 56 c0 00 08 ......VMware Virtual Ethernet Adapter for VMnet8
  1...........................Software Loopback Interface 1
 31...00 00 00 00 00 00 00 e0 Адаптер Microsoft ISATAP
 14...00 00 00 00 00 00 00 e0 Teredo Tunneling Pseudo-Interface
 27...00 00 00 00 00 00 00 e0 Адаптер Microsoft ISATAP #3
 37...00 00 00 00 00 00 00 e0 Адаптер Microsoft ISATAP #4
 26...00 00 00 00 00 00 00 e0 Адаптер Microsoft ISATAP #5
 29...00 00 00 00 00 00 00 e0 Адаптер Microsoft ISATAP #6
 28...00 00 00 00 00 00 00 e0 Адаптер Microsoft ISATAP #7
 72...00 00 00 00 00 00 00 e0 Адаптер Microsoft ISATAP #8
 36...00 00 00 00 00 00 00 e0 Адаптер Microsoft ISATAP #10
 38...00 00 00 00 00 00 00 e0 Адаптер Microsoft ISATAP #11
===========================================================================

IPv4 таблица маршрута
===========================================================================
Активные маршруты:
Сетевой адрес           Маска сети      Адрес шлюза       Интерфейс  Метрика
          0.0.0.0          0.0.0.0      192.168.1.1      192.168.1.9     25
        127.0.0.0        255.0.0.0         On-link         127.0.0.1    306
        127.0.0.1  255.255.255.255         On-link         127.0.0.1    306
  127.255.255.255  255.255.255.255         On-link         127.0.0.1    306
      192.168.1.0    255.255.255.0         On-link       192.168.1.9    281
      192.168.1.9  255.255.255.255         On-link       192.168.1.9    281
    192.168.1.255  255.255.255.255         On-link       192.168.1.9    281
     192.168.92.0    255.255.255.0         On-link      192.168.92.1    266
     192.168.92.1  255.255.255.255         On-link      192.168.92.1    266
   192.168.92.255  255.255.255.255         On-link      192.168.92.1    266
    192.168.153.0    255.255.255.0         On-link     192.168.153.1    276
    192.168.153.1  255.255.255.255         On-link     192.168.153.1    276
  192.168.153.255  255.255.255.255         On-link     192.168.153.1    276
    192.168.201.0    255.255.255.0         On-link     192.168.201.1    276
    192.168.201.1  255.255.255.255         On-link     192.168.201.1    276
  192.168.201.255  255.255.255.255         On-link     192.168.201.1    276
    192.168.220.0    255.255.255.0         On-link     192.168.220.2    266
    192.168.220.2  255.255.255.255         On-link     192.168.220.2    266
  192.168.220.255  255.255.255.255         On-link     192.168.220.2    266
        224.0.0.0        240.0.0.0         On-link         127.0.0.1    306
        224.0.0.0        240.0.0.0         On-link       192.168.1.9    281
        224.0.0.0        240.0.0.0         On-link     192.168.220.2    266
        224.0.0.0        240.0.0.0         On-link      192.168.92.1    266
        224.0.0.0        240.0.0.0         On-link     192.168.153.1    276
        224.0.0.0        240.0.0.0         On-link     192.168.201.1    276
  255.255.255.255  255.255.255.255         On-link         127.0.0.1    306
  255.255.255.255  255.255.255.255         On-link       192.168.1.9    281
  255.255.255.255  255.255.255.255         On-link     192.168.220.2    266
  255.255.255.255  255.255.255.255         On-link      192.168.92.1    266
  255.255.255.255  255.255.255.255         On-link     192.168.153.1    276
  255.255.255.255  255.255.255.255         On-link     192.168.201.1    276
===========================================================================
Постоянные маршруты:
  Отсутствует

IPv6 таблица маршрута
===========================================================================
Активные маршруты:
 Метрика   Сетевой адрес            Шлюз
 11    281 ::/0                     fe80::1
  1    306 ::1/128                  On-link
 11    281 fe80::/64                On-link
 20    266 fe80::/64                On-link
 19    266 fe80::/64                On-link
 23    276 fe80::/64                On-link
 22    276 fe80::/64                On-link
 23    276 fe80::c80:21d7:feb:85e5/128
                                    On-link
 11    281 fe80::3cda:52c7:8669:4bd5/128
                                    On-link
 22    276 fe80::4903:edb2:f654:caf6/128
                                    On-link
 19    266 fe80::5d1e:8371:fa09:7b27/128
                                    On-link
 20    266 fe80::70a0:f6f0:55f6:5f1e/128
                                    On-link
  1    306 ff00::/8                 On-link
 11    281 ff00::/8                 On-link
 20    266 ff00::/8                 On-link
 19    266 ff00::/8                 On-link
 23    276 ff00::/8                 On-link
 22    276 ff00::/8                 On-link
===========================================================================
Постоянные маршруты:
  Отсутствует
```

**Comment by lgg** [comment]
@trevj tried to install v1.2.12 and got this: 
![image](https://user-images.githubusercontent.com/12018713/45924120-47c81400-bf00-11e8-9c0a-ccf2a399aba8.png)

Outline Client is installed, but still can't connect. Sent report with title 'Github Issue 251'.

**Comment by trevj** [comment]
@birdmoney11 I think you're experiencing PATH issues like the one in https://github.com/Jigsaw-Code/outline-client/issues/278. That user also had Kaspersky installed, I wonder if it modifies the PATH by default.

**Comment by trevj** [comment]
@lgg Wow, let's continue discussion on https://github.com/Jigsaw-Code/outline-client/issues/291 :-)

**Comment by trevj** [comment]
So, as of 1.2.12 "not able to configure routing tables" occurs when one of:
- there is an error communicating with OutlineService
- `OutlineService` cannot be restarted
- OutlineService does not understand the routing table (with the exception of https://github.com/Jigsaw-Code/outline-client/issues/262) **or** there is some error, e.g. the PATH issue described in https://github.com/Jigsaw-Code/outline-client/issues/278

@birdmoney11 Seems like your original issue is that described at https://github.com/Jigsaw-Code/outline-client/issues/278

@YoulianBoshi Please try the latest version and let me know if you still experience issues.

@yywudi I guess your issue is covered by https://github.com/Jigsaw-Code/outline-client/issues/291.

@OneSecure If you restart OutlineService (or simply reboot your VM) does Outline then connect?

**Comment by trevj** [comment]
I just released https://github.com/Jigsaw-Code/outline-client/releases/tag/windows-v1.2.14 which improves the TAP device creation on systems not running in English. It should further help reduce the frequency of this error message. @YoulianBoshi and @OneSecure please do let me know if it doesn't help and we can re-open this or create more specific issues.

**Comment by OneSecure** [comment]
@trevj please email me privately.
