### ISSUE TITLE
Suggestion: add option for windows - to create adapter or set proxy up.

### ISSUE THREAD

**Issue by OlegShatin** [Jigsaw-Code/outline-client#252]
After last update, I found all my traffic goes through VPN net adapter. I'm using SwitchyOmega chrome extenesion to select which resourses I want to see trough proxy and which I want to see directly. It works perfect withc socks5 proxy, but not with net adapter. Thank you for adding adapter feature, but I suppose that my case is not unique. I think it would be better to leave option to user, to choose the kind of proxy he need.

**Comment by studentmain** [comment]
Use shadowsocks-windows

**Comment by OlegShatin** [comment]
Of course I could use third-party tool, but I suppose, if Outline already had some functionality, there is no reason to migrate somewhere else.

**Comment by trevj** [comment]
@OlegShatin Thanks for trying Outline. I'm afraid our hope with the new Windows client is that tools for very advanced users like SwitchyOmega wouldn't be necessary - just like on Android and iOS/macOS where Outline alone is sufficient to configure your system.

**Comment by OlegShatin** [comment]
@trevj at least, could you provide please the last stable client for windows with socks proxy and without adapter? No idea, how to find it. )

**Comment by trevj** [comment]
@OlegShatin Sorry for being so terse! If you want to install the previous client, here's a download link (but I'm afraid the auto-update will auto-upgrade you - so it's not a great solution):
https://github.com/Jigsaw-Code/outline-client/releases/tag/windows-v1.0.4
