### ISSUE TITLE
Module compiled with Swift 4.0.3 cannot be imported in Swift 4.1.2

### ISSUE THREAD

**Issue by armnotstrong** [Jigsaw-Code/outline-client#257]
ios build with Xcode 9.4.1 (9F2000)

![wx20180907-115721](https://user-images.githubusercontent.com/3839691/45197714-4dcdbc00-b295-11e8-8fb2-20570a5e3453.png)

**Comment by trevj** [comment]
@armnotstrong Thanks for trying Outline.

@alalamav IIRC we only test with XCode 9.3?

**Comment by alalamav** [comment]
> IRC we only test with XCode 9.3?

Yes. We are due an update to Swift 4.1 in our dependencies before we are able to use Xcode >9.3.

**Comment by trevj** [comment]
Thanks @alalamav. @armnotstrong: I'm afraid you'll have to use an older version of Xcode for now.

**Comment by yssmile** [comment]
try this http://www.code4app.com/home.php?mod=space&uid=817043&do=blog&id=3136)

**Comment by trevj** [comment]
Closing for now. @armnotstrong Good luck with Outline development, please feel free to ask more questions.
