### ISSUE TITLE
windows client: too many "another VPN is active" false positives

### ISSUE THREAD

**Issue by mookrhodan** [Jigsaw-Code/outline-client#262]
- still shows same error "It seems like another VPN is active"
- uninstall still does not remove Outline's tap - adapter nor does it remove VPN server settings from computer during uninstall...

Win10 enterprise latest updates, normally use Cisco AnyConnect for VPN connection (so it is installed on my computer)

**Comment by seanxushen** [comment]
Same problem here with 1.2.8 and 1.2.10. Previous Tap client works (eg 1.1.2 ?)

**Comment by mookrhodan** [comment]
Indeed, v 1.1.2 was the ONLY version that ever worked as intended on my PC.... All other versions, though the app actually confirmed to have established a secure connection, failed to do so - again easily tested for browser traffic via any website that shows one's external IP address....

**Comment by trevj** [comment]
@mookrhodan Thanks for trying Outline. Sorry you've been having trouble with the new Windows client. Can you please paste the output of `route print`? That will help me see why Outline cannot connect.

BTW, yes, you're right the uninstaller does not remove the TAP device (it is possible to do it manually) but can you clarify what you mean by "nor does it remove VPN server settings from computer during uninstall"?

**Comment by trevj** [comment]
@seanxushen FYI, 1.1.2 did not include the TAP driver. Again, if you can paste the output of `route print` it will help us see what's going wrong.

**Comment by mookrhodan** [comment]
@trevj 
- I do not understand why you ask for such information to be shared in a public forum.... 
- i uninstalled v1.2.10 and installed new version v1.2.11 and it seems to work now.. at least browser traffic seems to be tunneled now as verified with external IP confirmation
- I am using the ss server of a 3rd party, the connection info should be removed completely when uninstalling the Outline client!
- why is the TAP device not removed during de-installation? all other providers of application specific (named) TAP devices remove them as well during de-installation
- I would appreciate if you gave it some thought as to where this application might be in use and why I am wondering about this.....!

**Comment by xDrixxyz** [comment]
I'm also having this issue, [here's the output of my `route print`](https://xdrixxyz.page.link/SYdU) (I uploaded it to my google cloud storage bucket because it seemed too big to copy/paste into here).

I don't have any other VPN software installed, only Outline. This has been happening even with the v1.2.11 Windows pre-release. I'm on Windows 10 Home, 64-bit if that helps.

**Comment by trevj** [comment]
@xDrixxyz Thanks for the report. I can see you have VMWare installed. We have not tested cooperation with virtualisation/emulation software extensively.

One question for now:
- did you see an error while installing Outline?

**Comment by trevj** [comment]
@mookrhodan

- You can redact sensitive information such as server IPs before sharing; I assume most users are behind a firewall/router than will obscure their public IP **and** that questions on GitHub are from relatively advanced users who understand this.
- Great to hear 1.2.11 works better for you.
- Right now we don't have a good way to distinguish between uninstalls taking place as part of an update vs. a "final" uninstall.
- See previous answer (uninstalling and reinstalling the TAP device is very slow) but nevertheless this is something we really want to fix (it's possible to do so manually, via Control Panel). Is your concern leaving traces of the server on your machine, or traces that you've used Outline?
- Yes of course, understood.

BTW, if you'd prefer, there are several alternative ways to contact the team - all listed in the app.

**Comment by xDrixxyz** [comment]
@trevj Nope, Outline installed successfully and without errors.

**Comment by trevj** [comment]
@xDrixxyz OK, thanks. I'm afraid I'll need a little more info in order to debug this. Can I please ask you to submit feedback using the app?:
- open Outline
- try to connect
- from the menu, click **Submit feedback**
- include some way to identify you, e.g. Github username (we don't need an email)

This sends us a little more info on your network devices than is contained in `route print`.

Thanks again!

**Comment by trevj** [comment]
@xDrixxyz Many thanks. This tells me the error isn't, in fact, related to VMWare. Instead, you have multiple network devices with gateways. I'm still not sure how that happens but I'm going to prioritise a fix that guesses which one is "really" active by examining the device metric.

**Comment by trevj** [comment]
@mookrhodan @xDrixxyz I just merged https://github.com/Jigsaw-Code/outline-client/pull/281 which I think will help reduce unnecessary "another VPN is active" error messages. It will be in https://github.com/Jigsaw-Code/outline-client/releases/tag/windows-v1.2.12 which should go live later today. Many thanks again for helping us improve this tricky part of Outline.

**Comment by wkwalker** [comment]
It seems v1.2.13 has the same problem. I'm continuing to see the "another VPN is active" error. Win10 Pro system; WiTopia client installed, but not active.

**Comment by trevj** [comment]
So, as of 1.2.12 "another vpn is active" only occurs when there is >1 network device with an IPv4 gateway (in 1.2.11 and earlier, this message would **also** occur if >1 device had an IPv6 gateway). I see one remaining improvement: when we do find multiple network devices with an IPv4 gateway, choose the one with the lowest metric.

@seanxushen @xDrixxyz Please try connecting with 1.2.12. It may address your issue.

@wkwalker Sorry you're having problems with Outline. If you could please follow the steps above to send us detailed info on your system's network devices then I may be able to tell whether the remaining improvement I mentioned earlier will help you:
https://github.com/Jigsaw-Code/outline-client/issues/262#issuecomment-422172358

**Comment by xDrixxyz** [comment]
Yes, I can successfully connect to my Outline Server now. Thank you @trevj !

**Comment by trevj** [comment]
@xDrixxyz Delighted to hear it!

**Comment by NoobTW** [comment]
Same problem here. v1.2.26, Windows 10 1903 build 18329.1.

**Comment by wkwalker** [comment]
I've continued to have the same issue since after 1.1.2 and it is still occurring with 1.2.26. Windows 10, 1803, build 17134.523.

FWIW, I have the WiTopia VPN package installed, but not active.

**Comment by trevj** [comment]
@mookrhodan @seanxushen @xDrixxyz @wkwalker @NoobTW I just released Windows client 1.2.29 which should help with this issue. If you still run into problems after updating please re-open. Thanks for reporting this issue!
