### ISSUE TITLE
Settings -> VPN -> Close，Not Close VPN

### ISSUE THREAD

**Issue by ShuailongWang** [Jigsaw-Code/outline-client#263]
iPhone 6s, After the connection is successful, I go to: Settings -> VPN -> Close,
Here is the ability to close the VPN，
I want to know how to close here.

**Comment by alalamav** [comment]
Hi @ShuailongWang, thanks for the feedback. The Outline iOS client uses the On Demand VPN feature to automatically connect the VPN on startup if it was connected when the device shut down. This means that the VPN cannot be connected or disconnected through the Settings app. Please use the app to manage VPN connections.

As a workaround, you can disable the On Demand option in the Outline VPN configuration. This should disconnect the VPN. Please feel free to re-open if you have any questions.

**Comment by ShuailongWang** [comment]
Thank you.
