### ISSUE TITLE
Look into calling setUnderlyingNetworks

### ISSUE THREAD

**Issue by bemasc** [Jigsaw-Code/outline-client#265]
It looks like this isn't causing a problem for Outline, but it still might be worth calling `setUnderlyingNetworks` in the `VpnService` just for maximum correctness.

**Comment by trevj** [comment]
Cool find. Does this fix, for example, the issue whereby apps set to use only wifi may shun the VPN?:
https://www.valuewalk.com/2018/05/wifi-and-vpn-issue-oreo-8-1-android-p/

**Comment by bemasc** [comment]
Yes, that's the idea.  The exact behavior depends on the Android version, and indeed this doesn't seem to work quite right in 8.1, but it does help in some versions, especially 9.
