### ISSUE TITLE
[Windows] Cannot connect with the shadowsocks server that diable UDP support

### ISSUE THREAD

**Issue by yulahuyed** [Jigsaw-Code/outline-client#272]

**Comment by trevj** [comment]
@yulahuyed Thanks for trying Outline - sorry for the slow reply.

I'm afraid you've run into the side-effect of our new "full system" VPN support on Windows - previously, Windows was the only platform on which Outline did *not* require UDP support.

Can you enable UDP support on your server? It's just a matter of adding the `-u` command-line switch. If you cannot do that then I'm sorry but please note we are actively working to make *all* our client platforms support such servers.

**Comment by trevj** [comment]
@yulahuyed We've been working to support for servers without UDP forwarding enabled; it should appear in 1.2.22.

**Comment by trevj** [comment]
Let's track this in one place:
https://github.com/Jigsaw-Code/outline-client/issues/329
