### ISSUE TITLE
why “can not install app "  by itunes from my pc 

### ISSUE THREAD

**Issue by Hyvi** [Jigsaw-Code/outline-client#277]
hi,all 
after download outline.ipa file from chrome browser, and add it to my itunes,  then click 'sync' to my iphone . but when i try to open the app in my iphone.  i cannot run it the right way.  someone can help me ?

**Comment by trevj** [comment]
@Hyvi Thanks for trying Outline! I'm afraid `Outline.ipa`is only useful to very advanced users - Outline is built each night on our continuous build system and, when it's in a good state, we send that file to the Apple Store. I'm afraid you'll have to install Outline via the Apple Store.
