### ISSUE TITLE
Chrome OS client for the chromebooks that do not get Android support

### ISSUE THREAD

**Issue by kduvekot** [Jigsaw-Code/outline-client#28]
Would it be possible to provide a Chrome OS client for the chromebooks that do not get Android support?

You claim to support Chrome OS 65+ .. but for example the Acer C720p does run 65+, but does not support Android apps so it can not use your Android App to provide VPN

**Comment by bemasc** [comment]
I have a Chromebook with the same problem, so I can sympathize, but unfortunately this is very difficult. Also, all new Chromebooks come with Android app support, so this work would only be for the shrinking fraction of Chromebooks that don't support Android apps.
