### ISSUE TITLE
iOS outline client: failed to connect to server.

### ISSUE THREAD

**Issue by hongjn** [Jigsaw-Code/outline-client#282]
After upgrading to iOS 12, It can't connect to server. It has been running well before upgrading.

I am using iPhone 6s.

**Comment by trevj** [comment]
@hongjn Thanks for the report. We've tested Outline on iOS 12 and didn't see any issues - exactly what error message do you see when you try to connect?

**Comment by hongjn** [comment]
@trevj Sorry, Connected now.

**Comment by trevj** [comment]
@hongjn Great to hear it works for you.
