### ISSUE TITLE
add kcp procotol support

### ISSUE THREAD

**Issue by foxundermoon** [Jigsaw-Code/outline-client#290]
https://github.com/xtaci/kcptun

**Comment by studentmain** [comment]
https://github.com/Jigsaw-Code/outline-server/issues/177

oxundermoon <notifications@github.com> 于 2018年9月21日周五 上午3:55写道：

**Comment by trevj** [comment]
@foxundermoon Thanks for trying Outline. As @studentmain notes, we already have a discussion regarding KCP underway.
