### ISSUE TITLE
[iOS] Wi-fi disconnected when turning on Outline

### ISSUE THREAD

**Issue by lgg** [Jigsaw-Code/outline-client#296]
ios 12.0
outline app: 1.1.3

I dont want to share my personal info about Outline server and WiFi so i send video to support@getoutline.org with subject: iOS Outline Client Github Issue #296

**Comment by lgg** [comment]
btw Windows Client works fine in this WiFi network.

**Comment by mveplus** [comment]
@lgg I've just installed Outline 1.1.3 on iOS 12.0 on 6s, the same Outline ver. also on 5s with iOS 11.4.1, tested with two servers one local box Ubuntu 18.04 with port forwarded on the router DryTek 2820 WiFi (WPA2 AES personal) and one on DigitalOcean both working fine so far have not noticed any disconnections issue.
Tested also connecting to Meraki MR33 AP Guest WiFi no-encryption, with a weak signal - devices listed above no disconnections issues, so far.
It also stays constantly connected even when a device goes to sleep and after wakeup is connected to the WiFi and Outline. 
Could it be an Apple device or/and WiFi combination? If it does disconnects while testing to various WiFi AP I'd assume it's Apple Device specific?

**Comment by alalamav** [comment]
Thank you for the reports @lgg and @mveplus. I'll

**Comment by lgg** [comment]
@mveplus thank you, other WiFi networks works fine. I will check my problem network more carefully.

**Comment by lgg** [comment]
For those who faced with the same issue: I don't know what exactly helps but try this:
* reboot router
* delete and add again Outline Server config in iOS app
* reboot iOS device
