### ISSUE TITLE
Outline iOS ipa Xcode Installation Failed

### ISSUE THREAD

**Issue by kid551** [Jigsaw-Code/outline-client#297]
I downloaded `Outline.ipa` from release `daily-2018-09-25`, and try to use Xcode 10.10 to install Outline into my iPhone 6s Plus with iOS version 11.4.1. 

But I got error "**App installation failed: There was an internal API error.**" 

Does anyone know how I can solve this problem? Thanks!

**Comment by alalamav** [comment]
@kid551, thanks for trying out Outline. There are a few reasons why this may not work.

I believe the Outline.ipa daily build is not signed. Additionally, Outline only supports Xcode 9.4 at the moment. Finally, Outline requires network entitlements that can only be granted by distributing through the app store; the .ipa will only work in development devices that are whitelisted.

**Comment by kid551** [comment]
Thanks for the explanation. I got it.

**Comment by kid551** [comment]
> @kid551, thanks for trying out Outline. There are a few reasons why this may not work.
> 
> I believe the Outline.ipa daily build is not signed. Additionally, Outline only supports Xcode 9.4 at the moment. Finally, Outline requires network entitlements that can only be granted by distributing through the app store; the .ipa will only work in development devices that are whitelisted.

Thanks for the explanation. I got it.
