### ISSUE TITLE
Putty and WinSCP connection problem with outline new version

### ISSUE THREAD

**Issue by rapitsu** [Jigsaw-Code/outline-client#299]
Hi Sir
I work with putty and WinSCP everyday, they have been working well with Outline, and since I upgraded outline to 1.2.x, both putty and WinSCP connections are interrupted every 1~2 minutes.

And I switched back to 1.1.2 everything is normal again. So the server side looks good.

Would you please tell me how to to solve this problem please?

Thank you very much, Outline is a great tool, very convenient to be used as the main proxy for development, testing and access control etc.

My system aspects:
Windows 10 Home, 64bit 1803, build 17134.285
putty 0.70
WinSCP 5.11.3

Thank you very much.

**Comment by trevj** [comment]
@rapitsu Thanks for trying Outline. I think this must be related to keepalive issues, which have been brought up before:
- https://github.com/Jigsaw-Code/outline-server/issues/141
- https://github.com/Jigsaw-Code/outline-server/issues/178

I'll close this as a duplicate and continue discussion on https://github.com/Jigsaw-Code/outline-server/issues/141.

**Comment by trevj** [comment]
BTW @rapitsu what changed with Outline 1.2.x is that it establishes a "system-wide" VPN. In fact, before that your SSH client was not - unless you explicitly configured it - using the Outline connection at all.
