### ISSUE TITLE
Please add DNS over TCP!

### ISSUE THREAD

**Issue by sqwwqw5** [Jigsaw-Code/outline-client#324]
Outline works fine with cable networks but DNS queries fails while using LTE.The provider in my area seems to block the UDP protocol overseas randomly though TCP works just fine.

Appreciate all the works you've done to make outline the first and only VPN like SS-Client!

**Comment by trevj** [comment]
@sqwwqw5 Thanks for trying Outline! We've been working on support for servers without UDP and I think that will also address your issue.

**Comment by Kolahzary** [comment]
Any updates on this feature? my ISP has blocked UDP too

**Comment by alalamav** [comment]
I have been working on this feature. We'll be ready to release it soon, once we implement it on all platforms. You can follow changes on this [branch](https://github.com/Jigsaw-Code/outline-client/tree/alalama-dns-tcp-net).

**Comment by trevj** [comment]
Let's track this here:
https://github.com/Jigsaw-Code/outline-client/issues/272
