### ISSUE TITLE
Windows Client UDP Error

### ISSUE THREAD

**Issue by rmonst3r** [Jigsaw-Code/outline-client#329]
Hello,

  I have set up the server and opened both TCP and UDP ports.

iOS, OSX and Android devices can connect without issue, however on Windows 10 the following error is displayed: "It seems like this server doesn't support UDP forwarding." then the connection aborts.

Any idea on how to fix this?

**Comment by Mantains** [comment]
same issue on ios client.
![image](https://user-images.githubusercontent.com/25947164/47092979-bd52a600-d25a-11e8-9b96-a03ba0916396.png)

but my android device works well?
 and it seems like randomly happens...

**Comment by alalamav** [comment]
@rmonst3r, @Mantains thank you for the feedback. If you are certain that these servers support UDP forwarding, then the client's network may have a firewall that blocks UDP traffic to high number ports, or there may be a local firewall in your Windows machine.

Are the iOS/Android devices connecting over the same network? Could you verify the firewall settings in your machine?

We are working on a solution that would enable DNS over TCP in cases like these.

**Comment by trevj** [comment]
@rmonst3r Apologies for the slow reply. FYI, we have been working to support servers without UDP enabled. This should help in your case, although it does sound as if there is a firewall - or something else particular to your Windows machine - blocking UDP.

**Comment by rmonst3r** [comment]
Thanks Trejv

I turned off the firewall and everything that could be associated with it
but I’ll have another look.


On 6 December 2018 at 12:57:51 PM, trevj (notifications@github.com) wrote:

@rmonst3r <https://github.com/rmonst3r> Apologies for the slow reply. FYI,
we have been working to support servers without UDP enabled. This should
help in your case, although it does sound as if there is a firewall - or
something else particular to your Windows machine - blocking UDP.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Jigsaw-Code/outline-client/issues/329#issuecomment-444946528>,
or mute the thread

**Comment by trevj** [comment]
@rmonst3r @Mantains I'm going to close this due to inactivity but please note we have been working to make the client handle networks/situations where UDP is unavailable. I'm afraid it's not available for Windows just yet but please follow this thread for updates:
https://www.reddit.com/r/outlinevpn/comments/a68s0j/release_outline_beta_for_ios_and_android/

**Comment by Ronglisheng** [comment]
firewall-cmd --zone=public --permanent --add-port=8388/tcp
firewall-cmd --reload
