### ISSUE TITLE
My server doesn't work anymore after I installed Outline-client and server

### ISSUE THREAD

**Issue by patrickwai** [Jigsaw-Code/outline-client#332]
I have a Linode server which installed shadowsocks and my pc with shadowsocks client installed. 
It works very well for about one year. 

Just now I installed the outline. It works for a few minutes. And then my server does not work anymore. Also, I can not log in through ssh.

Does anyone have the same issue?

**Comment by trevj** [comment]
@patrickwai Thanks for trying Outline. Sorry you've been having trouble connecting.

Two questions:
- On which OS are you running the Outline client?
- When you say "cannot login through SSH", do you mean that you then cannot access the server at all even if you turn off all VPNs?

**Comment by patrickwai** [comment]
Hi trevj, Thank you for replying.
1. I am running the Outline client on Windows 10 and IOS
2. Yes. I can not access the server at all at the moment. It works after restarting the server. 
I think it doesn't have better performance than only ss client + ss server. 
Also, I found my ip was monitored cause internet connecting was broken when I using some applications . But I am not sure if the Outline is leaking my server ip. It happens even without the Outline installed.

**Comment by trevj** [comment]
@patrickwai You're welcome. I'm afraid i can't advise on how your internet connection may be affected - do you have other devices, e.g. mobile phone, on which you could try connecting to your server?

**Comment by patrickwai** [comment]
Hi Trevj
Now it works for me. Thank you.

trevj <notifications@github.com>于2018年10月20日 周六上午12:57写道：

**Comment by trevj** [comment]
@patrickwai Glad to hear it!
