### ISSUE TITLE
no ping respond after connecting to server

### ISSUE THREAD

**Issue by beigirad** [Jigsaw-Code/outline-client#333]
I have some problem when `Outline` connected to server.
when I run `ping 4.2.2.4`, get this response :
```
➜  ~ ping 4.2.2.4
PING 4.2.2.4 (4.2.2.4): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
çRequest timeout for icmp_seq 3
çRequest timeout for icmp_seq 4
^C
--- 4.2.2.4 ping statistics ---
6 packets transmitted, 0 packets received, 100.0% packet loss
```

What can I do for get a correct ping?

p.s: When I disconnected `Outline` I get correct ping response.

**Comment by alalamav** [comment]
Thanks for using Outline, @beigirad. This is expected - the Outline clients do not support ICMP. I'm afraid we do not have plans to support it.

**Comment by mjgs** [comment]
I'm curious about this, do none of the developers of Outline server/client actually use the software? If you do then how do you do developer stuff without using the ping command?

**Comment by trevj** [comment]
@mjgs ?

**Comment by mjgs** [comment]
@trevj I'm going to assume you are asking for more details (let me know if that's not the case). It's an honest question, I'm just interested to know how the developers of a network based software are able to develop the software without using the ping command. Do you have some other way of running ping commands?

**Comment by studentmain** [comment]
@mjgs `tcping`, `nping`, `curl`.

Yes, it's a network based software. And it's also a socks5 proxy based software. When debugging a (TCP only) proxy, you needn't use ICMP.

**Comment by mjgs** [comment]
@studentmain Thanks for the commands, and for the socks5 details, I didn't know that SOCKS5 was tcp only.

I wasn't aware of the [nping](https://linux.die.net/man/1/nping) command, looks to be quite useful with especially with multihost and multiport. This command worked (without needing root privileges):

```
nping -c 1 --tcp-connect -p 80 google.com
```

I couldn't find tcping, it's not installed on osx, and the [link returned](http://linuxco.de/tcping/tcping.html) by brew info doesn't load. Couldn't find a project homepage or man pages either. Where do I find it?

**Comment by trevj** [comment]
@mjgs `ping` has never been an issue - BTW, we do use Outline ourselves, all the time.

**Comment by mjgs** [comment]
@trevj Easy for you to say, you knew about nping and tcping! :) Seriously though it's good to know that other devs are using Outline.

**Comment by mjgs** [comment]
@trevj Easy for you to say, you knew about nping and tcping! :) Seriously though it's good to know that other devs are using Outline.
