### ISSUE TITLE
windows client: delay before netsh can configure TAP device

### ISSUE THREAD

**Issue by kouhi** [Jigsaw-Code/outline-client#338]
Hi Outline team:

On behalf of our users, we have been getting consistent support requests for Outline windows client. 

One of our users cannot connect to Outline at all. Here is what they get. The user updated to the latest version 1.2.17

![image](https://user-images.githubusercontent.com/15640491/47161678-6ac0ca80-d2ea-11e8-8a8a-5b9dec0bd2af.png)

Here is the list of network interfaces after installing Outine from `route print`.
<img width="561" alt="screen shot 2018-10-18 at 3 46 07 pm" src="https://user-images.githubusercontent.com/15640491/47163037-123efc80-d2ed-11e8-9503-9d18078f5847.png">

I asked the user to submit feedback multiple times. Please let me know if you require us to send another one.
 
Please let me know if there are any other information that could help with debugging.

**Comment by trevj** [comment]
@kouhi Thanks for the report - sorry you've been having trouble with Outline on Windows.

I don't see Outline's TAP device in that list. Did your user see an error message when they installed Outline? It should have, if the TAP device could not be installed.

**Comment by trevj** [comment]
@kouhi We're aware of some issues with the TAP device driver on certain systems for which we don't yet know the cause. However, since I see several TAP devices on your user's system I strongly suspect this is instead an issue with our installer. I'm afraid there are some bugs with our error reporting in certain situations - I suspect this is happening here.

However, we may be able to debug manually. It would help us a lot if your user could:
* open a command prompt
* run this script: c:\program files (x86)\outline\add_tap_device.bat
* send me the output

I'm afraid I don't have access to my Windows box today so those paths may not be **exactly** right but if you can forward that debugging information, we may be able to figure out what's happening here.

Many thanks again!

**Comment by trevj** [comment]
@lgg Many thanks for trying 1.2.17 and for the detailed report. The script cannot set the subnet on the new device - usually this is because some other device is already using that subnet. Is that the case here? (renaming an old outline-tap0 device and re-running this script will cause this)

**Comment by lgg** [comment]
@trevj no, tap-adapter from previous installations was deleted through Device Manager

**Comment by lgg** [comment]
hmm it's very strange:
```
c:\Program Files (x86)\Outline>netsh interface ip set address %DEVICE_NAME% static 10.0.85.2 255.255.255.0
Элемент не найден.



c:\Program Files (x86)\Outline>echo %DEVICE_NAME%
outline-tap0

c:\Program Files (x86)\Outline>echo %DEVICE_NAME%
outline-tap0

c:\Program Files (x86)\Outline>netsh interface ip set address %DEVICE_NAME% static 10.0.85.2 255.255.255.0
Элемент не найден.



c:\Program Files (x86)\Outline>netsh interface ip set address "outline-tap0" static 10.0.85.2 255.255.255.0
Элемент не найден.



c:\Program Files (x86)\Outline>netsh interface ip set address 'outline-tap0' static 10.0.85.2 255.255.255.0
Синтаксическая ошибка в имени файла, имени папки или метке тома.



c:\Program Files (x86)\Outline>netsh interface ip set address "outline-tap0" static 10.0.85.2 255.255.255.0


c:\Program Files (x86)\Outline>netsh interface ip set address "outline-tap0" static 10.0.85.2 255.255.255.0

c:\Program Files (x86)\Outline>
```

**Comment by lgg** [comment]
Yep, there is a countdown about 1 minute between newly created Tap adapter would become available in netsh list
```
c:\Program Files (x86)\Outline>netsh interface ip show interfaces

Инд     Мет         MTU          Состояние               Имя
---  ----------  ----------  ------------  ---------------------------
  1          50  4294967295  connected     Loopback Pseudo-Interface 1
 11          25        1500  connected     Беспроводное сетевое соединение
 17           5        1500  disconnected  Подключение по локальной сети
 16           5        1500  disconnected  Беспроводное сетевое соединение 2
 19          10        1500  connected     VirtualBox Host-Only Network
 33          10        1500  disconnected  Беспроводное сетевое соединение 2
 20          10        1500  connected     VirtualBox Host-Only Network #2
 21          20        1500  connected     VMware Network Adapter VMnet1
 22          20        1500  connected     VMware Network Adapter VMnet8


c:\Program Files (x86)\Outline>netsh interface ip show interfaces

Инд     Мет         MTU          Состояние               Имя
---  ----------  ----------  ------------  ---------------------------
  1          50  4294967295  connected     Loopback Pseudo-Interface 1
 11          25        1500  connected     Беспроводное сетевое соединение
 17           5        1500  disconnected  Подключение по локальной сети
 16           5        1500  disconnected  Беспроводное сетевое соединение 2
 57          20        1500  disconnected  outline-tap0
 19          10        1500  connected     VirtualBox Host-Only Network
 33          10        1500  disconnected  Беспроводное сетевое соединение 2
 20          10        1500  connected     VirtualBox Host-Only Network #2
 21          20        1500  connected     VMware Network Adapter VMnet1
 22          20        1500  connected     VMware Network Adapter VMnet8
```

**Comment by lgg** [comment]
Strange that `netsh interface show interface name=%DEVICE_NAME%` works fine right after adding TAP adapter, but `netsh interface ip show interfaces` and `netsh interface ip set address %DEVICE_NAME% static 10.0.85.2 255.255.255.0` doesn't see TAP adapter

**Comment by ssrlive** [comment]
Hi @trevj @alalamav , I have rewrite outlineService with pure C. now it's runing fine in Win7 basic version.

[OutlineService.zip](https://github.com/Jigsaw-Code/outline-client/files/2499100/OutlineService.zip)

**Comment by dsk9** [comment]
I have this problem. how to fix?

**Comment by lgg** [comment]
@dsk9 you have few options:
1. Check this PR https://github.com/Jigsaw-Code/outline-client/pull/340 and manually add and config TAP adapter using code from that PR.
2. Wait until that PR will be accepted. 
3. User previous release of Outline-Client for installation and then update it.

**Comment by lgg** [comment]
@dsk9 what does browser show instead of Youtube/Facebook? In which country your Outline-Server is located?

**Comment by dsk9** [comment]
set dns in outine_tap0 google. now work but slow .
what defult outline dns?

**Comment by lgg** [comment]
@dsk9 as I now for now - default DNS is your default tcp/v4 DNS.

**Comment by gokokusan** [comment]
I also meet  this question。   the last version still
 not work. why!       on the other it works.

**Comment by trevj** [comment]
@lgg Thanks again for the detailed report and fix. With https://github.com/Jigsaw-Code/outline-client/pull/387 (and https://github.com/Jigsaw-Code/outline-client/pull/392) I think this issue will be resolved.

**Comment by lgg** [comment]
@trevj unfortunately this issue isn't fixed ;(

I just tried to install windows-v1.2.20 on win7 from scratch. Still failing on `Could not set TAP network device subnet.`

`./add_tap_device.bat amd64`
```
Storing current network device list...
NetConnectionID
▒▒▒▒▒▒祭▒▒ ▒▒ ▒▒▒▒▒쭮▒ ▒▒
▒▒▒஢▒▒▒▒▒ ▒⥢▒▒ ᮥ▒▒▒▒▒▒▒
▒▒▒஢▒▒▒▒▒ ▒⥢▒▒ ᮥ▒▒▒▒▒▒▒ 2
VirtualBox Host-Only Network
VirtualBox Host-Only Network #2
VMware Network Adapter VMnet1
VMware Network Adapter VMnet8
Creating TAP network device...
Device node created. Install is complete when drivers are installed...
Updating drivers for tap0901 from C:\Program Files (x86)\Outline\tap-windows6\OemVista.inf.
Drivers installed successfully.
Storing new network device list...
NetConnectionID
▒▒▒▒▒▒祭▒▒ ▒▒ ▒▒▒▒▒쭮▒ ▒▒
▒▒▒஢▒▒▒▒▒ ▒⥢▒▒ ᮥ▒▒▒▒▒▒▒
▒▒▒஢▒▒▒▒▒ ▒⥢▒▒ ᮥ▒▒▒▒▒▒▒ 2
▒▒▒▒▒▒祭▒▒ ▒▒ ▒▒▒▒▒쭮▒ ▒▒ 5
VirtualBox Host-Only Network
VirtualBox Host-Only Network #2
VMware Network Adapter VMnet1
VMware Network Adapter VMnet8
Searching for new TAP network device name...
New TAP device name: ▒▒▒▒▒▒祭▒▒ ▒▒ ▒▒▒▒▒쭮▒ ▒▒ 5

Testing that the new TAP network device is visible to netsh...
Configuring new TAP network device...
▒▒▒▒▒▒▒ ▒▒ ▒▒▒▒▒▒.


Could not set TAP network device subnet.
```

**Comment by lgg** [comment]
hmm, it's Windows magic :D

@trevj you missed this https://github.com/Jigsaw-Code/outline-client/issues/338#issuecomment-431540626

so current check https://github.com/Jigsaw-Code/outline-client/blob/da7e9824db797f5f331d41dffca74d5273f81790/src/electron/add_tap_device.bat#L94

doesnt work properly, so it always goes to `:configure`

**Comment by lgg** [comment]
Also:
```
@echo off
netsh interface ip show interfaces | find "Loopback Pseudo-Interface 1"
echo ErrorLevel: %errorlevel%

netsh interface ip show interfaces | find "outline-tap0"
echo ErrorLevel: %errorlevel%
```
output:
```
C:\Program Files (x86)\Outline>test.bat
  1          50  4294967295  connected     Loopback Pseudo-Interface 1
ErrorLevel: 0
ErrorLevel: 1
```

**Comment by lgg** [comment]
So this code:
```
:: We've occasionally seen delays before netsh will "see" the new device, at least for
:: purposes of configuring IP and DNS ("netsh interface show interface name=xxx" does not
:: seem to be affected).
echo Testing that the new TAP network device is visible to netsh...
netsh interface ip show interfaces | find "%DEVICE_NAME%" >nul
if %errorlevel% equ 0 goto :configure

:loop
echo waiting...
timeout /t 1 >nul
netsh interface ip show interfaces | find "%DEVICE_NAME%" >nul
if %errorlevel% equ 1 goto :loop

:configure
echo Configuring new TAP network device...
```
I convinced that we need to increase timeout

<details>
<summary>Check this</summary>
<p>
New TAP device name: Подключение по локальной сети 5

Testing that the new TAP network device is visible to netsh...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
Configuring new TAP network device...

Служба не запущена. // Service not running


Could not configure TAP device primary DNS.
</p>
</details>

**Comment by lgg** [comment]
Ok, for now we have `Could not configure TAP device primary DNS.` error ;) 
but it's a progress!

**Comment by lgg** [comment]
@tedzhu it's not released yet. You can try to manually configure TAP adapter.
1. Install Outline from release version.
2. Go to device manager - delete TAP adapter there.
3. Open cmd
4. Go to `C:\Program Files (x86)\Outline` and manually run `add_tap_device.bat`
5. Then use Outline Client.

**Comment by ilinbxu** [comment]
I had the same problem, and an error was reported during installation. I tried to run add_tap_device.bat, and the same error

C:\Program Files (x86)\Outline>add_tap_device.bat
Creating TAP network device...
tapinstall failed.
Could not create TAP network device.
