### ISSUE TITLE
Why my outlineclient works on AndroidPhone well,but it's not work on Windows10?

### ISSUE THREAD

**Issue by Edward7Zhang** [Jigsaw-Code/outline-client#34]
Why my outlineclient works on AndroidPhone well,
but it's not work on Windows10?
On Windows10 it's just show connected,but IP not change.
(I use School Network PPPOE)

**Comment by trevj** [comment]
@Edward7Zhang Thanks for your report. Happy to hear Outline is working on your phone. For Windows, can I ask which browser you're using to check the IP?

**Comment by Edward7Zhang** [comment]
Chrome(Latest version)

**Comment by scor4er** [comment]
I have the same situation, do I need to do anything else besides pressing "Connect" on my Outline Client?

**Comment by trevj** [comment]
@Edward7Zhang Did you ever have success getting connected on Windows? We are rolling out a new version of Outline for Windows which sets a VPN for the entire system and may help with your problem.
