### ISSUE TITLE
windows client: Internet Connection Problem related to TAP and outline

### ISSUE THREAD

**Issue by mataqvazadeh** [Jigsaw-Code/outline-client#366]
Last week, Suddenly my laptop didn't connect to Internet, the problem was related to DNS. And it was wonderful because the problem was between only my laptop (window 7) and my router. my laptop could connect to my phone's hot-spot and other devices could connect to WiFi and internet correctly.

After googling a lot, finally I reset my tcp/ip by this command:
`netsh int ip reset`

After reseting, Ouline could not connect and showed 'Unexpected Error ...'. I had searched in issues and found the problem is related to TAP, so I deleted and inatlled tap again.

Every thing was OK but after restart windows, the internet connection problem occurred again.

I think it's related to new version of Outline. 

Best Regards

**Comment by lgg** [comment]
@mataqvazadeh try this:
- reboot laptop
- internet not working
- disconnect from wifi
- close outline
- connect to wifi
- internet works fine?

I think I might faced this issue too.

**Comment by mataqvazadeh** [comment]
@lgg I ran Outline from command prompt in windows.

**Comment by gaotongsh** [comment]
My friend is having the exact same issue when connecting to my server last week. Hope someone could share insight of how this happened.

**Comment by trevj** [comment]
@mataqvazadeh Thanks for the report - sorry you've been having trouble connecting with Outline. It looks like your laptop has problems connecting to your wifi router. Two questions for now:
- was this the case before you installed Outline?
- does Outline work when your laptop is using your phone's hotspot?

**Comment by mataqvazadeh** [comment]
@trevj 
Thanks, No Problem. There is no software without bugs.
Actually my laptop connects to router but the problem is internet connection. I can access router settings but I can't access any website. When I run Windows Troubleshooter , I get this message:

![diagnostics](https://user-images.githubusercontent.com/8982050/48091443-f315f980-e21e-11e8-9593-933566c88c73.jpg)

And answering to your questions:

- Absolutely not.  This problem occurred after updating Outline to new version (1.2.17)

- I tried using outline with my phone's hot spot, and after restarting windows problem occurred again with my hot spot connection. same scenario. But this time I got this message from windows troubleshooter:

![diagnostics hotspot](https://user-images.githubusercontent.com/8982050/48091719-b7c7fa80-e21f-11e8-9d60-f8c14b736e16.jpg)

Best Regards

**Comment by mataqvazadeh** [comment]
@saeedghod Thanks. Yeah, Accidentally I found this solution last night.

**Comment by ppryamikov** [comment]
I have the same problem on two of my PCs with Windows 10. There's no internet connection after each reboot. Uninstalling the actual network adapter and than scanning for hardware changes helps. Uninstalling Outline doesn't. So there's no proof, but I think it's related to Outline too.

**Comment by saeedghod** [comment]
> 
> 
> I have the same problem on two of my PCs with Windows 10. There's no internet connection after each reboot. Uninstalling the actual network adapter and than scanning for hardware changes helps. Uninstalling Outline doesn't. So there's no proof, but I think it's related to Outline too.

this is definitely related to Outline. because if you disconnect and close Outline before restart or shut down your PC there will be no internet connection problem.

**Comment by Flawks** [comment]
@saeedghod actually, the solution "close/disconnect outline client before shut down the OS" doesn't work fine, as I noticed the same Internet Connection Problem after rebooting PC with Outline being disconnected. Driver re-installation didn't help so I solved this issue with System restore. 
There is Wi-Fi adapter on my PC (Windows 7, x64), so I decided to replay same scenario on VirtualBox Windows 7: 

* installed Outline client
* connected to server 
* disconnected from server
* shut virtual Windows
* run it again (internet works fine)
* shut it down with disconnected Outline
* left it turned off for several days

After several days I ran virtual Windows 7 and it showed Internet Connection Problem. 
`netsh int ip reset` was the only way I found to solve it (thanks, @mataqvazadeh).

**Comment by gisha** [comment]
There is defnetly some problem with outline application. Firstly I thought that it is connected with hamachi adapter that was conflicting with outline adapter in some way. After deleting hamachi adapter I had my Internet connection going, but then again this error occured without hamachi. It really looks like it appears after turn on/trun off or after I wake pc from sleep mode.

**Comment by lgg** [comment]
Hi, I just tried to install Outline-Client from scratch on Win7. Got error:

Run as Administrator:
![image](https://user-images.githubusercontent.com/12018713/49333714-c4e4c900-f5d4-11e8-9a7e-a3634e53059a.png)

**Comment by trevj** [comment]
@mataqvazadeh @gaotongsh @ppryamikov @jandornig @gisha Thanks for the reports and apologies for any inconvenience this may have caused.

@lgg @saeedghod @Flawks Many thanks for the helpful workarounds.

I believe this is related to how Outline creates *persistent* routes on the system. We originally made these routes persistent to properly handle sleep and suspend but it seems that's no longer necessary - without persistent routes, rebooting your system should always return it to a useable state.

Fix here and should appear in the next release sometime next week:
https://github.com/Jigsaw-Code/outline-client/pull/430

**Comment by trevj** [comment]
This was released in:
https://github.com/Jigsaw-Code/outline-client/releases/tag/windows-v1.2.23
