### ISSUE TITLE
The provided path  is not a valid browser project.

### ISSUE THREAD

**Issue by rc452860** [Jigsaw-Code/outline-client#367]
$ yarn gulp build --platform=browser --watch
yarn run v1.9.4
$ D:\work\outline-client\node_modules\.bin\gulp build --platform=browser --watch
[13:53:27] Using gulpfile D:\work\outline-client\gulpfile.js
[13:53:27] Starting 'build'...
[13:53:27] Building for platform browser...
[13:53:33] The following dependencies were modified, rebuilding...
      D:\work\outline-client\www\model\errors.js,D:\work\outline-client\www\app\clipboard.js,D:\work\outline-client\www\model\events.js,D:\work\outline-client\www\app\environment.js,D:\work\outline-client\www\app\error_reporter.js,D:\work\outline-client\www\app\persistent_server.js,D:\work\outline-client\www\app\settings.js,D:\work\outline-client\www\app\updater.js,D:\work\outline-client\www\app\url_interceptor.js,D:\work\outline-client\www\app\app.js,D:\work\outline-client\www\app\fake_connection.js,D:\work\outline-client\www\app\main.js,D:\work\outline-client\www\app\outline_server.js,D:\work\outline-client\www\app\cordova_main.js
[13:53:33] Running browserify
[13:53:33] Rebuilt
++ git rev-parse --show-toplevel
+ export ROOT_DIR=D:/work/outline-client
+ ROOT_DIR=D:/work/outline-client
+ export BUILD_DIR=D:/work/outline-client/build
+ BUILD_DIR=D:/work/outline-client/build
+ export -f do_action
+ do_action src/www/build
+ local action=src/www/build
+ echo '[Running src/www/build]'
+ shift
+ D:/work/outline-client/src/www/build_action.sh
+ tsc -p src/www
+ rsync -ac --exclude '*.ts' src/www/ www/
+ echo '[Done src/www/build]'
[13:53:33] Running browserify
[13:53:33] Finished 'build' after 6.23 s
[13:53:34] Browserify: 796481 bytes written (1.20 seconds)
[13:53:35] Browserify: 796481 bytes written (2.20 seconds)
[13:53:35] Running test -d platforms/browser || cordova platform add browser
[13:53:35] Running cordova prepare browser

You have been opted out of telemetry. To change this, run: cordova telemetry on.
Error: The provided path "D:\work\outline-client\platforms\browser" is not a valid browser project.
[13:53:36] Running cp -v node_modules/babel-polyfill/dist/polyfill.min.js platforms/browser/www/babel-polyfill.min.js
[13:53:36] Running sh scripts/environment_json.sh -p browser  > platforms/browser/www/environment.json
[13:53:36] Transpiling Bower components
'node_modules/babel-polyfill/dist/polyfill.min.js' -> 'platforms/browser/www/babel-polyfill.min.js'
[13:53:37] Copied Babel polyfill.
[13:53:39] Wrote platforms/browser/www/environment.json
[13:53:50] Transpiling UI components
[13:53:51] Generating RTL CSS
[13:53:51] Running :
[13:53:51] Running cordova compile browser   --

You have been opted out of telemetry. To change this, run: cordova telemetry on.
Error: The provided path "D:\work\outline-client\platforms\browser" is not a valid browser project.
[13:53:51] Running...
[13:53:51] Running cordova run browser --noprepare --nobuild

You have been opted out of telemetry. To change this, run: cordova telemetry on.
Error: The provided path "D:\work\outline-client\platforms\browser" is not a valid browser project.

**Comment by rc452860** [comment]
I upgrade node and yarn then everything is ok.

**Comment by trevj** [comment]
@rc452860 Good to hear you got it working!

**Comment by joeytwiddle** [comment]
This happens here, about once a week. (Using latest node and latest yarn.)

What seems to fix it for us is:
```
yarn clean && yarn install
```

Followed of course by a build:
```
yarn gulp build --platform=browser
```

**Comment by trevj** [comment]
@joeytwiddle Right, I find I have to clean and re-run `yarn install` regularly - that's Node.js, I guess :-)

**Comment by joeytwiddle** [comment]
One thing we think causes this is if we try to do a clean and a fresh build, but something _other_ than the build is writing into the `platform` folder. (For example, if we have left a `tsc --watch` running for faster re-bundling.)

In that case, the build process sees that the folder `platforms/browser` exists, so it doesn't do the "Adding browser project..." part, and so the `platforms/browser` doesn't get properly initialised, resulting in "not a valid browser project".

For that reason, it is important to stop all build processes, when trying to do a clean build.

**Comment by trevj** [comment]
@joeytwiddle Good to know, thanks. I don't use `--watch` much myself precisely because of things like this but it sure makes life easier when it works.
