### ISSUE TITLE
The @ symbol in the password will report an error

### ISSUE THREAD

**Issue by whg517** [Jigsaw-Code/outline-client#372]
The password contains the @ symbol, USES the shadowsocks-windows generated server configuration, and imports it on the android phone, indicating that the configuration access key is invalid.

The android client is downloaded from shadowsocks.org.

https://github.com/Jigsaw-Code/outline-releases/blob/master/client/Outline.apk?raw=true

**Comment by joeytwiddle** [comment]
Can confirm this bug. The [example on shadowsocks.org](https://shadowsocks.org/en/config/quick-guide.html) suggests that `@` is valid inside a password, even unescaped in the URI:

```
ss://bf-cfb:test/!@#:@192.168.100.1:8888
```

Therefore I think we should extract everything before the _last_ `@`, to separate the method+password from the host+port.

In `shadowsocks_config.ts` we could change:
```diff
- const atSignIndex = b64DecodedData.indexOf('@');
+ const atSignIndex = b64DecodedData.lastIndexOf('@');
```

Presumably that would fix it.

**Comment by alalamav** [comment]
@whg517, thanks for reporting this issue. 
@joeytwiddle, the fix looks reasonable to me - would you be amenable to making the change in [outline-shadowsocksconfig](https://github.com/Jigsaw-Code/outline-shadowsocksconfig/)?

**Comment by joeytwiddle** [comment]
Fixed by that merge. Can be closed!

**Comment by trevj** [comment]
@joeytwiddle Apologies, we never updated the dependency lists to pull in this fix.

I just created this release:
https://github.com/Jigsaw-Code/outline-shadowsocksconfig/releases/tag/v0.0.9

And two PRs to pull it in:
- https://github.com/Jigsaw-Code/outline-client/pull/529
- https://github.com/Jigsaw-Code/outline-server/pull/402

The fix will go out in the next release. Many thanks again for the fix!
