### ISSUE TITLE
mac下编osx版本报错./scripts/do_action.sh: line 26: /src/www/build_action.sh: No such file or directory

### ISSUE THREAD

**Issue by xiaooutv** [Jigsaw-Code/outline-client#382]
从github下载了最新的release版本的tar压缩包，
在本地解压后，
执行命令编译：
`yarn run clean && yarn && yarn gulp build --platform=osx`

报错：
`[18:38:40] Building for platform osx...
++ git rev-parse --show-toplevel
fatal: Not a git repository (or any of the parent directories): .git`

`./scripts/do_action.sh: line 26: /src/www/build_action.sh: No such file or directory`

**Comment by LinyangHe** [comment]
Jesus, I spent like three days on this...THANK YOU SO MUCH
