### ISSUE TITLE
呼叫大牛，呼叫大牛，呼叫大牛，收到请回答，收到请回答，收到请回答

### ISSUE THREAD

**Issue by YUHG412** [Jigsaw-Code/outline-client#386]
打开文件：./scripts/do_action.sh
发现是这一行代码报错：
`export ROOT_DIR=${ROOT_DIR:-$(git rev-parse --show-toplevel)}`

才明白是因为下载的压缩包版本，
目录下没有.git/目录且还没有用git管理源码导致。

**解决办法**：
**从官网用`git clone`最新或对应版本代码到本地重新编译。**

建议维护团队的朋友兼容这种直接下载zip或tar.gz压缩包解压编译的情况。

_Originally posted by @xiaooutv in https://github.com/Jigsaw-Code/outline-client/issues/382#issuecomment-437846677_

**Comment by trevj** [comment]
@YUHG412 Thanks for trying to build Outline. I'm afraid we don't have any plans to change this but we are, as always, open to pull requests.
