### ISSUE TITLE
slower than shadowsocks

### ISSUE THREAD

**Issue by rc452860** [Jigsaw-Code/outline-client#391]
in my test,outline is slower then shadwsocks.i think The main reason is because add tun2socks and have double tcp/ip stack.Is there any way to solve it?

![image](https://user-images.githubusercontent.com/3949222/48663804-54b44e80-ead0-11e8-9bf8-bb26c49ffd0b.png)

![image](https://user-images.githubusercontent.com/3949222/48663800-47975f80-ead0-11e8-98a7-9e6bfc3199b4.png)

**Comment by studentmain** [comment]
Remember hide your server IP address.
To provide "full VPN", it must use tun2socks.
若尘 <notifications@github.com> 于 2018年11月18日周日 上午1:19写道：

**Comment by rc452860** [comment]
@studentmain Actually this is not a complete vpn, and tun2socks have the efficiency problem.

**Comment by studentmain** [comment]
Okay, "full proxy".

若尘 <notifications@github.com> 于 2018年11月18日周日 下午12:15写道：

**Comment by rc452860** [comment]
@sailosha 
同样的服务器。这两台是同一台电脑同一个服务器 同一个时间测试的。前后差距不到5分钟。但是很奇怪的是。我测速没这个问题只有YouTube有。fast.com测速两个客户端是一致的。

**Comment by rc452860** [comment]
@sailosha 
同样的服务器。这两台是同一台电脑同一个服务器 同一个时间测试的。前后差距不到5分钟。但是很奇怪的是。我测速没这个问题只有YouTube有。fast.com测速两个客户端是一致的。

**Comment by rc452860** [comment]
@sailosha 
同样的服务器。这两台是同一台电脑同一个服务器 同一个时间测试的。前后差距不到5分钟。但是很奇怪的是。我测速没这个问题只有YouTube有。fast.com测速两个客户端是一致的。

**Comment by rc452860** [comment]
@sailosha
你用自己服务器测试一下就好了。shadowsocks和outline是兼容的。YouTube链接速率8000上不去。我正在查这个问题。最开始怀疑是lwip这个库的效率问题。但是看别人嵌入式测试这个库调优stm32都可以上600m网速。感觉应该不是lwip的问题。现在还在查

**Comment by sailosha** [comment]
3个月前测试过 缓冲2个都没问题 我人不在国内服务器扔亚太区走CN2 自己没办法测

**Comment by rc452860** [comment]
@sailosha
先丢这里吧。我慢慢查。感觉还可以优化。还有很多工作可以做。

**Comment by trevj** [comment]
@rc452860 Thanks for trying Outline. I'm afraid @sailosha is right, there are many things could affect this. You say connection speed tests such as fast.com provide consistent results between the two servers? These tests are what I use myself (usually speedtest.net) rather than something like Youtube which, for example, doesn't necessarily need to use all available bandwidth.

**Comment by rc452860** [comment]
@trevj This test is not rigorous, temporarily turn off him first. Wait until I have time to find a rigorous environmental test. Then provide data.
