### ISSUE TITLE
We really need the PAC mode

### ISSUE THREAD

**Issue by tanchengqiu** [Jigsaw-Code/outline-client#397]
Dear team:
I love outline because it’s easy and safe.But it’s more convenient to have the PAC mode,otherwise I have to switch on and off very time...

**Comment by tanchengqiu** [comment]
SS服务器，客户端都有，因为这个好看，想用这个。

**Comment by tanchengqiu** [comment]
有自己搞得SS服务器，也有SS客户端，也用了好几年了。工作就是搞linux的……这个界面好看，尤其在IOS，想用而已……

**Comment by sailosha** [comment]
哦哦 他们不支持pac的 我以前问过能不能单独网页代理一类
他们的意思是：不 太麻烦了 现在是修别的问题
所以还是建议ss客户端+pac

**Comment by qudy2001** [comment]
哪个IOS的SS客户端支持SS URL啊？

**Comment by tanchengqiu** [comment]
刚刚IOS发布了一个版本说是重新开放bypass  功能？

**Comment by trevj** [comment]
@tanchengqiu Thanks for trying Outline! This is one of our most requested features, please do +1 it:
https://github.com/Jigsaw-Code/outline-client/issues/8
