### ISSUE TITLE
[Feature Request] Show on which port the client is trying to connect

### ISSUE THREAD

**Issue by pascalandy** [Jigsaw-Code/outline-client#406]
Because I'm a power user I was able to fix my issue but that could be useful for non-it folks.

- I just set up my second computer
- The Outline's client could not connect.
- Then I remember that unlike OpenVPN, Outline uses a random port for each new users. 
- I when into Little Snitch to see on which port Outline client was trying to connect onto.
- I opened the port on the server and boom, it worked.

_Note: on my server UFW blocks most ports by default_.

### Suggestion

When the connection can't be made, have the GUI show something like:

```
Error: the client tried to connect on 123.456.15.12:45621. Please make sure the port is open on the server, and etc...
```

**Comment by trevj** [comment]
@pascalandy Thanks for trying Outline!

I completely agree we need to make this easier. We have a few efforts nearing completion in that area:
- No more "random port for each access key": we recently rolled out a new server which can support multiple users on one port. This will make firewall configuration much easier.
- The server manager will let you change the port used for access key(s).

Your suggestion of having the *client* explain what failed is one we hadn't considered. Personally, I like it.

**Comment by pascalandy** [comment]
I'm not into OpsSec but I feel the tradeoff is better:

> - No more "random port for each access key": we recently rolled out a new server which can support multiple users on one port. This will make firewall configuration much easier.
> - The server manager will let you change the port used for access key(s).

**Comment by alalamav** [comment]
The Outline clients now display the port number for each server.
