### ISSUE TITLE
Using custom DNS server instead of OpenDNS

### ISSUE THREAD

**Issue by NanoG6** [Jigsaw-Code/outline-client#408]
Anyone knows how can I change the DNS for the clients? Currently they are using OpenDNS by default. I need to use my internal DNS server.

**Comment by trevj** [comment]
@pascalandy It doesn't matter how the server is configured, the Outline client itself performs DNS (currently hard-coded, though at some point we would like to make it configurable).

**Comment by sqwwqw5** [comment]
> @hd-deman I see what you did there, glad it works for you but we'd rather make this setting explicit in the client vs. having the server silently rewrite queries.
> 
> @pascalandy `iptables` is one of the hardest problems in computer science :-)

Then you should've let user decide what DNS server they want to use, DNS clearly plays a big part in privacy.

**Comment by d4op** [comment]
./cordova-plugin-outline/android/java/org/outline/shadowsocks/ShadowsocksConnectivity.java:  private static final String DNS_RESOLVER_IP = "208.67.222.222";  // OpenDNS
./cordova-plugin-outline/android/java/org/outline/vpn/VpnTunnel.java:    "208.67.222.222", "208.67.220.220"
./cordova-plugin-outline/apple/vpn/PacketTunnelProvider.m:  settings.DNSSettings = [[NEDNSSettings alloc] initWithServers:@[@"208.67.222.222", @"216.146.35.35",
./cordova-plugin-outline/apple/vpn/ShadowsocksConnectivity.m:static char *const kDnsResolverAddress = "208.67.222.222";  // OpenDNS
./src/electron/add_tap_device.bat:netsh interface ip set dnsservers %DEVICE_NAME% static address=208.67.222.222
./third_party/badvpn/lwip/src/core/dns.c:#define DNS_SERVER_ADDRESS(ipaddr)        (ip4_addr_set_u32(ipaddr, ipaddr_addr("208.67.222.222"))) /* resolver1.opendns.com */

**Comment by EvilBox** [comment]
The presented solutions are inoperative
Docker rewrites firewall chain
Does the community have a ready-made solution? As I understand it, developers will not add the feature - custom DNS. Thanks!

**Comment by MrBenFTW** [comment]
Still no custom DNS option?

**Comment by momai** [comment]
not working ;(
