### ISSUE TITLE
Modify the code and recompile it

### ISSUE THREAD

**Issue by ameue** [Jigsaw-Code/outline-client#419]
hello:
    If we modify the Library under the third_party folder ourselves and recompile it with the compiler command in README.md, will our modifications be overwritten?

**Comment by trevj** [comment]
@ameue No, if you modify and recompile code in third_party before compiling the client then your changes to third_party should be included. Let me know if you have a more specific question!

**Comment by ameue** [comment]
That's fine. Thank you! I have a question: do the two dynamic libraries, Shadowsocks_iOS. framework and PacketProcessor_iOS. framework, used in iOS projects compile the corresponding projects in the third_party/folder or download them from the internet? Because I saw in the compilation log that they copied the past directly from the third_party/folder

**Comment by trevj** [comment]
@ameue If you make changes to PacketProcessor and recompile it then, yes, the changes will appear in your re-compiled client. I haven't done this myself but @alalamav may be able to help if you get stuck.
