### ISSUE TITLE
Proxy settings on Windows

### ISSUE THREAD

**Issue by ryogishiki** [Jigsaw-Code/outline-client#428]
I have been using Outline for quite a while.
In earlier versions, Outline creates a system proxy on a random port when connected, and I just turn off the system proxy and use auto switch plugins in Chrome or Firefox for necessary traffics only.
But after a certain version, it no longer creates system proxy and forces all traffic through its connection. Auto switch plugins are not working as well.
Is this a feature? Or is there anything I can do to config about it?
Thanks.

**Comment by studentmain** [comment]
Feature. You may want use ss-windows.

ryogishiki <notifications@github.com> 于 2018年12月7日周五 上午9:09写道：

**Comment by trevj** [comment]
@ryogishiki Thanks for trying Outline. I'm afraid @studentmain is correct, this is a feature - sorry it's not working for you right now but FYI we do have plans to implement selective proxying based on the application and/or destination:
- https://github.com/Jigsaw-Code/outline-client/issues/180
- https://github.com/Jigsaw-Code/outline-client/issues/8
