### ISSUE TITLE
TCP forwarding in iOS Client

### ISSUE THREAD

**Issue by ameue** [Jigsaw-Code/outline-client#429]
In the process of playing the game, UDP can be smoothly forwarded to ss-server, but TCP data is not forwarded to ss-server, resulting in a large fluctuation of game delay. However, HTTP requests are forwarded normally. Does it have some relationship with ss-local configuration parameters? I haven't changed ss-local configuration parameters

**Comment by trevj** [comment]
@ameue That's weird - we see many more network issues with UDP than TCP. Can I ask which platform you're using (Windows, Android, etc.)?

**Comment by ameue** [comment]
iOS and Android, If there is an error log, I will post it.

**Comment by trevj** [comment]
Closuing due to inactivity. @ameue If you have any more info to provide, we'd love to hear it.
