### ISSUE TITLE
windows client does not run because /tmp does not exist

### ISSUE THREAD

**Issue by Mqinkai** [Jigsaw-Code/outline-client#435]
![image](https://user-images.githubusercontent.com/21375197/49841966-af517980-fdf4-11e8-9a43-55bb8550caba.png)

**Comment by trevj** [comment]
Looks like you are building and running on Windows. I just ran into this myself. It's due to `LINUX_TEMP_FOLDER` HERE:
https://github.com/Jigsaw-Code/outline-client/blob/master/src/electron/util.ts#L14

Working on a fix now.
