### ISSUE TITLE
yarn build fails 

### ISSUE THREAD

**Issue by wenewzhang** [Jigsaw-Code/outline-client#452]
yarn gulp build --platform=browser --watch
yarn run v1.6.0
$ /Users/wenewzhang/Documents/sl/outline-client/node_modules/.bin/gulp build --platform=browser --watch
[17:08:26] Using gulpfile ~/Documents/sl/outline-client/gulpfile.js
[17:08:26] Starting 'build'...
[17:08:26] Building for platform browser...
++ git rev-parse --show-toplevel
+ export ROOT_DIR=/Users/wenewzhang/Documents/sl/outline-client
+ ROOT_DIR=/Users/wenewzhang/Documents/sl/outline-client
+ export BUILD_DIR=/Users/wenewzhang/Documents/sl/outline-client/build
+ BUILD_DIR=/Users/wenewzhang/Documents/sl/outline-client/build
+ export -f do_action
+ do_action src/www/build
+ local action=src/www/build
+ echo '[Running src/www/build]'
+ shift
+ /Users/wenewzhang/Documents/sl/outline-client/src/www/build_action.sh
+ tsc -p src/www
error Command failed with exit code 2.
[17:08:32] 'build' errored after 5.96 s
[17:08:32] Error: Command failed: yarn do src/www/build
++ git rev-parse --show-toplevel
+ export ROOT_DIR=/Users/wenewzhang/Documents/sl/outline-client
+ ROOT_DIR=/Users/wenewzhang/Documents/sl/outline-client
+ export BUILD_DIR=/Users/wenewzhang/Documents/sl/outline-client/build
+ BUILD_DIR=/Users/wenewzhang/Documents/sl/outline-client/build
+ export -f do_action
+ do_action src/www/build
+ local action=src/www/build
+ echo '[Running src/www/build]'
+ shift
+ /Users/wenewzhang/Documents/sl/outline-client/src/www/build_action.sh
+ tsc -p src/www
error Command failed with exit code 2.

    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:653:13)
    at build (/Users/wenewzhang/Documents/sl/outline-client/gulpfile.js:215:17)
    at Gulp.<anonymous> (/Users/wenewzhang/Documents/sl/outline-client/gulpfile.js:200:3)
    at module.exports (/Users/wenewzhang/Documents/sl/outline-client/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/wenewzhang/Documents/sl/outline-client/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/wenewzhang/Documents/sl/outline-client/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/wenewzhang/Documents/sl/outline-client/node_modules/orchestrator/index.js:134:8)
    at /Users/wenewzhang/Documents/sl/outline-client/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (internal/process/next_tick.js:61:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

tsc -p src/www
src/www/app/app.ts:110:51 - error TS2345: Argument of type '(event: ServerAdded) => void' is not assignable to parameter of type 'OutlineEventListener'.
  Types of parameters 'event' and 'event' are incompatible.
    Property 'server' is missing in type 'OutlineEvent' but required in type 'ServerAdded'.

110     this.eventQueue.subscribe(events.ServerAdded, this.showServerAdded.bind(this));
                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  src/www/model/events.ts:22:15
    22   constructor(public readonly server: Server) {}
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    'server' is declared here.

src/www/app/app.ts:111:55 - error TS2345: Argument of type '(event: ServerForgotten) => void' is not assignable to parameter of type 'OutlineEventListener'.
  Types of parameters 'event' and 'event' are incompatible.
    Property 'server' is missing in type 'OutlineEvent' but required in type 'ServerForgotten'.

111     this.eventQueue.subscribe(events.ServerForgotten, this.showServerForgotten.bind(this));
                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  src/www/model/events.ts:30:15
    30   constructor(public readonly server: Server) {}
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    'server' is declared here.

src/www/app/app.ts:112:53 - error TS2345: Argument of type '(event: ServerForgotten) => void' is not assignable to parameter of type 'OutlineEventListener'.

112     this.eventQueue.subscribe(events.ServerRenamed, this.showServerRenamed.bind(this));
                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/www/app/app.ts:113:58 - error TS2345: Argument of type '(event: ServerForgetUndone) => void' is not assignable to parameter of type 'OutlineEventListener'.
  Types of parameters 'event' and 'event' are incompatible.
    Property 'server' is missing in type 'OutlineEvent' but required in type 'ServerForgetUndone'.

113     this.eventQueue.subscribe(events.ServerForgetUndone, this.showServerForgetUndone.bind(this));
                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  src/www/model/events.ts:34:15
    34   constructor(public readonly server: Server) {}
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    'server' is declared here.

src/www/app/app.ts:114:55 - error TS2345: Argument of type '(event: ServerConnected) => void' is not assignable to parameter of type 'OutlineEventListener'.
  Types of parameters 'event' and 'event' are incompatible.
    Property 'server' is missing in type 'OutlineEvent' but required in type 'ServerConnected'.

114     this.eventQueue.subscribe(events.ServerConnected, this.showServerConnected.bind(this));
                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  src/www/model/events.ts:46:15
    46   constructor(public readonly server: Server) {}
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    'server' is declared here.

src/www/app/app.ts:115:58 - error TS2345: Argument of type '(event: ServerDisconnected) => void' is not assignable to parameter of type 'OutlineEventListener'.
  Types of parameters 'event' and 'event' are incompatible.
    Property 'server' is missing in type 'OutlineEvent' but required in type 'ServerDisconnected'.

115     this.eventQueue.subscribe(events.ServerDisconnected, this.showServerDisconnected.bind(this));
                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  src/www/model/events.ts:50:15
    50   constructor(public readonly server: Server) {}
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    'server' is declared here.

src/www/app/app.ts:116:58 - error TS2345: Argument of type '(event: ServerReconnecting) => void' is not assignable to parameter of type 'OutlineEventListener'.
  Types of parameters 'event' and 'event' are incompatible.
    Property 'server' is missing in type 'OutlineEvent' but required in type 'ServerReconnecting'.

116     this.eventQueue.subscribe(events.ServerReconnecting, this.showServerReconnecting.bind(this));
                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  src/www/model/events.ts:54:15
    54   constructor(public readonly server: Server) {}
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    'server' is declared here.

src/www/app/clipboard.ts:31:11 - error TS2564: Property 'listener' has no initializer and is not definitely assigned in the constructor.

31   private listener: ClipboardListener;
             ~~~~~~~~

src/www/app/persistent_server.ts:36:11 - error TS2564: Property 'serverById' has no initializer and is not definitely assigned in the constructor.

36   private serverById: Map<string, PersistentServer>;
             ~~~~~~~~~~

src/www/app/persistent_server.ts:37:11 - error TS2564: Property 'lastForgottenServer' has no initializer and is not definitely assigned in the constructor.

37   private lastForgottenServer: PersistentServer|null;
             ~~~~~~~~~~~~~~~~~~~

src/www/app/settings.spec.ts:88:12 - error TS2564: Property 'length' has no initializer and is not definitely assigned in the constructor.

88   readonly length: number;
              ~~~~~~

src/www/app/updater.ts:23:11 - error TS2564: Property 'listener' has no initializer and is not definitely assigned in the constructor.

23   private listener: UpdateListener;
             ~~~~~~~~

src/www/app/windows_connection.ts:21:11 - error TS2564: Property 'statusChangeListener' has no initializer and is not definitely assigned in the constructor.

21   private statusChangeListener: (status: ConnectionStatus) => void;
             ~~~~~~~~~~~~~~~~~~~~


Found 13 errors.

build fails on macOS
yarn 1.6
node 11& 10 (same error)
what should i do?

thanks

**Comment by wenewzhang** [comment]
tsc -v
Version 3.2.2

**Comment by trevj** [comment]
@wenewzhang Thanks for trying Outline. For some reason you are using the wrong version of TypeScript: we're still on 2.5.2, not 3.2.2. My guess is that you have installed typescript "globally", with `yarn global add typescript`. If you remove that, then the client should compile.
