### ISSUE TITLE
Outline-Client.AppImage on Ubuntu 18.04 Desktop Icon Missing?

### ISSUE THREAD

**Issue by dan09gt** [Jigsaw-Code/outline-client#454]
Is this intended or I'm missing something?
![image](https://user-images.githubusercontent.com/6730496/50124331-11035f00-029f-11e9-8dbf-f75be78e2112.png)

Downloaded it from here: https://github.com/Jigsaw-Code/outline-client/releases

**Comment by RoldanLT** [comment]
Full screenshot
![image](https://user-images.githubusercontent.com/6730496/50124531-0a291c00-02a0-11e9-90d6-85946999f51c.png)

**Comment by dan09gt** [comment]
Outline Manager App Image works fine.
![image](https://user-images.githubusercontent.com/6730496/50199797-d88e7e80-038d-11e9-9a25-8b7b5e6077de.png)

**Comment by dan09gt** [comment]
Same issue on linux-v1.0.0-test1.
And it doesn't have an icon anymore on System Menu Bar.

**Comment by trevj** [comment]
@dan09gt Apologies for the slow reply. I'm not able to reproduce with the current version:
https://github.com/Jigsaw-Code/outline-client/releases/tag/linux-v1.0.3

I wonder if you can try again? Regarding the system tray, you're right, this was broken in the current version - fix hopefully going out later today (https://github.com/Jigsaw-Code/outline-client/issues/488).

**Comment by trevj** [comment]
I'm going to close this due to inactivity and because I can't reproduce. @dan09gt Please re-open if you're still seeing this.
