### ISSUE TITLE
Connection closing?

### ISSUE THREAD

**Issue by vysec** [Jigsaw-Code/outline-client#455]
Been getting this issue:

![image](https://user-images.githubusercontent.com/3596242/50128552-714ecc80-02b0-11e9-84fa-dcb72b9f63ea.png)

Basically VPN won't even connect at all.

**Comment by trevj** [comment]
@vysec Apologies for the slow response - were you able to figure out what was happening here?

**Comment by vysec** [comment]
Filtering, sorted.
