### ISSUE TITLE
Can you add Clipboard bulk import

### ISSUE THREAD

**Issue by yuningning520** [Jigsaw-Code/outline-client#457]
In Shadowsocks can import
ss://**
ss://**
ss://**
on one clipboard
I test outline, can't do this, no quick.
ps. in Android 8.1.0

**Comment by trevj** [comment]
@yuningning520 Thanks for trying Outline. Neat feature, we'll take it into consideration.

**Comment by trevj** [comment]
Just spotted this issue, which I think covers this:
https://github.com/Jigsaw-Code/outline-client/issues/339
