### ISSUE TITLE
Android failed to connect server using 4G

### ISSUE THREAD

**Issue by QwertyJack** [Jigsaw-Code/outline-client#458]
Android 8.1.0
kernel 4.4.103+
CMCC 4G
Outline 1.2.7 Android
Server ss-libev with udp

Failed to connect ss server using CMCC 4G.
However it works like a charm when using wifi.

**Comment by trevj** [comment]
@QwertyJack I'd need a lot more information before I can really help but this *could* be related to your mobile phone network restricting UDP traffic. We just started beta testing a new client that will work on such networks, perhaps you can give it a try?:
https://www.reddit.com/r/outlinevpn/comments/a68s0j/release_outline_beta_for_ios_and_android/

**Comment by trevj** [comment]
@alalamav FYI

**Comment by QwertyJack** [comment]
Glad to hear that. Let me try v1.2.8 .

**Comment by trevj** [comment]
@QwertyJack I'm going to close this due to inactivity but FYI all our clients now support servers and clients without UDP.
