### ISSUE TITLE
Questions about secondary development

### ISSUE THREAD

**Issue by Sean-Wang** [Jigsaw-Code/outline-client#462]
Outline is awesome project. Thanks so much. You've been a big help already.

We plan to do some simple secondary development based on Outline. For example, add a user login interface. There is two way that: Add HTML and other content directly in the outline project or add some content in each build project. Which one is better?

Thanks. @trevj @alalamav

**Comment by trevj** [comment]
@Sean-Wang Thanks for trying Outline!

So, I'm not sure I understand your second option: "add some content in each build project". Are you considering changes to the client(s), server manager, or both?

**Comment by sailosha** [comment]
For my understanding:
he is asking for use outline souce code and build his own stuff.
And also, he is wondering which one is better for user login with password. Html (probably SQL way to login) or outline project shows up an user name and password.

you can build you own json/database and use either way to login. It won't bother, but build you own sql give your more freedom choice. I personally not willing to let project developer to build this.(cuz it is not necessary lol, a simple mini sql can hold all the stuff)

**Comment by Sean-Wang** [comment]
> For my understanding:
> he is asking for use outline souce code and build his own stuff.
> And also, he is wondering which one is better for user login with password. Html (probably SQL way to login) or outline project shows up an user name and password.
> 
> you can build you own json/database and use either way to login. It won't bother, but build you own sql give your more freedom choice. I personally not willing to let project developer to build this.(cuz it is not necessary lol, a simple mini sql can hold all the stuff)

Yeah, we want to build our own stuff.

**Comment by trevj** [comment]
@Sean-Wang In that case, I recommend adding it to the "web app", under `src/www`. Any changes you make there will be included on all platforms.

**Comment by Sean-Wang** [comment]
> @Sean-Wang In that case, I recommend adding it to the "web app", under `src/www`. Any changes you make there will be included on all platforms.

Thank you for your reply. @trevj
