### ISSUE TITLE
How to switch server port?

### ISSUE THREAD

**Issue by DragonCircle** [Jigsaw-Code/outline-client#465]
In some cases, the GFW block some certain ports automatically , we need to change the port to browse the Internet.

如何更换Outlie服务器端口？
防火墙会自动屏蔽一些端口，在更换服务器端口设置？（因为我用的是shadowsocksX-NG连接服务器，不是用的outline的那个VPN）

**Comment by studentmain** [comment]
Generally, you can't do that now.

简单地说，还没法，老老实实上ss-libev

Jeff Li <notifications@github.com> 于 2018年12月22日周六 下午12:42写道：

**Comment by studentmain** [comment]
现阶段恐怕只有在服务器上iptables转发端口将就。不过你说的"防火墙"是指客户侧的，还是服务侧的，还是指"那个防火墙"。

**Comment by DragonCircle** [comment]
> 现阶段恐怕只有在服务器上iptables转发端口将就。不过你说的"防火墙"是指客户侧的，还是服务侧的，还是指"那个防火墙"。

当然指GFW，你没有经历过吗？SS突然不能用，ssh上去换个端口就好了？

**Comment by studentmain** [comment]
话说这在隔壁 https://github.com/Jigsaw-Code/Outline-Server/issues 讨论比较好

**Comment by trevj** [comment]
Going to mark this as a duplicate, not sure why I just linked to the original issue.
