### ISSUE TITLE
".....Outline is not properly installed....". Any suggestions? 

### ISSUE THREAD

**Issue by hereticalcoral** [Jigsaw-Code/outline-client#466]
Hi, I installed Outline manager and client on Windows 10 two days ago. And I chose DigitalOcean as my server. 
The connection of my VPN works good at the beginning. However, I cannot browse website later, though Outline client shows the connection is built. The error is in browser, which is "cannot find the IP address of the website". I switched to different servers trying to fix the problem but failed. 
Then, I tried to change the TCP/IPV4 setting of the "outline-tap0" adapter from "using following IP address/ DNS address" to "obtain the IP address/DNS automatically", the error is shown in the Outline client, which is "Outline is not properly installed". 
I would guess I may not be the only one who has the similar problem. If anyone can help me to figure this out, I would be very appreciated.

**Comment by hereticalcoral** [comment]
By the way, I just found that the Outline Client installed on my laptop is 32 bit. However, the system of my laptop is 64 bit. Is that the real issue? I downloaded the Outline Manager and Client from the Outline VPN official website. It seems there is no specific notice for the 32bit and 64bit system.

**Comment by CZY3434123** [comment]
I have the same problem

**Comment by trevj** [comment]
@hereticalcoral Sorry you've been having problems with the Windows client. Two things:
- I'm afraid changing settings on outline-tap0 won't help: it *must* have the IP 10.0.85.2 - otherwise you'll see the "Outline needs to be reinstalled" error.
- We only release a 32 bit version of the client to handle older Windows 7 systems; this 32 bit version should run just fine on 64 bit machines.

**Comment by trevj** [comment]
@hereticalcoral Do you have another device with which to test your server? It should be on the same network as your Windows machine: *not* a 4G/LTE mobile connection.

**Comment by al5330** [comment]
> @hereticalcoral Do you have another device with which to test your server? It should be on the same network as your Windows machine: _not_ a 4G/LTE mobile connection.

I have the same problem. There is no problem with the server.

**Comment by Highsun** [comment]
I had this same issue pop up yesterday. I work at a school and the IT staff block VPN traffic on the network so I have been using Outline for a while at work. 

For me, it was working fine all day and I got up from my desk locked my laptop and left for maybe 30 minutes or so. I came back to find that the wifi was showing it was no longer connected to any network. So I went ahead logged back in and selected the regular wifi and connected, from here I disconnected outline and went to re-establish its connection. At this point, I started getting the error.

**What I've tried so far**:
1. At first, I thought it may be the server so I tried connecting to it via my phone, it had no problems at all.
2. I thought maybe it could be the network then, so I went ahead and tethered my phones mobile date to the laptop and tried connecting again, my normal VPNs worked, but Outline was still giving the same error.
3. I then Revo uninstalled the client, rebooted, reinstalled client. Still same error.
4. I destroyed the digital ocean server via the manager, recreated, added the server to the client. Still the same error.
5. Yesterday I ran out of time so now I have both the manager and client Revo uninstalled, rebooted and will continue to troubleshoot from my end while at work.

Any suggestions are welcome.

**Comment by Highsun** [comment]
Ok so after a couple days of troubleshooting this issue, I'm suspecting something is causing the tap to be unhappy. 

Uninstalling the client did nothing by itself, however, if I uninstalled the client, then went into device manager and uninstalled the tap for outline, then rebooted and reinstalled the client and added the server again, it worked like new.

So not much for information but at least this should help some people get up and running for now. If I find the exact cause I'll be sure to post it here.

**Comment by Flawks** [comment]
I tried solution suggested by @Highsun on Win7x64. Unfortunately that didn't help

**Comment by trevj** [comment]
@Highsun @Flawks Sounds like you've largely resolved this - apologies for the inconvenience and thanks for taking the time to report.
