### ISSUE TITLE
Please STOP requiring UDP!

### ISSUE THREAD

**Issue by LBYPatrick** [Jigsaw-Code/outline-client#467]
We all know UDP is an important protocol on the internet other than TCP, and this software is designed for unblocking websites in internet-restricted countries.

Here is the fun part: These countries usually have restrictions on UDP.

This means that in some cases you would be able to use UDP because they made it not working (i.e. Under China Mobile Shadowsocks' UDP works 40% of the time), and most users who were using Shadowsocks before were using TCP the whole time just for accessing Google or Instagram.

The main reason why most people switched back to the original Shadowsocks clients (i.e. [shadowsocks-qt5](https://github.com/shadowsocks/shadowsocks-qt5) for windows or [ShadowsocksX-NG](https://github.com/shadowsocks/shadowsocksX-NG) for macOS ) is this UDP thing. 

Please put this into consideration, thank you.

**Comment by LBYPatrick** [comment]
@sailosha 中国移动屏蔽UDP是真的，我在广东，十次只有四次能正常使用UDP，而只依靠TCP也能满足基本需求，所以我希望Outline取消强制UDP。

> 另外我建议你检查一下你的英语语法

**Comment by LBYPatrick** [comment]
@sailosha Sorry but there isn't any proper software providing convincing data (to me it should be as detailed as WinMTR data), but...

Both my servers are not going through CN2 network (which are ``jpn1.lbynet.com``(Linode JPN) and ``jpn2.lbynet.com``(Vultr JPN)) and my cellular network and cable network, as implied in my first post, is **China Mobile**. (And I use opened about 50 ports for shadowsocks with [my program](https://github.com/LBYPatrick/YAMATO))

So here's what I observed:

1. This problem appears mostly under China Mobile
2. For cable network (which is "家用宽带" or "光纤"):
    - 0900 AM -- 1100 AM: Completely unusable (UDP fails but TCP passes (Tested on both SSTap and Outline with the two servers mentioned above))
    - Other times: fine for 90% of the time but with unstable UDP connection

3. For cellular network (which is "蜂窝数据" or "流量"):
    - Pretty much the same as cable, but more unstable (So probably another two or three down hours in afternoon)

**Comment by trevj** [comment]
@LBYPatrick We are beta testing a new version of the client which will work on networks and servers that do not support UDP:
https://www.reddit.com/r/outlinevpn/comments/a68s0j/release_outline_beta_for_ios_and_android/

**Comment by pavelborisofff** [comment]
China Unicom (中国联通) sometimes block UDP. 
I used China's SIM about a week without problems, today I have received UDP errors on phone. My friends also use China Unicom SIM cards, and they could not used Outline without UDP.

Also, today I have UDP error on OS X Mojave for a few minutes, connected to wired network (I don't know what the provider).

Outline server raised in Netherland, nothing special, no any other features or services.

Reddit blocked in China. 
> @LBYPatrick We are beta testing a new version of the client which will work on networks and servers that do not support UDP:
> https://www.reddit.com/r/outlinevpn/comments/a68s0j/release_outline_beta_for_ios_and_android/

I put info from Reddit here

> We just released an updated version of Outline for iOS and Android with DNS fallback to TCP when the proxy server or network does not support UDP. Help us test [Outline v.1.2.8 for Android](https://play.google.com/store/apps/details?id=org.outline.android.client&hl=en_US) (opt-in for beta access) and [Outline v.1.2.4 for iOS](https://testflight.apple.com/join/XZKdpUbS) (through TestFlight). Let us know what you think by submitting feedback through the app.
> This is our last update of 2018. Thanks for all your feedback and input this year!
> 
> How to opt-out of beta: Uninstall the app (instructions for [Android](https://support.google.com/googleplay/answer/2521768?hl=en) and [iOS](https://support.apple.com/en-us/HT207618)). You can download and re-install the latest stable version of Outline at [getoutline.org](https://www.getoutline.org/).

**Comment by trevj** [comment]
Folks,

All our clients now support servers and networks without UDP:
- https://github.com/Jigsaw-Code/outline-client/releases/tag/windows-v1.2.24
- https://github.com/Jigsaw-Code/outline-client/releases/tag/android-v1.2.9
- https://github.com/Jigsaw-Code/outline-client/releases/tag/ios-v1.2.5
- https://github.com/Jigsaw-Code/outline-client/releases/tag/macos-v1.2.5

**Comment by LBYPatrick** [comment]
¡Muchos gracias! This would be helpful when traveling back to China!

**Comment by Since1999** [comment]
> trevj
hi:
Could U can add rules for URL/IP addresses so that they can connect DIRECTly or through the PROXY, or even REJECT to connect.
