### ISSUE TITLE
how export outline-client config or copy or share config to other outline-client?

### ISSUE THREAD

**Issue by hktalent** [Jigsaw-Code/outline-client#470]
how export outline-client config or copy or share config to other outline-client?

or
where is the config file

**Comment by trevj** [comment]
@hktalent Thanks for using Outline. I'm afraid it's not possible right now to re-share a server via the client: you must keep the original email/IM/whatever message containing the invite.

This has come up before and we are considering this:
https://github.com/Jigsaw-Code/outline-client/issues/90

**Comment by aryabarzan** [comment]
How can I make backup of users? I need to move the users on another server.
