### ISSUE TITLE
iOS error: Incompatible library version: CocoaLumberjackSwift requires version 1.0.0 or later, but libswiftCore.dylib provides version 0.0.0

### ISSUE THREAD

**Issue by HeavenYoung** [Jigsaw-Code/outline-client#471]
Mac OS: 10.14
Xcode Version 10.1 (10B61)

![image](https://user-images.githubusercontent.com/12215944/50626423-12a07880-0f69-11e9-9bb4-febf5b6e2816.png)

**Comment by trevj** [comment]
@alalamav I think we're still on Xcode 9.x, am I right?

@HeavenYoung You might have better luck with Xcode 9.4:
https://github.com/Jigsaw-Code/outline-client/blob/master/.travis.yml

**Comment by HeavenYoung** [comment]
@trevj  I've fixed this issue on Xcode 9.4 , cheers mate.
