### ISSUE TITLE
system tray missing on Windows and Linux

### ISSUE THREAD

**Issue by sailosha** [Jigsaw-Code/outline-client#488]
win10 1803 update another bug 
![12](https://user-images.githubusercontent.com/1269208/51089746-513feb00-1740-11e9-9057-46597cc0904f.png)

**Comment by mookrhodan** [comment]
same for me on Win10 1607

**Comment by trevj** [comment]
@sailosha Thanks for the report. I think I broke this with https://github.com/Jigsaw-Code/outline-client/pull/453. I just submitted a fix for review:
https://github.com/Jigsaw-Code/outline-client/pull/494
