### ISSUE TITLE
possible issue with startup behaviour on windows

### ISSUE THREAD

**Issue by kevy8707** [Jigsaw-Code/outline-client#501]
**Describe the issue**
no response when trying to open outline in win10, it can be seen in task manager, but need to end it then reopen the app.

**Environment**
 - Yarn version
 - Node.js version

**Additional context**

**Comment by trevj** [comment]
@kevy8707 I need a bit more information to help you here. Do you mean that when you close the Outline window you need kill and restart before the window will reappear? You can't just relaunch?

There's an issue in the current release concerning the system tray icon, I wonder if that's what's happening here:
https://github.com/Jigsaw-Code/outline-client/issues/488

**Comment by kevy8707** [comment]
I got the same tray icon problem. What I mean is sometimes when double click outline app, the window will not show, i need to go to task manager to kill it then reopen the app, and it will show finally. And some of my colleagues using win10 have such problem.

BR,
Kevin Yang


________________________________

**Comment by Omoeba** [comment]
I got the same problem. When the computer boots up, outline is not in the system tray, but if you look for outline in task manager, there are 2 "outline (32-bit)" and 1 "outline service". The IP address is did not change to the server's address. If you try to start outline, nothing would happen. You would need to quit both of the "outline (32-bit)" processes and start outline again to make it work.

**Comment by ElijahZAwesome** [comment]
I have the exact same problem described by @kevy8707. I don't want to just +1 this post but although i would love to look through the source code to find the issue, i don't think ill find anything and the adventure would be fruitless.

**Comment by trevj** [comment]
@kevy8707 @Omoeba @ElijahZAwesome Thanks again for the report. I haven't seen this behaviour myself so it's hard for me to debug but of course we'll keep this open.

**Comment by trevj** [comment]
BTW, there could be a bug in the code that runs on startup - to be determined.

**Comment by trevj** [comment]
@kevy8707 @Omoeba @ElijahZAwesome Thanks again for the report. I was able to reproduce and have a fix under review in https://github.com/Jigsaw-Code/outline-client/pull/536. We should be able to release a fix tomorrow.

**Comment by trevj** [comment]
This should be fixed in 1.2.28. Please re-open if you still see the issue after upgrading.
