### ISSUE TITLE
Cannot build Android client

### ISSUE THREAD

**Issue by DonZheng** [Jigsaw-Code/outline-client#503]
**Describe the issue**
Followed Readme and installed yarn and node.js. Tried building android client via command 'yarn gulp build --platform=android' but got error messages about modules missing...

Tried install individual modules like 'gulp', 'gulp-posthtml', and many others, I followed promted message and tried 'npm audit fix' and 'npm install'. Still got more error messages...

Below is the snapshot of another error message....

**Environment**
 - OS: Windows 10 home
 - Yarn version: 1.13.0
 - Node.js version: v10.15.0

**Additional context**
C:\Users\don\Downloads\outline-client-master>yarn gulp build --platform=android
yarn run v1.13.0
$ C:\Users\don\Downloads\outline-client-master\node_modules\.bin\gulp build --platform=android
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'posthtml-postcss'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\don\Downloads\outline-client-master\scripts\generate_rtl_css.js:18:21)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by trevj** [comment]
@DonZheng Thanks for trying Outline. I'm afraid on Windows you'll need to install Cygwin before our build scripts will work (this is briefly mentioned at https://github.com/Jigsaw-Code/outline-client#windows - sorry we haven't made it more explicit).

BTW, to build for Android specifically I do recommend our Docker-based helper - but I don't know how well it works on Windows:
https://github.com/Jigsaw-Code/outline-client#building-for-android-with-docker

**Comment by DonZheng** [comment]
Dear trevj,

Thank you very much for your guidance.

I will follow your advice and try again.

A follow-up question is whether you can please recommend an IDE for us to
play around the code? I am very new to node.js, yarn, only know about
android studio, so I will appreciate it very much if you can share some
guidance.

Respectfully,

Don

**Comment by trevj** [comment]
@DonZheng I'm happy to help answer further development-related questions - it helps us figure out where we can improve.

Regarding IDE, I recommend (and use myself) Visual Studio Code (VSC):
https://code.visualstudio.com/

It has great support for TypeScript: if, after running `yarn install`, you open the git repo in VSC then you should get auto-complete, formatting, compile errors, etc., right away.

**Comment by trevj** [comment]
@DonZheng Please re-open if you still run into problems here.

**Comment by karance7** [comment]
I have also issue in Android Build

Window 10 
Node 10.15.3
npm 6.4.1
cygwin installed

error
---------------
yarn cordova platform rm android && yarn gulp build --platform=android
yarn run v1.15.2
$ E:\Code\outline-client\node_modules\.bin\cordova platform rm android
Done in 3.73s.
yarn run v1.15.2
$ E:\Code\outline-client\node_modules\.bin\gulp build --platform=android
[08:14:00] Using gulpfile E:\Code\outline-client\gulpfile.js
[08:14:00] Starting 'build'...
[08:14:00] Starting 'buildWebApp'...
$ bash ./scripts/do_action.sh src/www/build
++ git rev-parse --show-toplevel
                                + export ROOT_DIR=/mnt/e/Code/outline-client
                                                                            [Running src/www/build]
                                                                                                   + ROOT_DIR=/mnt/e/Code/outline-client
                + export BUILD_DIR=/mnt/e/Code/outline-client/build
                                                                   + BUILD_DIR=/mnt/e/Code/outline-client/build
                                                                                                               + export -f do_action
            + do_action src/www/build
                                     + local action=src/www/build
                                                                 + echo '[Running src/www/build]'
                                                                                                 + shift
                                                                                                        + /mnt/e/Code/outline-client/src/www/build_action.sh
                                    + tsc -p src/www
                                                    + rsync -ac --exclude '*.ts' src/www/ www/
                                                                                              + echo '[Done src/www/build]'
   [Done src/www/build]
[08:14:13] Finished 'buildWebApp' after 13 s
[08:14:13] Starting 'copyBabelPolyfill'...
'node_modules/babel-polyfill/dist/polyfill.min.js' -> 'www/babel-polyfill.min.js'
[08:14:13] Finished 'copyBabelPolyfill' after 366 ms
[08:14:13] Starting 'browserifyAndBabelify'...
[08:14:17] Finished 'browserifyAndBabelify' after 3.47 s
[08:14:17] Starting 'transpileBowerComponents'...
[08:14:35] Finished 'transpileBowerComponents' after 18 s
[08:14:35] Starting 'transpileUiComponents'...
[08:14:35] Finished 'transpileUiComponents' after 246 ms
[08:14:35] Starting 'rtlCss'...
[08:14:35] Generating RTL CSS
[08:14:36] Finished 'rtlCss' after 246 ms
[08:14:36] Starting 'writeEnvJson'...
[08:14:42] Finished 'writeEnvJson' after 6.18 s
[08:14:42] Starting 'cordovaPlatformAdd'...
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: org.outline.android.client
        Name: Outline
        Activity: MainActivity
        Android target: android-27
Android project created with cordova-android@7.1.4
Android Studio project detected
Android Studio project detected
Installing "com.borismus.webintent" for android
Installing "com.verso.cordova.clipboard" for android
Installing "cordova-custom-config" for android
Installing "cordova-plugin-device" for android
Installing "cordova-plugin-outline" for android
Copying Android third party source code
Subproject Path: CordovaLib
Subproject Path: app
Installing "cordova-plugin-splashscreen" for android
Installing "cordova-plugin-statusbar" for android
Installing "cordova-plugin-whitelist" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.

cordova-custom-config: Skipping auto-restore of config file backup(s)
cordova-custom-config: Applied custom config from config.xml to E:\Code\outline-client\platforms\android\app\src\main\AndroidManifest.xml
Running command: cmd "/s /c ""/bin/bash -eu" E:\Code\outline-client\scripts\update_android_target_version.sh E:\Code\outline-client""
The system cannot find the path specified.
Error: Hook failed with error code 1: E:\Code\outline-client\scripts\update_android_target_version.sh
[08:15:02] 'cordovaPlatformAdd' errored after 20 s
[08:15:02] Error: exited with error code: 1
    at ChildProcess.onexit (E:\Code\outline-client\node_modules\end-of-stream\index.js:39:36)
    at ChildProcess.emit (events.js:189:13)
    at ChildProcess.EventEmitter.emit (domain.js:459:23)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
[08:15:02] 'build' errored after 1.02 min
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Please help me out this problem

**Comment by OneHappyForever** [comment]
I also have the same issue as karence7 above when compiling after running yarn run clean && yarn && yarn gulp build --platform=android

It worked the first time, but now when re-compiling it doesn't work

**Comment by wangandhao** [comment]
@karance7 me too.The same problem.Did you find way to resolve?
