### ISSUE TITLE
Connection stops working on Linux

### ISSUE THREAD

**Issue by alexmherrmann** [Jigsaw-Code/outline-client#504]
**Description**
After some variable amount of time passes, my outline connection can no longer reach the internet.

**To Reproduce**
I had been using a Digital Ocean server in the SFO2 just fine for a while. But an update to the outline client (I presume from `1.0.3 -> 1.0.4`) and a change to a Frankfurt server seems to have messed something up.

I will get a successful connection to the outline server and will be able to run just fine for some amount of time. Eventually no connections can be made. The outline client still shows me as "connected", and the ss-local command is still running. If I disconnect from the outline server I then go back to working (not through the proxy though). Attempting to reconnect produces an error. If I manually kill off the still running ss-local command I am then able to reconnect, and the process repeats.

**Expected behavior**
The connection to the proxy should remain stable or know when it's encountered a problem and correctly recover.

**Logs**
Here is the "hanging" ss-local command (showed using pgrep, with what I assume is semi-personal information blocked out with ****)
`26342 /tmp/.mount_OutlinnMygIv/resources/app.asar.unpacked/third_party/shadowsocks-libev/linux/ss-local -l **** -s **** -p **** -k **** -m chacha20-ietf-poly1305 -t 28 -u`

Logs from Outline-Client: (including a disconnect so I could continue to write this bug :smile:)
```
loading web app from file:///tmp/.mount_OutlinnMygIv/resources/app.asar/www/electron_index.html
Checking for update
Outline is starting
Update for version 1.0.4 is not available (latest version: 1.0.4, downgrade is disallowed).
Pipe connected
Got data from pipe for action: resetRouting
UDP forwarding enabled
Got data from pipe for action: getDeviceName
Got data from pipe for action: configureRouting
Promise "DNS lookup" resolved before 10000 ms.
Promise "Reachability check" resolved before 10000 ms.
tun2socks exited with code 1
Got data from pipe for action: resetRouting
```
I will gladly attempt again, I have pulled down the Frankfurt
**Desktop**
 - OS: Ubuntu 18.04
Latest Chrome doesn't work, curl doesn't work. No TCP connections seem to be able to go through.
DNS queries also no longer work (`dig`s of google against `8.8.8.8`, `8.8.4.4`, and `1.1.1.1` all timeout)

**Additional context**
I am in Slovakia so I do not think there is any censorship, etc. going on right now.

I will gladly attempt to reproduce or collect more logs with some information on how that works but I have only been using outline for a short amount of time so my knowledge is fairly limited.

**Comment by trevj** [comment]
@alexmherrmann Thanks for the detailed report - sorry you've been having problems with Outline.

I'm afraid I don't know what's happening. The output of this command would help me debug: (again, removing any identifying information such as your proxy server's IP address):
```
route -n
```
If you can send me the output both while the connection is working and when it's stopped working, that would be great.

Thanks!

**Comment by alexmherrmann** [comment]
Sorry about the (incredibly) late reply. My use case for outline was suppressed for a while so I had stopped using it and shut down my server. Running the updated client has fixed it for whatever reason. I've been using it semi-regularly and haven't had the same problem occur. If it does happen again I'll return to this issue but for my purposes it can be closed. Thanks.
