### ISSUE TITLE
Detected as a Trojan via Windows Defender

### ISSUE THREAD

**Issue by mxschmitt** [Jigsaw-Code/outline-client#51]
Details:
![image](https://user-images.githubusercontent.com/17984549/38172403-121ca916-35ac-11e8-9aef-cf1580a51891.png)

**Comment by griffinbai** [comment]
I also encountered this warning too .
![default](https://user-images.githubusercontent.com/10183338/38173620-4132f208-35f4-11e8-810f-239a040d5305.JPG)

**Comment by lifeva** [comment]
me too

**Comment by suonli** [comment]
me too
Trojan:Win32/Bitrep.B

**Comment by trevj** [comment]
Related issue:
https://github.com/Jigsaw-Code/outline-client/issues/12

**Comment by trevj** [comment]
@mxschmitt, @griffinbai, @lifeva, @suonli - many thanks for the reports. This is really useful for us. I'm going to mark this as a duplicate of https://github.com/Jigsaw-Code/outline-client/issues/12 and continue discussion there.
