### ISSUE TITLE
[Mac v1.2.5] Can’t Connect to Internet

### ISSUE THREAD

**Issue by yakovmanshin** [Jigsaw-Code/outline-client#511]
In Outline 1.2.5 on macOS 10.14.3, I’m not able to use the internet on my Mac. Although the Outline client seems to be connected to the server, sites don’t open.

## Quick Facts
* I attempted to connect to three different servers (all in AWS).
* The iOS client (v1.2.5) works fine with the very same servers.
* Other VPN services (namely, TunnelBear) function properly on the same network.

## Configuration
* Outline client version: 1.2.5
* OS: macOS 10.14.3
* Browser: Safari 12.0.3

**Comment by hadifarnoud** [comment]
I tried both auto and manual install in Digitalocean.

I can ping the server IP when Outline is connected but there is no internet

**Comment by hadifarnoud** [comment]
I even tried setting up the server while connected to a VPN. I did it to be sure my server IP is not compromised.

**Comment by tomlister** [comment]
Same here bud, being going on for months.

**Comment by yakovmanshin** [comment]
As of 2/10, I no longer experience the issue; tested on two Macs with macOS 10.14.3 and the latest supplemental update (macOS build 18D109).

**Comment by vinsongeo** [comment]
same here. It seems the connection broken soon after the establishment of a connection.
