### ISSUE TITLE
Allow User Defined DNS Server

### ISSUE THREAD

**Issue by TexanScot** [Jigsaw-Code/outline-client#515]
I use Pi-hole running on a Raspberry Pi to provide ad blocking on my local network.  All devices such as pc, iPads, phones etc. use the Pi-Hole as their DNS server.  However Outline seems to bypass the local DNS server and this allows ads to be served when active.

Allow user to specify and configure which DNS server should be used.

Just noted that this seems to already have been requested (Issue #343) - apologies for the duplication.

**Comment by trevj** [comment]
@TexanScot Let's discuss on https://github.com/Jigsaw-Code/outline-client/issues/343 :-)
