### ISSUE TITLE
Front proxy

### ISSUE THREAD

**Issue by AberSheeran** [Jigsaw-Code/outline-client#516]
There are times when the networks we use are limited. External networks can only be accessed through one Http(s)/socks5 proxy server. 
Can you join the front agent on the outline? Like this

![qq 20190204002929](https://user-images.githubusercontent.com/25364828/52179318-fd429680-2813-11e9-80df-5507004fba56.png)

By the way, maybe it's enough to support only the SOCKS5.

**Comment by jadolg** [comment]
This feature is really needed. Many places use a proxy to access the internet and it is impossible to use outline there without a massive amount of magic.

**Comment by trevj** [comment]
@AberSheeran @jadolg Thanks for the report. This has been requested many times and we are still working to make it easy:
https://github.com/Jigsaw-Code/outline-server/issues/44
