### ISSUE TITLE
Possible bug in latest iOS client version 1.2.6 - client does not connect

### ISSUE THREAD

**Issue by mjgs** [Jigsaw-Code/outline-client#538]
Since around 6 days the iOS app is not able to connect to the Outline server I have running. Previous to this the setup had been functional for several weeks. The error in the iOS UI:

```
Sorry, an unexpected error occurred.
Quiting and restarting may help. If this happens again, please submit feedback.
```

**To Reproduce**
1. Open Outline vpn client on iOS device
2. Tap the Connect button
3. See the error at the bottom of the screen

**Expected behavior**
Expected the vpn client to connect to the Outline server, and to be able to browse web over vpn connection.

**Smartphone:**
OS: iOS Version 12.1.1
Connection-type: Wifi

**Additional context**
I noticed that I have the latest version of the [iOS client 1.2.6](https://github.com/Jigsaw-Code/outline-client/releases/tag/ios-v1.2.6) installed so I guess that got updated automatically at some stage because I didn't knowingly update any apps on my device.

The only other thing that happened around the same time was the server changed it's public ip. That has since been reverted now, and vpn connections work fine from my laptop. 

Does the iOS vpn client cache some network info in some way that could be causing the connection problem?

Is there a bug in the latest iOS 1.2.6 causing the connection issue and how should I troubleshoot?

[update: added connection type]

**Comment by alalamav** [comment]
Hi @mjgs, I'm sorry that you're experiencing this issue. I have not been able to reproduce this issue, but have a few questions that may help pinpoint the problem.

* You mentioned that the server IP changed. Are you able to connect to the server over the same WiFi network from your laptop? We only cache the connection configuration (i.e. server IP) when the device turns off while Outline is connected. Re-adding the invite may help.
* Do you see the VPN icon flash at all when connecting?
* Does the client succeed in connecting over mobile or a different network?

Lastly, if this happens again please submit feedback through the app and tag it with this issue number.

**Comment by mjgs** [comment]
Thanks for the troubleshooting suggestions. Answers and a few questions inline:

> You mentioned that the server IP changed. Are you able to connect to the server over the same WiFi network from your laptop? We only cache the connection configuration (i.e. server IP) when the device turns off while Outline is connected. Re-adding the invite may help.

Yes I can connect successfully using the client installed on my laptop using the same WIFI network. I tried generating a new key in the Outline Manager and opened it on the iOS device selecting to add a new server. Connecting to this server also errors in the same way.

> Do you see the VPN icon flash at all when connecting? Does the client succeed in connecting over mobile or a different network?

No I didn't see any vpn icon when connecting using the connect button in the iOS app. I tried another WIFI network over the past few days, in a different country as it happens, and the error persisted. When using the toggle in the iOS device "Settings>vpn>vpn configuration" a spinning icon appeared where the vpn icon usually appears. 

I tried again from the iOS app several times just now and on the 3rd attempt the connection succeeded. I haven't made any configuration changes since I created the issue. So it's been broken for about 10 days, then just as I was writing this reply the problem stopped happening.

I have a few questions:

Is it the case that if both devices are connected to the same WIFI, that no entities external to the WIFI network could differentiate between the laptop and ios client connections?

Is the networking for mobile devices different in some way? Do the iOS clients use ipv6 when on WIFI?

Could the error messages in the clients be more specific so as to be able to identify exactly if and where the connection is being blocked? Cleary posting this sort of information in a public forum like this github issue could be quite risky.

Do the servers still require the whole port range (1000-65000) to be openned in the firewall? (quite risky)

> Lastly, if this happens again please submit feedback through the app and tag it with this issue number.

Why is this necesary?

**Comment by alalamav** [comment]
Glad to hear the app is back working.

> Is it the case that if both devices are connected to the same WIFI, that no entities external to the WIFI network could differentiate between the laptop and ios client connections?

That is correct, as long as they are using the same access key.

> Is the networking for mobile devices different in some way? Do the iOS clients use ipv6 when on WIFI?

Outline's network stack is the same across platforms. How the OS handles routing is slightly different. Currently all clients are IPv4.

> Could the error messages in the clients be more specific so as to be able to identify exactly if and where the connection is being blocked?

We try to be as descriptive as possible. I have seen errors like the one you describe on development devices; generally uninstalling and reinstalling the app helps.


> Do the servers still require the whole port range (1024:65535) to be openned in the firewall?

Outline servers now support a single port for all traffic. We are working on making this configurable from the Outline Manager app.

> Why is [feedback submission] necessary?

We receive technical logs (without PII) on feedback submissions that could help us troubleshoot or diagnose the problem.

**Comment by Kyogre** [comment]
> Sorry, an unexpected error occurred.
> Quiting and restarting may help. If this happens again, please submit feedback.

I encountered same error on my ipad (iOS 14.8, outline app 1.6.0). What helped me: I deleted outline server from the app, uninstalled outline app, rebooted the ipad, installed outline app again, after that connection works again.
