### ISSUE TITLE
Mac Command-Line / Terminal Usage

### ISSUE THREAD

**Issue by markwk** [Jigsaw-Code/outline-client#550]
**Mac Terminal / Command Line Does Not Pick Up Outline Network Settings**
While Outline does a fine job routing traffic in the browser and most applications, it does not provide any coverable for the command line. Currently command line access using the local internet network and does not tunnel through outline. This creates a hole. 

**Ideal Solution: Routing All Network Traffic like a VPN**
The ideal solution here is to route traffic the same way a traditional VPN connection works. I'm not sure this is feasible using ShadowSocks protocol. But this would be ideal. 

**Alternative: Routing Instructions for Proxychain (or similar)**
[proxychains](https://github.com/haad/proxychains) and [proxychains-ng](https://github.com/rofl0r/proxychains-ng) both look like they are in the right direction and apparently work with shadow socks. So a good alternative is get something like this work and provide necessary instructions.

**Comment by alalamav** [comment]
Hi @markwk, the Outline macOS client is a full system VPN, meaning that the traffic of all applications is routed through the VPN. The only exception is traffic destined to the LAN (i.e. subnet 192.168.0.0/16), which bypasses the VPN.

>  Currently command line access using the local internet network and does not tunnel through outline.

Can you provide an example supporting this claim? For instance, when I run `curl httpbin.org/ip` in the terminal, I see the IP of the proxy server.

**Comment by markwk** [comment]
After I did a computer restart, it appears to be working now. Strange one. God of cpu restart to the rescue. Thanks @alalamav

**Comment by salakis** [comment]
> Hi @markwk, the Outline macOS client is a full system VPN, meaning that the traffic of all applications is routed through the VPN. The only exception is traffic destined to the LAN (i.e. subnet 192.168.0.0/16), which bypasses the VPN.

Is there actually an option to opt-out of the LAN bypass? Would come in handy for a lot of people I guess.
