### ISSUE TITLE
Please help. Need to regain access to outline having only the droplet and its key

### ISSUE THREAD

**Issue by vachaganbalayan** [Jigsaw-Code/outline-client#553]
Hi my working machine was stolen recently and many resources i use are secured trough static ip of the outline vpn...

I managed to find my droplet key so i can access it, but how can i reuse the existing running outline vpn on that droplet? is there some way to generate the key that i used initially to add the server?
Only options i see in outline manager is to create a new one (but then the ip will be different...)

Please help with this, im stuck.

**Comment by alalamav** [comment]
Hi @vachaganbalayan, sorry about your computer :/

You need to retrieve the API URL and certificate hash to add the server as manual server in the Outline Manager app. If you have SSH access to the droplet, you can find the management credentials at `/opt/outline/access.txt` or `/root/shadowbox/access.txt`.

The file will look something like:

```yaml
certSha256:XXXXXXXX
apiUrl:https://IP:PORT/PATH
```

Convert it to JSON (note the braces and comma):

```
{
certSha256:XXXXXXXX,
apiUrl:https://IP:PORT/PATH
}
```

Copy and paste it into the Outline Manager "advanced" server mode. Hope this helps.

**Comment by vachaganbalayan** [comment]
thanks, i regained access...

**Comment by rahmati** [comment]
Hi folks,
facing the same issue. However, `/opt/outline/access.txt` only seems to include `certSha256` now. Where should I look for `apiUrl`?

**Comment by IoannVS** [comment]
Thanks! It helped me too.

**Comment by soemoeaungmdy** [comment]
Thank you very much
