### ISSUE TITLE
client can not open when google service is not available

### ISSUE THREAD

**Issue by BarrieShieh** [Jigsaw-Code/outline-client#56]
I found that both Mac version of outline manager and client use google services like fonts.googleapis.com and fonts.gstatic.com when first time open the app. And they just went blank when these services are not accessible.

I think it's better to use these apps without any dependencies

**Comment by jab** [comment]
I suspected this might happen! Yikes! Just suggested a workaround in https://github.com/Jigsaw-Code/outline-server/issues/67#issuecomment-380509896

**Comment by alalamav** [comment]
Thanks for the feedback @BarrieShieh. This was fixed in #62.
