### ISSUE TITLE
macos 10.14.4 xcode 10.1  can not connect to server, can we upgrade to xcode 10.2?

### ISSUE THREAD

**Issue by rchen9012** [Jigsaw-Code/outline-client#563]
successfully build and run in xcode 10.1 and macos10.14.3, but after I upgraded to 10.14.4, can not connect to server any more.  current CocoaLumberJack is not working with xcode 10.2 either.  when will update the CocoaLumberJack to xcode 10.2?

**Comment by alalamav** [comment]
Hi @rchen9012, I'll update the project to Xcode 10.2 in the coming days.

**Comment by alalamav** [comment]
Quick update: we have seen reports of gomobile having App Store submission [issues](https://github.com/golang/go/issues/31628) with Xcode 10.2. We are currently testing a migration of network stack to Go, so we'll hold on to updating until the issue is resolved.

**Comment by Xuanwo** [comment]
ping, any update on this ?

**Comment by MWalid** [comment]
Is there any plan to update to xcode 11.2?
