### ISSUE TITLE
outline-client dmg file needed

### ISSUE THREAD

**Issue by houseofcode2019** [Jigsaw-Code/outline-client#586]
**Is your feature request related to a problem? Please describe.**
Thx for building these tools but seems like I can not download the
outline-client in China's App Store[1], Apple says it is not available in China.[2] 

[1] https://itunes.apple.com/cn/app/outline-secure-internet-access/id1356178125?mt=12

**Describe the solution you'd like**
Maybe the main reason is China's censorship, so could you provide the client dmg file on
your website as well? Thx!

**Comment by alalamav** [comment]
Hi @houseofcode2019, the Outline macOS client requires entitlements that can only be obtained by distributing through the Mac App Store. Please see #148 for more details and a workaround to download the app. Thanks!
