### ISSUE TITLE
UI doesn't show when building windows app yourself

### ISSUE THREAD

**Issue by OneHappyForever** [Jigsaw-Code/outline-client#588]
**Describe the issue**
Building the app for windows from source, on windows using cygwin.

When running the browser version, everything works fine, UI loads, dummy servers load etc.

However, when building the windows version and then installing it, it installs successfully but when I run it, the UI doesn't load. The windows opens, but the ui is blank. No menu bar either, just the minimize and close buttons and the logo, that it. I tried on two computers. Both fail.

No errors pop up when building, which is the strange part. No errors pop up when installing. No errors pop up when running the installed program. UI just doesn't show.

**Environment**
 - OS: Windows 10
 - Yarn version v1.15.2
 - Node.js version v.10.15.3

**Additional context**
Built on windows using cygwin.

**Comment by OneHappyForever** [comment]
It seems that now it does show but only after several minutes... could this be related to https://github.com/electron/electron/issues/11381 ?

**Comment by JonathanDCohen** [comment]
I'm seeing this too on Linux, something weird is happening inside Polymer.  I'll try to bisect the problem and figure it out

**Comment by JonathanDCohen** [comment]
I just did a `yarn run clean && yarn` which bumped the electron version from 2.0.15 to 2.0.16.  Can you try this and see what happens?  It's working for me now.

**Comment by OneHappyForever** [comment]
It works for me as well. UI loads between 1-5 seconds depending on the CPU (older pc with intel celeron takes longer).

Thanks for solving this issue!
