### ISSUE TITLE
support sharing plain access codes

### ISSUE THREAD

**Issue by dalton-chiou** [Jigsaw-Code/outline-client#59]
First, thank you.
Now to share a key, click, then we got invitation message and a link; the key is in the url and ,of course, url-encoded, which make it quite inconvenient for one to just  copy the key and paste it into Client. Can we at the same time have a plain pastable key ?

**Comment by jab** [comment]
The "escape hatch" UI proposed in https://github.com/Jigsaw-Code/outline-server/issues/89#issuecomment-381107216 would address this.

**Comment by jab** [comment]
@dalton-chiou Was this issue meant for [outline-server](https://github.com/Jigsaw-Code/outline-server) instead or in addition?

**Comment by dalton-chiou** [comment]
@jab Actually it's for outline-manager. Since the manager repo no longer available, so ...:)
