### ISSUE TITLE
Command failed: git config --get remote.origin.url

### ISSUE THREAD

**Issue by roadhub** [Jigsaw-Code/outline-client#590]
**Describe the issue**
i got a error Command failed: git config --get remote.origin.url on macos to build ios app

**Environment**
 - OS: macos mojave 10.14.4
 - Yarn 1.12.3
 - Node.js v10.15.0
 - Xcode version 10.2.1

**Additional context**
![image](https://user-images.githubusercontent.com/18000037/57012461-3fc01780-6c39-11e9-9ee8-b71caadf7461.png)

**Comment by JonathanDCohen** [comment]
Can you run the command manually and paste the output?

**Comment by roadhub** [comment]
yes, i had try it ，it is no problem. it return me the address of this repo.

![image](https://user-images.githubusercontent.com/18000037/57113272-5f108f00-6d76-11e9-9131-1c0cb1a2a357.png)
