### ISSUE TITLE
Outline Client connects on Android but not on Windows with the same key and network

### ISSUE THREAD

**Issue by smkm** [Jigsaw-Code/outline-client#593]
**Describe the bug**
From my Linux VPS, I installed the Outline Server. All of the ports from 1024:65535, tcp and udp are open using UFW. The VPS provider does not block any ports. 
In only the Windows Outline Client, it does not connect to the server and shows a message, "Access Key looks invalid, contact your admin for assistance..."
However, the Outline Manager connects to the server in the same Windows computer in the same network connected. 
In the same network, the Android client works. The IP and DNS server changed to the correct server on Android. 

**To Reproduce**
Install Outline Client on both Android and Windows and Outline Manager on Windows. 
Install Outline Server in the VPS using the custom server method and add to Outline Manager. It works. 
Add key to Android and Windows and connect to the server on both systems.
In only the Windows Outline Client, it does not connect to the server and shows a message, "Access Key looks invalid, contact your admin for assistance..."

**Expected behavior**
Both clients should connect. 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 70+, Outline Client 1.2.31, Manager 1.2.2

**Smartphone (please complete the following information):**
 - Device: Galaxy S6 Edge
 - OS: Android 7.2
 - Browser Chrome 70+
 - Version Outline Client 1.2.10

**Submit Feedback**
Please submit feedback through the app and label it with this issue number.

**Additional context**

Edit: I have moved my computer and phone from my school network to my home network and same phenomenon occurs.

**Comment by paulopais** [comment]
Some problem, no idea?
