### ISSUE TITLE
Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0.1 compiler

### ISSUE THREAD

**Issue by ITyongzhen** [Jigsaw-Code/outline-client#597]
my xcode is version 10.2.1, there is a wrong
Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0.1 compiler: /Users/yinyongzhen/Documents/yyz/ios/shadowsocks/platforms/ios/Outline/Plugins/cordova-plugin-outline/CocoaLumberjackSwift.framework/Modules/CocoaLumberjackSwift.swiftmodule/arm64.swiftmodule

**Comment by alalamav** [comment]
Hi @ITyongzhen, we haven't yet updated to Xcode 10.2. In the meantime you can upgrade your local dependency of CocoaLumberJack to the next version by updating its [Cartfile](https://github.com/Jigsaw-Code/outline-client/blob/master/third_party/CocoaLumberjack/Cartfile) to the latest version and running `carthage update`. Note that you will need to clean the project and rebuild the client (`yarn run clean && yarn && yarn gulp build --platform=ios`.

See #563 for more details.
