### ISSUE TITLE
Data Traffic Mismatch

### ISSUE THREAD

**Issue by sanasigma** [Jigsaw-Code/outline-client#604]
The "Data Transferred" info on Outline Manager isn't the same as the "Bandwidth Usage" of my VPS.
My VPS is running on Ubuntu 18.04 and I'm using Outline Manager 1.2.2 on Windows 10
![Capture](https://user-images.githubusercontent.com/36327461/58485482-b992e480-8196-11e9-9422-75e76adc34d8.PNG)
![Capture2](https://user-images.githubusercontent.com/36327461/58485483-ba2b7b00-8196-11e9-94fa-7263f96331f4.PNG)

**Comment by alalamav** [comment]
Hi @sanasigma, what cloud provider are you using? It may be the case that the measuring cycles are misaligned, which may be expected if you are installed Outline through the manual flow.

**Comment by sanasigma** [comment]
> Hi @sanasigma, what cloud provider are you using? It may be the case that the measuring cycles are misaligned, which may be expected if you are installed Outline through the manual flow.

I use Bandwagonhost. I installed outline as soon I bought the servers.

**Comment by alalamav** [comment]
I'm thinking there could be two possible explanations for the mismatch. The data transfer we display is measured as a rolling average over the last 30 days. As I said before, the window will not always align with your cloud provider's (I see it resets on 6.27.19). The Outline Manager only displays data used by Outline. If you are using this server for any other network activity, that could explain the higher usage number in the provider.

Please feel free to re-open this issue and let us know if you have any other questions.

**Comment by sanasigma** [comment]
> I'm thinking there could be two possible explanations for the mismatch. The data transfer we display is measured as a rolling average over the last 30 days. As I said before, the window will not always align with your cloud provider's (I see it resets on 6.27.19). The Outline Manager only displays data used by Outline. If you are using this server for any other network activity, that could explain the higher usage number in the provider.
> 
> Please feel free to re-open this issue and let us know if you have any other questions.

The thing is that I did a fresh installation of Outline on my VPS as soon as I purchased the VPS, so I don't know how could the traffic be so different unless the VPS is transmitting data elsewhere. When I used Vultr's servers nothing like this happened. I'm starting to think it's because of the Ubuntu version that I'm running.
