### ISSUE TITLE
Outline on Windows 10 on Surface

### ISSUE THREAD

**Issue by mohsenmottaghi** [Jigsaw-Code/outline-client#609]
**Describe the bug**
I get This error: "It looks like Outline is not properly installed.... ".
and Then I tried to install a Stable Version and test again but still not work!
I have 2 server in US and DE and works fine on IOS and Android Devises but after I update Outline on windows I have many Problems.

**Screenshots**
![ScreenShot](http://uupload.ir/files/br3h_jfaklsjflka.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1809 Build 17763.529

**Comment by marcoccy** [comment]
I have the same issue, work in android but not windows 10 surface book 2.
Tried to remove the adapter and reinstall, suggested it could not configure my system to connect to outline
![image](https://user-images.githubusercontent.com/21359289/59296645-10c9a680-8cb9-11e9-8002-95d99ea64606.png)

**Comment by mohsenmottaghi** [comment]
This bug fixed by installing new version 1.2.23
