### ISSUE TITLE
Read outline packets from ISP

### ISSUE THREAD

**Issue by sohrablou** [Jigsaw-Code/outline-client#615]
Hi
I have a Outline server. But when I connected to the server, I saw some packets blocked on ISP servers in Iran.
For example: Twitter and YouTube sites have been blocked, but other sites like the Telegram are still open.
Note: IP and server ports are not blocked.

What solution do you have for solving this problem?

regards

**Comment by saifalbadi** [comment]
what is the server operating system ?
and which operating system do you use ? ( as client )

**Comment by helnokaly** [comment]
Where is your Outline server located ?

**Comment by alalamav** [comment]
Closing due to age. Please reopen if there are further questions.
