### ISSUE TITLE
MacOS Catalina - UI doesn't show connected

### ISSUE THREAD

**Issue by SR5WKG4MWKQFWGS54AUE** [Jigsaw-Code/outline-client#619]
**Describe the bug**
On MacOS Catalina Public Beta, the app (latest version) does not turn to "connected". It will display the error message and say it's disconnected, when in fact it did connect successfully (based on the VPN info in System Preferences / ability to circumvent firewall).

**Desktop (please complete the following information):**
 - OS: MacOS Catalina Public Beta (10.15 Beta (19A487m))

**Comment by Ehco1996** [comment]
i face this problem too

**Comment by TheNullPlayer** [comment]
+1

**Comment by alalamav** [comment]
I believe this problem has been fixed in macOS Catalina 10.15.3. Feel free to reopen if the issue persists.
