### ISSUE TITLE
rebuild libshadowsocks-libev.a in ios ?

### ISSUE THREAD

**Issue by harveyHW** [Jigsaw-Code/outline-client#628]
when i run "utline-client/third_party/shadowsocks-libev/apple/libshadowsocks-libev/build_action.sh" to rebuild libshadowsocks-libev.a.
I get error in "manager.c:509:9: error: 'system' is unavailable: not available on iOS".
how can i rebuild libshadowsocks-libev.a successfully?

**Comment by harveyHW** [comment]
now I have to change some code in shadowsocks local.c 
Please!

**Comment by alalamav** [comment]
Let's track this on #594.

**Comment by harveyHW** [comment]
thax
