### ISSUE TITLE
502 Bad Gateway error at appleid.apple.com

### ISSUE THREAD

**Issue by Dotnaught** [Jigsaw-Code/outline-client#629]
**Describe the bug**
When the Outline client is active, attempting to access https://appleid.apple.com fails with a 502 Bad Gateway error.

**To Reproduce**
1. Activate Outline VPN
2. Attempt to visit https://appleid.apple.com
3. 502 Bad Gateway

**Expected behavior**
Web page should load.

**Desktop (please complete the following information):**
 - macOS 10.14.5
 - Chrome/Safari/Firefox
 - Version 75.0.3770.142/Version 12.1.1 (14607.2.6.1.1)/67.04

**Smartphone (please complete the following information):**
Same result with iPhone 8, iOS 12 using Outline and Chrome.

**Comment by alalamav** [comment]
Hi @Dotnaught, I have seen this issue as well when connecting through an Outline server hosted in a sizeable cloud provider. I believe this to be a security measure used by Apple to prevent automated access and/or abuse to their sites.

Where is your Outline server hosted?

**Comment by Dotnaught** [comment]
Digital Ocean, San Francisco.

**Comment by Omoeba** [comment]
Same for me on DO SF2. This doesn't appear to be caused by outline though.
