### ISSUE TITLE
Use virtual NIC provide Windows global VPN

### ISSUE THREAD

**Issue by studentmain** [Jigsaw-Code/outline-client#63]
We can do the same thing as OpenVPN: Use tun2socks ( or equivalent ) provide a virtual NIC. Then edit route table to redirect traffic. Then open shadowsocks local socks5 proxy.

client -> tun2socks virtual NIC -> ss socks5 proxy [-> internet -> ss server -> server]

Someone manually configured this solution on windows then successfully got a global 'VPN'. We can do this automatically.

**Comment by trevj** [comment]
@studentmain We have started rolling out version 1.2.0 of the Windows client which does what you dscribe:
https://github.com/Jigsaw-Code/outline-client/releases/tag/windows-v1.2.0

**Comment by studentmain** [comment]
Thank you. I've already downloaded it, it works well. For a long time, we
can't easily use shadowsocks for a global VPN, You solved a big problem.

trevj <notifications@github.com> 于 2018年7月26日周四 04:46写道：
