### ISSUE TITLE
Linux build 1.0.8 is broken

### ISSUE THREAD

**Issue by canesin** [Jigsaw-Code/outline-client#632]
Latest outline is broken, seems to be a electron build issue with `fs-extra`. Issue is amplified because the client automatically update itself and even when you revert it will keep breaking.

**To Reproduce**
1. Download outline for linux
2. Try to run it

**Expected behavior**
A working client.

**Screenshots**
![image](https://user-images.githubusercontent.com/353648/61541801-9c64ee80-aa40-11e9-99a1-506e88766a6c.png)

**Desktop (please complete the following information):**
 - OS: Fedora 30

**Comment by ariebrainware** [comment]
I've got the same issue,
OS: Linux Mint 19.1 Tessa

**Comment by ergxpr0xy** [comment]
got the same issue
OS: Linux Ubuntu 18.04.2 LTS

**Comment by JonathanDCohen** [comment]
We believe this has to do with out Travis config, since our local builds work fine but we've confirmed the binaries coming into our releases have this issue.

**Comment by canesin** [comment]
@JonathanDCohen thanks for looking into it, but it is concerning that the VPN client build shipped at auto-update is not being checked for reproducibility with the repo. I couldn't find a way to stop the auto-update besides blocking network calls for the release URL, would it be possible to make that a non-default behavior ?

**Comment by JonathanDCohen** [comment]
electron-update is kind of dumb, i've been trying to poke them to add backup installs for this reason.  If you update to 1.0.9 which should be released, then it should all work.

Please keep us informed if you can't get to a working version, and sorry for the problem.
