### ISSUE TITLE
Loss of internet access after waking from sleep/hibernation [WINDOWS]

### ISSUE THREAD

**Issue by Omoeba** [Jigsaw-Code/outline-client#636]
**Describe the bug**
Internet access is lost after sleeping for a long period of time (one hour should be enough) or hibernating. Outline is still shown as connected but there is no internet access.

**To Reproduce**
1. Connect outline
2. sleep/hibernate
3. wake from sleep after an hour or immediately after hibernation
4. test internet access

**Expected behavior**
Outline remains connected and working after sleep or hibernation 

**Desktop (please complete the following information):**
 - OS: Windows 10 1903

**Additional context**
This issue does not occur on ios or mac. Android was not tested.

**Comment by helnokaly** [comment]
Same happens on Linux (Ubuntu 18.04.3), after waking up from sleep, internet access is lost and when I try to disconnect from Outline, it stays on disconnecting forever and nothing happens.
A restart is required to regain internet access.

![Screenshot from 2019-08-15 11-23-33](https://user-images.githubusercontent.com/15964842/63086918-355c2c00-bf51-11e9-8913-dac12bb14b1b.png)

**Comment by alalamav** [comment]
@Omoeba, sorry for the long delay. We fixed this issue in the Windows client some months ago; I just tested on Windows 10 1903. Please feel free to reopen if the issue persists.

@helnokaly, this is a known Linux issue - we are working on getting the Linux client out of beta and this is on our backlog.
