### ISSUE TITLE
restart tun2Socks in PacketProcessor_iOS

### ISSUE THREAD

**Issue by harveyHW** [Jigsaw-Code/outline-client#637]
Now I need to restart the tun2socks
1.   [TunnelInterface setupWithPacketTunnelFlow:self.packetFlow]
2.   [TunnelInterface startTun2socks:999];
      Then tun2 start succeed
3.  [TunnelInterface stop]

When I run step 4 to restart tun2Socks after receiving "kTun2SocksStoppedNotification" notification
4.  [TunnelInterface startTun2socks:998];
I got errors:
PacketProcessor/tun2socks/system/BNetwork.c:54 Assertion failed
PacketProcessor/tun2socks/system/BTime.h:81 Assertion failed

**Comment by gaga227** [comment]
Have you run this project yet?Can you share the code with me?I can pay the Commission

**Comment by fortuna** [comment]
Is this still an issue?
What are you trying to do?
