### ISSUE TITLE
Develop & Run Cordova iOS

### ISSUE THREAD

**Issue by MWalid** [Jigsaw-Code/outline-client#646]
**Describe the issue**
I want to make some changes in the user interface, I'm trying to test it on the emulator, the command `cordova run ios` fails with error: 

`xcodebuild: Command failed with exit code 65`

Full output:
```
The following build commands failed:
	CompileSwift normal x86_64 /Users/*****/outline-client/platforms/ios/Outline/Plugins/cordova-plugin-outline/OutlineConnection.swift
	CompileSwift normal x86_64 /Users/*****/outline-client/platforms/ios/Outline/Resources/vpn/Subnet.swift
	CompileSwift normal x86_64 /Users/*****/outline-client/platforms/ios/Outline/Resources/vpn/OutlineConnectionStore.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(4 failures)
xcodebuild: Command failed with exit code 65
npm ERR! code ELIFECYCLE
npm ERR! errno 65
npm ERR! outline-client@ ios: `yarn run clean && yarn && yarn gulp build --platform=ios && cordova emulate ios`
npm ERR! Exit status 65
npm ERR! 
npm ERR! Failed at the outline-client@ ios script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/*****/.npm/_logs/2019-08-08T10_59_05_775Z-debug.log

```
**Environment**
 - OS: OSX
 - Yarn version: 1.15.2
 - Node.js version: v11.15.0

**Additional questoin**
Does outline license allow me to customise it and publish it under different app name?

I have seen that I have to be invited to to join the "Jigsaw Operations LLC" team. Is that mandatory. I can't deploy the app with my own team without being invited?

**Comment by alalamav** [comment]
Hi @MWalid, the Outline iOS client does not support running on the simulator since the NetworkExtension framework is not available. You must deploy the app to a real device.

> Does outline license allow me to customise it and publish it under different app name?

I believe so. You need to change your bundle ID and signing team/cert for both the Outline and VpnExtension targets. Xcode should be able to automatically create and download the corresponding provisioning profiles. Note that you also need to create an App Group and update it in the targets' capabilities.

Please let me know if you have any further questions.

**Comment by MWalid** [comment]
Thank you so much @alamav for your reply

**Comment by MWalid** [comment]
Hey @alalamav,

So I did some UI changes, rebuilt the the successfully using the command:

`yarn run clean && yarn && yarn gulp build --platform=ios`

However I did not find the `ipa` file to test it on my device.

Thank you,

**Comment by MWalid** [comment]
I was able to build it by opening the project located in `platforms/ios/outline` of course Xcode v 10.1 is used.
