### ISSUE TITLE
Provide macOS Image in Release Page

### ISSUE THREAD

**Issue by sabersalv** [Jigsaw-Code/outline-client#66]
The macOS Outline App is not available in the Chinese App Store. 

Can you provide outline.dmg image in Release Page?

**Comment by Azeril** [comment]
I just want a dmg file download link... sigh...

**Comment by KaminoDice** [comment]
macOS Image Release Require~

**Comment by rankun203** [comment]
We really need this final build to be downloadable dmg / pkg instead of sticking to App Stores which are managed by the gfw the same way to the internet, this doesn't make too much sense.

**Comment by rankun203** [comment]
For an app that set to fullfill the needs for "safer to break the news", this doesn't make any sense.

So yes, I think some people might need a dmg / pkg downloadable app. 

![image](https://user-images.githubusercontent.com/2988555/40870143-85f00100-665b-11e8-87a0-4331e8e0b011.png)

**Comment by thelonious89** [comment]
Outline can have the server generate and deliver OTA the config files to an iOS or MacOS device. That means then that the Outline app would not be unnecessary and instead the Apple network tools would natively support the connection just like they used to for PPTP or currently for L2TP and IKEv2. Is that possible?

**Comment by alalamav** [comment]
Thanks for the feedback. Unfortunately, the Outline macOS client must be distributed through the Mac App Store, given that it requires NetworkExtension entitlements (see answer 8 on [this thread](https://forums.developer.apple.com/thread/67613)).

**Comment by thelonious89** [comment]
It's sort of a circular loop to nowhere... if Google wants to make this a product that should be used as intended, this NetworkExtension entitlement on Apple OS makes it very very difficult. For example, I am doing some tests and sent some links to colleagues in Shanghai, Shenzhen, and Chengdu in the past week and nobody can access the files to download and try to get online. It's ironic. But unfortunately with NetworkExtension entitlement requirement, it looks like there is no other alternative but wait and see if something can overcome this in the future...

**Comment by rankun203** [comment]
I actually did download the app with an US Apple ID and then packed it to a zip file, then sent to my friend, when they drag that `Outline.app` into their `/Applications` folder and opened it.

It just works.

I'm not sure if the App Store verison will contain anything I would not like to share publicly, so I won't upload it anywhere except my close close friends and colleagues. Besides, anyone with an US Apple ID seems to be able to do that.

**Comment by bjrnio** [comment]
A colleague of mine has an Apple account, I don't, we both use Outline. How? He downloads it, compresses it (because .app files are folders and folder suck) and sends it to me.

The only caveat is that updates over the Mac App Store require his Apple ID, so somewhere in the app there is a file saying this app is his'.

If we find the way of unlinking the app from the real owner, we can have two independent people download the app from the Mac App Store, compare checksums, and if equal, compress and upload to the Release Page.

Hope it helps.

**Comment by bjrnio** [comment]
I do the same as @rankun203.

> I'm not sure if the App Store verison will contain anything I would not like to share publicly, so I won't upload it anywhere except my close friends and colleagues. Besides, anyone with an US Apple ID seems to be able to do that.

It does contain at least an indicator of ownership, because whenever there is an update it requires the original user's Apple ID password.

**Comment by thelonious89** [comment]
Thanks to both of you. A super simple solution 👍

**Comment by bjrnio** [comment]
> But unfortunately with NetworkExtension entitlement requirement, it looks like there is no other alternative but wait and see if something can overcome this in the future...

What about replacing NetworkExtension? Other VPN apps do not have said entitlement, so how difficult would it be to move to what (e.g.) Tunnelblick does?

**Comment by thelonious89** [comment]
I have been developing on Tunnelblick for many years (and donated cash to the project too). Great project, but not as graceful a solution as Outline (NetworkExtension aside).

**Comment by bjrnio** [comment]
Thanks for your contribution, I've been a Tunnelblick user for a while but I have to agree that Outline (and the ShadowSocks protocol, compared to OpenVPN) IMO, are much easier to deploy, use and maintain.

What other solutions do we have. @rankun203 said it right:

> For an app that set to fullfill the needs for "safer to break the news", this (not available in some app stores) doesn't make any sense.

We cannot afford to have people who require extreme caution on every step they take, go ahead and create an Apple account and download apps from the Mac App Store.

**Comment by bjrnio** [comment]
I understand.

**Comment by daniel-fuelx** [comment]
So is there a direct dmg file for mac ???

**Comment by serverguru666** [comment]
any news?
