### ISSUE TITLE
cpan Net::Shadowsocks 404 error

### ISSUE THREAD

**Issue by fsswzy** [Jigsaw-Code/outline-client#661]
cpan Net::Shadowsocks

 http://45.252.224.80/files/506000000E6B4769/162.255.118.133/CPAN/modules/02packages.details.txt.gz
Connecting to 45.252.224.80:80... connected.
HTTP request sent, awaiting response... 404 Not Found
 ERROR 404: Not Found.

**Comment by alalamav** [comment]
Closing due to age, feel free to reopen with more information.
