### ISSUE TITLE
Android client pass traffic trough outline when sharing connection trough hotspot

### ISSUE THREAD

**Issue by vachaganbalayan** [Jigsaw-Code/outline-client#676]
When using different machines, and travelling a lot its troublesome to set up outline every time on a new machine. Also linux outline client does not work properly, it will start, connect successfully and after 30-40 minutes you'll have no connection and only restart will help you recover....

While you may change laptops and OSes you will hardly change your mobile phone nearly as frequently. Currently android outline client works great when you only need vpn for the phone itself, but if you share connection to your laptop or other devices they use the carrier directly they do not go trough vpn... 

Please support this, as some configuration (if not by default), when this is available for most people installing outline client on laptops wont even be necessary...

**Comment by vachaganbalayan** [comment]
I have no idea why its such a complicated mess to set up a simple vpn and forward all your traffic to it in 2019... but outline did the best job so far in simplifying it, it would be great to have this too...

**Comment by alalamav** [comment]
Hi @vachaganbalayan, I can see how this would be a useful feature. However, I'm not aware of Android APIs that allow this functionality without root access. As you mentioned, the default behavior is to tether the connection through the default network, not the VPN.

We are working on a feature to re-share access keys directly from the client; maybe this would reduce the friction of installing Outline in a laptop.

Finally, do note that the Outline Linux is still in beta. We are hoping to fix the issues you describe in the near future.
