### ISSUE TITLE
Running cordova-plugin-outline in Ionic.

### ISSUE THREAD

**Issue by OCA99** [Jigsaw-Code/outline-client#677]
I'm trying to use the `cordova-plugin-outline` in Ionic. I'm running this code in the home module of my app:

```
constructor(public plt: Platform) {
    this.plt.ready().then((readySource) => {
      console.log('Ready from: ', readySource);
      setTimeout(function () {
        cordova.plugins.outline.Connection({ "method":"chacha20-ietf-poly1305", "password":"1234", "host":"127.0.0.1", "port":8388, "name":"server" });
        cordova.plugins.outline.Connection.prototype.isRunning().then(function (res) {
          console.log(res);
        });
      }, 5000);
    });
  }
```
Running `cordova.plugins.outline.Connection({ "method":"chacha20-ietf-poly1305", "password":"1234", "host":"127.0.0.1", "port":8388, "name":"server" });` successfully changes the configuration of the plugin. But when I run `cordova.plugins.outline.Connection.prototype.isRunning().then(function (res) { console.log(res); });`, outline returns error 1 (unexpected).

Where is my code failing? What exactly does error 1 mean?

Thanks.

**Comment by alalamav** [comment]
Hi @OCA99, what native platform are targetting? The plugin supports Android, iOS, and macOS.

**Comment by OCA99** [comment]
I'm targeting Android right now, testing it on a physical device.
