### ISSUE TITLE
[Windows] Restore system proxy settings

### ISSUE THREAD

**Issue by evil-shrike** [Jigsaw-Code/outline-client#68]
Outline Window client clears current system proxy settings and doesn't restore them. Even if it failed to connect. Please make it to restore proxy settings. At least on exit.

**Comment by scor4er** [comment]
+1. I'm using exceptions for specific domain names (on the Settings->Network->Proxy->Manual Proxy Setup page) and every time I re-connect these settings are cleared off.

**Comment by trevj** [comment]
@evil-shrike and @scor4er Thanks for the feedback. Yes, we're aware that Outline doesn't restore all proxy settings on exit. You might be interested to know that we're working on a "full", system-wide VPN for Windows which will address this issue. I'm afraid it may be some time until it's ready but you can follow the progress here:
https://github.com/Jigsaw-Code/outline-client/issues/63

**Comment by trevj** [comment]
@evil-shrike @scor4er We have started rolling out a new release - 1.2.0 - of the Windows client which should address this (it configures a VPN for the whole system, not just browsers).
