### ISSUE TITLE
iOS update fails when connected through Outline

### ISSUE THREAD

**Issue by helnokaly** [Jigsaw-Code/outline-client#684]
**Describe the bug**
iOS update fails when connected through Outline

**Expected behavior**
iOS updates without needing to disconnect from Outline.

**Screenshots**
![image](https://user-images.githubusercontent.com/15964842/67088265-fe023980-f1a4-11e9-9cac-ec752955cffe.png)

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 13
 - Version: 1.3.2

**Comment by JonathanDCohen** [comment]
So the update downloads correctly but refuses to install?  If you turn off Outline does it work without re-downloading?  Why do you need to be on Outline to install an OS update?

**Comment by helnokaly** [comment]
@JonathanDCohen correct.

I use Outline 24/7 and don't like to bother turning off and on for certain tasks. And for non power user friends who I advice them to use Outline VPN 24/7, usually have no clue why update is failing to install.

Does this issue happen with all VPNs other than Outline or is it unique to Outline?

**Comment by alalamav** [comment]
@helnokaly, this could be related to #629. Depending on where you are hosting the server, Apple may be denying its requests.
