### ISSUE TITLE
FaceTime calls fails when both users are connected to Outline

### ISSUE THREAD

**Issue by helnokaly** [Jigsaw-Code/outline-client#685]
**Describe the bug**
FaceTime calls fails when both users are connected to Outline. It rings but fails to connected after answering.
It works if just one is connected to Outline and the other is not.

Note: Only tested both clients connected to same Outline server, don't have a different server to test.

**Expected behavior**
FaceTime calls should work if both users are connected to Outline.

**Smartphone (please complete the following information):**
 - Device: iPhone X, iPhone 5S
 - OS: 13, 12
 - Version 1.3.2

**Comment by JonathanDCohen** [comment]
I wonder if this has to do with https://developer.apple.com/support/ipv6/ ?  @alalamav is more familiar with our networking stack.  Do regular calls work?

**Comment by helnokaly** [comment]
@JonathanDCohen thanks for testing. Are you able to test but with phones connected to same Outline server and see if you can reproduce this issue.

**Comment by JonathanDCohen** [comment]
We tried that as well and everything worked fine for us.

**Comment by helnokaly** [comment]
@JonathanDCohen thanks for testing, I will close the issue since it is not reproducible on your end.
