### ISSUE TITLE
Outline Client Disconnected Immediately on windows with hyper-v

### ISSUE THREAD

**Issue by enif-lee** [Jigsaw-Code/outline-client#697]
**Describe the bug**
After installed docker desktop for windows, Outline was not working.

**To Reproduce**
1. Install Docker Desktop (or Enable Hyper-V Setting)
2. Click Connecting to own server
3. Disconnected immediately.

**Expected behavior**

**Screenshots**
![GIF](https://user-images.githubusercontent.com/9916002/68068525-183d3980-fd99-11e9-96bd-913ecf6f2863.gif)
![image](https://user-images.githubusercontent.com/9916002/68068529-1ffcde00-fd99-11e9-80d1-2997fda21852.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.2.34

**Comment by enif-lee** [comment]
it's seems to duplicate with #611

**Comment by angao** [comment]
it also happens on macOS Catalina 10.15.1

**Comment by climba03003** [comment]
Suddenly, Windows 10 can connect to outline server with Hyper-V turns-on.

**Comment by DanonekTM** [comment]
Any updates on this issue?

**Comment by fortuna** [comment]
Is this still an issue?

What are you trying to run on hyper-v, the server or the client?

**Comment by studentmain** [comment]
Hyper-V may randomly reserve some ports, other program can't listen on them. If client listening port is hardcoded, it may cause problem.

**Comment by fortuna** [comment]
I still don't understand what the issue and the request is.

Can @studentmain or @enif-lee clarify what's the architecture you are trying to set up?

**Comment by studentmain** [comment]
According to his network setting, I guess he's running Outline-Client on Hyper-V enabled Windows 10 host (not in Hyper-V VM, in physical machine).

I just mention a possible cause here. shadowsocks-windows had a simillar problem before.

**Comment by fortuna** [comment]
So the server is running on a completely different machine, and the client is running on a windows machine that is also running hyper-v. Running hyper-v makes the client fail to connect. Is that right?

I don't understand how hyper-v would prevent the client from connecting to an external server, since on every connection the system will give the client an unallocated port that it can use.

The only static port is the external server port.

**Comment by studentmain** [comment]
> So the server is running on a completely different machine, and the client is running on a windows machine that is also running hyper-v. Running hyper-v makes the client fail to connect. Is that right?

True

> I don't understand how hyper-v would prevent the client from connecting to an external server, since on every connection the system will give the client an unallocated port that it can use.

Hyper-V reserved port is unallocated if you check it via something like netstat, but when you listen on it, it will give you WSAEACCESS (not WSAEADDRINUSE) error. https://github.com/shadowsocks/shadowsocks-windows/issues/1835#issuecomment-453528715 (in Chinese) and https://gist.github.com/strayge/481a77d31a94e133a76662877b1a90ca has some detail. But I'm not sure if it is his problem either.

**Comment by fortuna** [comment]
@enif-lee Did you install Outline before or after you enabled hyper-v?
It seems you need to enable hyper-v before installing Outline: https://github.com/Jigsaw-Code/outline-client/issues/848

I'll close this bug in favor of the one linked above.
