### ISSUE TITLE
Autorun Error

### ISSUE THREAD

**Issue by xmha97** [Jigsaw-Code/outline-client#699]
### Describe the bug
Hello, Outline team.
I using the Outline version 0.0.0.0+9307ddc ([daily-2019-11-04](https://github.com/Jigsaw-Code/outline-client/releases/tag/daily-2019-11-04)) and want to report an error.
When I don't turn off the VPN and restart my PC, the app will automatically run with this error.
Please fix it.
Regards.

## Possible Fix
I think if you disable the autorun feature, this problem doesn't occur.
Also, I don't like autorun feature, Please add a config to disabling it.

### Debug log
```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: net::ERR_HTTP_RESPONSE_CODE_FAILURE

[OK]
```

### Screenshots
![Outline Error Message Screenshot](https://user-images.githubusercontent.com/23485114/68497546-0a405a80-026a-11ea-8173-342ecd42006a.png)

**Comment by amirrammari** [comment]
Now I have to disable Outline startup
![Windows 10\Task Manager\Startup Tab\Outline item](https://user-images.githubusercontent.com/23485114/68522180-a6e01800-02bd-11ea-896a-20ffdc83d28f.png)
