### ISSUE TITLE
sorry,we could not configure system to connect to outline.please try running the installer again.

### ISSUE THREAD

**Issue by xulinbao** [Jigsaw-Code/outline-client#714]
os: windows 10 64bit
outline-client version: 1.3.1

error:
sorry,we could not configure system to connect to outline.please try running the installer again.
if you still cannot install outline,please get in touch with us and let us know that the TAP device could not be installed

C:\Program Files (x86)\Outline>add_tap_device.bat
Creating TAP network device...
tapinstall failed.
Could not create TAP network device.

**Comment by parrygit** [comment]
i got same problem. 1.3.1 version.

**Comment by 123ysys** [comment]
I have the same problem. Uhhh...

**Comment by parrygit** [comment]
i used this version : https://github.com/Jigsaw-Code/outline-client/releases/tag/windows-v1.2.34
is work.

**Comment by superior68** [comment]
i have same problem with outline 1.3.1 runing on windows7 32it
also i reinstall this version with 1.2.34 and it be installed but cannot connect to my server.
version 1.3.1 has working well on another PCs that run windows 8.1 64 bit
help me please.

**Comment by kevy8707** [comment]
same problem here, should be the source problem, I had to install the old version then upgrade to latest one.

**Comment by ganshuyu** [comment]
Reproducing same issue on my Windows7 64bit with 1.3.10. I even tried to reinstall my Windows, issue still. :(

**Comment by yetangye** [comment]
Same issue, Windows 10 1909, 64 bit, Outline client is 1.3.2

**Comment by GarryLau** [comment]
> i used this version : https://github.com/Jigsaw-Code/outline-client/releases/tag/windows-v1.2.34
> is work.


It works. thx.

**Comment by JonathanDCohen** [comment]
You all are great, thanks for helping support each other.  @alalamav has been working tirelessly to find a reliable fix for this issue (https://github.com/Jigsaw-Code/outline-client/pull/756 for instance)

**Comment by neyron163** [comment]
any update? I have the same issue and 1.2.34 also does not work for me

**Comment by authentic-killer** [comment]
1 GO TO DEVICE MANAGER AND UPDATE THE DRIVER FOR TAP-Windows Provider IN NETWORK ADAPTERS IF ALREADY THERE. IF IT IS NOT SHWOING IN DEVICE MANAGER THEN RUN OUTLINE CLIENT WITH RUN AS ADMINISTARTIVE OPTION AND AGAIN CHECK IN DEVICE MANAGER NOW IF IT SHWOING THEN UPDATE THE DRIVER WITH SERACH AUTOMATICALLY FOR DRIVER OPTION.
2. GO TO  Control Panel\Network and Internet\Network Connections AND RENAME "tap-wINDOWS ADAPTER" AS A "outline-tap0". 
3. AGAIN REINSTALL THE OUTLINE CLIENT WITH RUN AS ADMINISTARTOR OPTION

**Comment by Klediramo** [comment]
I still failed though I had tried any method I saw, could some guys help me?

**Comment by upsoftt** [comment]
> 1 GO TO DEVICE MANAGER AND UPDATE THE DRIVER FOR TAP-Windows Provider IN NETWORK ADAPTERS IF ALREADY THERE. IF IT IS NOT SHWOING IN DEVICE MANAGER THEN RUN OUTLINE CLIENT WITH RUN AS ADMINISTARTIVE OPTION AND AGAIN CHECK IN DEVICE MANAGER NOW IF IT SHWOING THEN UPDATE THE DRIVER WITH SERACH AUTOMATICALLY FOR DRIVER OPTION. 2. GO TO Control Panel\Network and Internet\Network Connections AND RENAME "tap-wINDOWS ADAPTER" AS A "outline-tap0". 3. AGAIN REINSTALL THE OUTLINE CLIENT WITH RUN AS ADMINISTARTOR OPTION

this work for me

**Comment by paigusov** [comment]
> 1 GO TO DEVICE MANAGER AND UPDATE THE DRIVER FOR TAP-Windows Provider IN NETWORK ADAPTERS IF ALREADY THERE. IF IT IS NOT SHWOING IN DEVICE MANAGER THEN RUN OUTLINE CLIENT WITH RUN AS ADMINISTARTIVE OPTION AND AGAIN CHECK IN DEVICE MANAGER NOW IF IT SHWOING THEN UPDATE THE DRIVER WITH SERACH AUTOMATICALLY FOR DRIVER OPTION. 2. GO TO Control Panel\Network and Internet\Network Connections AND RENAME "tap-wINDOWS ADAPTER" AS A "outline-tap0". 3. AGAIN REINSTALL THE OUTLINE CLIENT WITH RUN AS ADMINISTARTOR OPTION

It says that the driver is up to date. connection with the correct name. but the error still remains.

**Comment by g-struchin** [comment]
an error occurs when running the command

```
PS C:\Program Files (x86)\Outline> .\add_tap_device.bat
Интерфейс с таким именем не зарегистрирован на маршрутизаторе.

Creating TAP network device...
Device node created. Install is complete when drivers are installed...
Updating drivers for tap0901 from C:\Program Files (x86)\Outline\tap-windows6\OemVista.inf.
UpdateDriverForPlugAndPlayDevices failed, GetLastError=-536870325
tapinstall failed.
Could not create TAP network device.
```
