### ISSUE TITLE
Using Outline with WSL

### ISSUE THREAD

**Issue by florianmonfort** [Jigsaw-Code/outline-client#715]
Hi,

Is there a way to set up Outline on Windows to apply the connection to WSL as well?

As reported here there is a way to do this with Shadowsocks Windows client:

https://github.com/shadowsocks/shadowsocks-windows/issues/2686

but not sure if can do the same using Outline's Windows client? I cannot find the settings that specify which port is being used by the client unlike in the Shadowsocks windows client.

**Comment by JonathanDCohen** [comment]
I know this is a little old but to answer your question, we use local port 1081.

No idea about WSL, we aren't really able to test it at the moment.  Were you able to have any luck?

**Comment by florianmonfort** [comment]
> I know this is a little old but to answer your question, we use local port 1081.
> 
> No idea about WSL, we aren't really able to test it at the moment. Were you able to have any luck?

@JonathanDCohen  No worries haha, well I'm outside of China right now  (coz.. you know.. 😂) so not using my Outline server much at the moment.

As soon as I'm back I'll test again and let you know

**Comment by florianmonfort** [comment]
@JonathanDCohen follow up from my side, I've done some testing and it does seem to work with WSL, we can close this:

![image](https://user-images.githubusercontent.com/1446429/76722270-d1ffda00-677d-11ea-8d0c-06b21a3f3b6f.png)

**Comment by JonathanDCohen** [comment]
This git fetch was done through Outline?  

And out of curiosity, could you share your setup so we can point other users here who are trying to do the same thing?

**Comment by florianmonfort** [comment]
> This git fetch was done through Outline?
> 
> And out of curiosity, could you share your setup so we can point other users here who are trying to do the same thing?

@JonathanDCohen I'm not sure how to do a git fetch "through" outline, all I did is the following:

- On Windows 10 Version 1909, launch [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701)
- Launch Ubuntu command prompt;
- cd to folder where git repository is (SSH pull method);
- First try git fetch when Outline windows client is not connected to outline server
 --> My git fetch is slow (I am in China);
- Second try git fetch when Outline windows client is connected to outline server
 --> My git fetch is fast;

So I am "assuming" that the Windows Terminal, Ubuntu or git process is routing the connection through the VPN that the Outline windows client is creating. Though how it does this, I could not tell you.

**Comment by JonathanDCohen** [comment]
If you're connected it should work.  We work at the level of the routing table so whatever wiring WSL is doing to connect with Windows I think is independent.  That's awesome to hear!  I'm going to close this issue as fixed, please feel free to re open.
