### ISSUE TITLE
Tab device won't configured in Windows

### ISSUE THREAD

**Issue by Seia-Soto** [Jigsaw-Code/outline-client#722]
I freshly installed Windows via Windows reset function in 'Settings > Recovery' with removing all files. After the installation, I tried to install outline but outline installer shows me an error that failed to install the tab device.

**To Reproduce**
1. Download an Outline Windows Installer from official outline website.
2. Run the file as an administrator to install.

**Expected behavior**
The outline installer should add a new tap device called outline-tap0 and show me that outline is installed correctly.

**Screenshots**
- Error message
![image](https://user-images.githubusercontent.com/30369714/71966168-70cefe00-3244-11ea-9551-2d32379c2be6.png)
- Installer details
![image](https://user-images.githubusercontent.com/30369714/71966403-d7ecb280-3244-11ea-9dc8-39e0cc5abd04.png)

**Desktop:**
 - OS: Windows 10 1909
 - Browser: Downloaded via Chrome 72
 - Version: 18363.535
 - Anti Virus: Norton

**Comment by c0state** [comment]
This *might* help: https://github.com/Jigsaw-Code/outline-client/issues/524#issuecomment-590158981

**Comment by Seia-Soto** [comment]
After searching the internet a lot, now I can find that this issue can be resolved in some cases.

# Removing the Outline Client application first

1. Open `Settings App` and go to `Apps`.
2. Find `Outline` application and remove.

# Removing the Outline's TAP device (Windows-only)

1. Open `network and sharing center`. (`Settings App` > `Network..` > `Network and Sharing Center`)
2. Click `change adapter settings` and find `Outline TAP device`.
3. Open `Properties` of the adapter.

![image](https://user-images.githubusercontent.com/30369714/76550537-a064e580-64d5-11ea-9820-ad7e50c47465.png)

4. Open `Configure` tap of the adapter in `Properties` tab.

![image](https://user-images.githubusercontent.com/30369714/76550754-fb96d800-64d5-11ea-8bae-3a2ed466469d.png)

5. Go to `Driver` tab and remove it (including softwares).

![image](https://user-images.githubusercontent.com/30369714/76550831-15d0b600-64d6-11ea-80c1-c3ef457df055.png)

![image](https://user-images.githubusercontent.com/30369714/76550858-22eda500-64d6-11ea-9fc3-39305df13443.png)

# Alterantives & Possible fixes

## Running the installer with `compatibility mode` of Windows.

In some cases, I can see that people installing Outline with the compatibility mode of Windows.

You can set the compatibility mode of the file by using right-clicking the file and click properties.

![image](https://user-images.githubusercontent.com/30369714/76551192-aad3af00-64d6-11ea-92ad-7359038f5f5b.png)

## Using Shadowsocks-Windows client (Portable)

1. Get the sharing code from Outline Manager and get the access code.

The format: `ss://BASE64TOKEN@ADDRESS:PORT/?outline=1`

2. Copy the BASE64TOKEN and decode it. Then, you'll get the following format.

The format: `EncryptionMethod:PASSWORD`

3. Fill the blanks.

![image](https://user-images.githubusercontent.com/30369714/76552184-0e5ddc80-64d7-11ea-9020-4de691dd45ec.png)

4. Set the mode to `global` or `PAC` in minimal to make Shadowsocks work in your system.

![image](https://user-images.githubusercontent.com/30369714/76553520-8926f780-64d7-11ea-8452-c1a516bff4f3.png)
