### ISSUE TITLE
Outline Client Error - Windows10 Home 

### ISSUE THREAD

**Issue by itmuji** [Jigsaw-Code/outline-client#736]
OS - Windows10 Home 1909 Version 64bit
Install Clinet Version - 1.3.2 / 1.2.7

Error message 
- Sorry, we could not configure your system to connect to Outline.
   Please try runnnig the installer again. If you still cannot install Outline, please get in
   touch with us and let us know that OutlineService failed to install

I can't use Outline because I installed it and got an error.
I want to learn how to solve it.
Please.

TAP Device Setup ended normally.

**Comment by ChickenRiceWithEgg** [comment]
hello, i had the same problem, how didi you solve it ?
