### ISSUE TITLE
Issue during windows build

### ISSUE THREAD

**Issue by norbinto** [Jigsaw-Code/outline-client#74]
Hello, i try to build the project on windows, follow the tutorial, and in the end after i cloned the master branch, my application can not run on the devices (neither android and web).
I get an issue. I added the 2 picture about it.
Can anyone help me why i get this exception?
![untitled2](https://user-images.githubusercontent.com/8628861/39239059-7108aae2-48b2-11e8-9337-2344a643adc8.png)
![untitled](https://user-images.githubusercontent.com/8628861/39239062-713bb5c2-48b2-11e8-8884-7c0028d67b84.png)

**Comment by alalamav** [comment]
@norbinto thank you for reporting this issue. What error do you get when you build the application for the browser (`yarn gulp build --platform=browser --watch`)?

**Comment by norbinto** [comment]
Thanks, I do not get error. During the yarn dependencies and build etc. No
errors.
I get error only during running. By the way I get the same. Today I will
send you a picture about it (it will be the same in the chrome browser).

**Comment by norbinto** [comment]
Ok, probably something bad happens during the build, environment.js is empty. I downloaded your apk, and it was not empty. ..

**Comment by trevj** [comment]
@norbinto Thanks for trying to build Outline! I'm afraid we don't normally build APKs on Windows; in fact, we normally build our APKs with the help of Docker, using an image we build ourselves which has just the right SDKs installed. Though we haven't tested it, this technique will probably work on Windows too:
https://github.com/Jigsaw-Code/outline-client#building-for-android-with-docker

**Comment by norbinto** [comment]
@trevj  Thanks, i tried it with docker too, same error ( By the way your build.sh is not running under windows well, you need some modification for example \ and /). Thanks for your help, i gave it up. Good luck
