### ISSUE TITLE
 Starting 'transpileBowerComponents'...  The following tasks did not complete:

### ISSUE THREAD

**Issue by 174high** [Jigsaw-Code/outline-client#750]
[Done src/www/build]
[15:39:47] Finished 'buildWebApp' after 5.73 s
[15:39:47] Starting 'copyBabelPolyfill'...
'node_modules/babel-polyfill/dist/polyfill.min.js' -> 'www/babel-polyfill.min.js'
[15:39:47] Finished 'copyBabelPolyfill' after 238 ms
[15:39:47] Starting 'browserifyAndBabelify'...
[15:39:49] Finished 'browserifyAndBabelify' after 1.99 s
[15:39:49] Starting 'transpileBowerComponents'...
[15:39:49] The following tasks did not complete: build, <series>, <series>, transpileBowerComponents
[15:39:49] Did you forget to signal async completion?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by 174high** [comment]
I meet this problem . could you fix it ?

**Comment by JonathanDCohen** [comment]
Hey there!  Could you give us some information like what platform you're running, what commands you built, or anything else interesting about your development environment?

**Comment by yangyide** [comment]
> Hey there! Could you give us some information like what platform you're running, what commands you built, or anything else interesting about your development environment?

Hello, I am also meet this problem and I want build ios client.  My environment:


**Environment**

OS: Ubuntu 20.04 LTS
Yarn version: 1.22.4
Node.js version: 10.19.0
Gulp version: CLI version: 2.2.1

**Comment by JonathanDCohen** [comment]
I think your issue is that you're trying to build the ios app on Linux.  Although I can't reproduce your exact error, you would eventually reach an error that xcodebuild isn't installed.

**Comment by Mkurbanov** [comment]
After 3 hours i solved this problem.
Just type this to console :D
`bower install --allow-root`

**Comment by fortuna** [comment]
It seems the issue has been solved.
