### ISSUE TITLE
Client still connected vpn when stop server

### ISSUE THREAD

**Issue by oncul** [Jigsaw-Code/outline-client#752]
**Describe the bug**
Hi,
I have a problem with drop connection. I need to drop connected user. If i remove connected access key, client side status shows stay connected.
Client side doesnt know access key no longer valid and still connected.
Also i tried to outline server turn off got same result.

I tried mac and ios clients got same problem.

Do you have any solution for this ?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macos
 - Version 10.14.6

**Smartphone (please complete the following information):**
 - Device: iphone X
 - OS: ios 13.3.1

**Comment by alalamav** [comment]
Hi @oncul, Outline clients don't communicate with Outline servers beyond proxying. This means that when you delete an access key, the client cannot update the UI to reflect this. However, no new connections can be established, as the key no longer exists. Even if the UI status says "connected", the device will apear to have lost internet connectivity. When the client disconnects, it will not be able to re-connect.

Please let me know if this answers your question or if you are seeing different behavior than what I described.

**Comment by oncul** [comment]
Thanks @alalamav, i think i need to make custom impelementation for this situation. 

Do you have any solution?

**Comment by alalamav** [comment]
@oncul - Outline clients perform a series of connectivity tests when connecting. These are currently platform-specific and include reachability, authentication, and UDP support checks. You could run these checks periodically to assess whether a key has lost server access and update the UI. However, this may increase fingerprintability of the client/server. You also need to watch out for transient network failures that may result in false positives.
