### ISSUE TITLE
Failing to connect

### ISSUE THREAD

**Issue by danielntech** [Jigsaw-Code/outline-client#76]
I'm encountering problems when connecting to my node, I've determined it is because if inner network blocks that I can't fix, is there any specific port I should open on the client side or any specific block to remove so I can use the software properly?

![image](https://user-images.githubusercontent.com/16944217/39404349-440f5f8c-4b9a-11e8-915c-8a21246b0a65.png)

I've completely confident this is caused by a restriction within my network, just not sure which one. It is not a private network, but my school network.

Thanks, I appreciate every answer!

**Comment by shaomeng** [comment]
I try a few more times when I see this msg, and usually it connects eventually :) Not ideal though but it gets you online!

**Comment by trevj** [comment]
@danielntech Thanks for the feedback! I'm sorry you're having trouble connecting - we are aware this is an issue on certain networks. Each Outline access key uses a random port; you can determine the port by opening the invite URL in a browser and examining the `ss://` link (the port is towards the end, immediately after the server's IP address).

**Comment by danielntech** [comment]
So what your'e saying is that I can connect to Outline manually each time by a port of my choice? For instance 443?

**Comment by immartian** [comment]
Is it possible to show such an error explicitly?
