### ISSUE TITLE
Net error

### ISSUE THREAD

**Issue by MingqianYang** [Jigsaw-Code/outline-client#768]
**Describe the issue**

- Aftering runing `yarn do src/electron/package_windows`, there is a problem as the screenshot below.
- And why the background has nothing?

**Environment**
 - OS: [Win10]
 - Yarn version [1.10.1]
 - Node.js version [12.16.1]

**Additional context**
![image](https://user-images.githubusercontent.com/15353430/77396944-c99c4480-6df8-11ea-8dfa-e612ee7e3c19.png)

**Comment by JonathanDCohen** [comment]
Is there anything in the Developer console?

**Comment by joeytwiddle** [comment]
I believe this was fixed in #781

**Comment by fortuna** [comment]
Stale issue. Let us know if the fix from #781 didn't fix this.
