### ISSUE TITLE
Upgrade to ChromeOS Causes IP address to be exposed

### ISSUE THREAD

**Issue by barthawk** [Jigsaw-Code/outline-client#78]
I had OutlineVPN installed and working on my Asus Chromebook flip.  I had to perform a Powerwash and install Increased Security to get it to work-before that it would expose my home IP address on sites like whatismyip and ipinfo.io  However, after I installed the latest stable chromeos the symptom of exposing the home IP address returned. I no longer have the option to increase security.

**Comment by trevj** [comment]
@barthawk Thanks for trying Outline. Sorry you've been having problems - and apologies for the slow reply. Can I please ask you to submit feedback using the Outline app (making sure to include your handle)? If you do this immediately after trying to connect, it may help us debug the issue.

**Comment by barthawk** [comment]
@trevj - I had to do another powerwash and reinstall the ChromeOS (for other reasons than that related to Outline), Outline VPN connected without issues and my IP address is shown as the Digital Ocean IP address on whatismyip after I connect.

Thanks for checking back in and thanks for a really easy to install and use VPN software.  My daughter has been using it extensively as she is on an extended road trip and using many public wifi spots. 

Bart
