### ISSUE TITLE
Need some help regarding the setup and custom build.

### ISSUE THREAD

**Issue by iamsid47** [Jigsaw-Code/outline-client#786]
**The issue**
Hi there, I'm Siddhesh.
I am a certified programmer and I have decided to make my own commercial VPN using the techniques which you have used while programming for Outline. 

I came across your organization's GitHub page and saw all the resource provided by you. But I am kind of getting confused that which repositories have you actually used to build the complete Server and Client (of Outline.) In short, I am not correctly understanding the file structure of your repositories (even after reading the Readme.md file.)

In a nutshell, can you just explain ne that how are those things actually working with each other and what actually goes where? 
If possible, I would be glad to know that how can I implement ths in my project.

Some quick thoughts and ideas about my project: I am developing a commercial VPN in which I want to implement Outline technology in some or the other way. What I mean is that I'll be developing an app (cross-platform), using Flutter (iOS and Android) and Electron (Windows & MAC). So, this app will connect connect to the server which I will setup using the Outline manager.

It will be something like this:

SERVER (on GCP)
|
|
|>> Connect with my Flutter application
|
|>>Connect with my Electron application

In one of your Readme.md files, I saw that your organization has used Polymer, Electron and Cordova for making cross platform apps. So I just wanted to ask which things actually connect where. (I mean that I am not getting tthat how the connectivity is working between the Client and the Server). So, if you would help me in this project, I'd be really thankful.

**Environment**
 - OS: Windows 10 (development) , Android 8.1 (testing)
 - Yarn version 1.22.4
 - Node.js version 12.16.3

**Comment by joeytwiddle** [comment]
The front-end is in `src/www`. You will find Polymer and Electron here.

The interface between the front-end and the platform-specific code is in `server.ts`. Specifically `start()`, `stop()`, `checkRunning()` and `checkReachable()`.

When using cordova, `outline_server.ts` fulfils this interface, by calling down to `cordova.plugins.outline.Connection.*()`. You can find that plugin, and **the Android/Apple code, in `/cordova-plugin-outline`**

For Windows, macOS and Linux, electron is used and cordova is not. In this case, `windows_connection.ts` fulfils the interface. It passes a message to `src/electron/index.ts` and that calls down to `process_manager.ts` which communicates with `ssLocal` and `tun2socks` which are either native libraries or native executables. In this case **the native code lives in `/third_party`**

At my workplace, we tried to make our lives simple by changing only the UI and keeping everything else working in Outline as it does now. (Still using cordova and electron.)

But if you are planning to work in flutter, then you may prefer to try to extract just the native parts.

**Comment by Siddhesh43** [comment]
Thanks for the help. It really helped me out!
