### ISSUE TITLE
Update to WKWebView

### ISSUE THREAD

**Issue by Rezhe** [Jigsaw-Code/outline-client#787]
> [The App Store will no longer accept new apps using UIWebView as of April 2020 and app updates using UIWebView as of December 2020.](https://developer.apple.com/news/?id=12232019b)

When will Outline Updated to WkWebView? and does Outline need to rewrite the UI?

**Comment by alalamav** [comment]
Thanks for bringing this up to our attention. I believe we should be able to upgrade to WkWebView before the deadline without too many UI changes. We need to investigate if any cordova plugins are referencing UIWebView and update the [WebView preferences](https://cordova.apache.org/howto/2020/03/18/wkwebviewonly.html) in our end.

**Comment by fortuna** [comment]
@alalamav is this done for both iOS and macOS?

**Comment by alalamav** [comment]
cordova-osx v6.0.0 (latest at this time) has not yet updated to WKWebView and still uses WebView. There is no requirement at this time for macOS apps to switch to WKWebView, only for iOS.
