### ISSUE TITLE
Outline Icon Died

### ISSUE THREAD

**Issue by danielntech** [Jigsaw-Code/outline-client#79]
![image](https://user-images.githubusercontent.com/16944217/39469125-6b5e2cfc-4d3f-11e8-9ca0-edbc208fe2d2.png)

The icon just died in my taskbar, looks like it was drawn on using paint.

Anyone has an idea why it happend?

**Comment by trevj** [comment]
@danielntech Thanks for trying Outline. Apologies for the slow reply. Which platform are you using?

**Comment by danielntech** [comment]
I have no idea if it still happens as I stopped using outline ages ago. It was on WIndows 10 x64 Professional.
