### ISSUE TITLE
Add domain or SNI hostname or http request on client

### ISSUE THREAD

**Issue by ingnelson** [Jigsaw-Code/outline-client#790]
**Additional context**
Hello .
Is there a way to add a domain or SNI host name or a http request line on client ? 
This way i can bypass my firewall , because the firewall will think i am visiting that allowed domain or website. 
As i see outline use a RTP and it do not send a HTTP request , but can you add a listen local proxy and port to first sent a HTTP request with GET header and connect to outline via local port ?
Or just a option to add a HTTP request  , example : 
GET www.example.com/assfjr HTTP/1.1

so the connection would be :

client
http request HTTP  > outline RTP

Server vps
outline server .

i will wait your answer.

![image](https://user-images.githubusercontent.com/6626845/81984411-f9deb300-95f1-11ea-9af8-de5dd64b9c8e.png)

**Comment by JonathanDCohen** [comment]
Sorry for taking so long.

I don't think we use RTP, our server code is at https://github.com/Jigsaw-Code/outline-ss-server

Shadowsocks can be transported over TCP or UDP https://shadowsocks.org/en/spec/Protocol.html

Is this a university firewall or something?  You have no access to change it?  Or is this a firewall setting on your server which you can control?  There's no way for us to send an HTTP request to the proxy server as it doesn't speak HTTP.

**Comment by fortuna** [comment]
Outline is not intended to modify the user traffic. It tunnels your traffic, so the network won't see the domains you are accessing.
