### ISSUE TITLE
Skipping the KEY

### ISSUE THREAD

**Issue by iamsid47** [Jigsaw-Code/outline-client#792]
**Description**
Actually, I am building my own vpn using the Outline Source code. I am using Flutter to develop the client app and I will be using the Outline Manage as it is. But I wanted to ask that can I skip the KEY part. That means When you connect to the server using a client, it shhould not ask for a key, it should directly connect. So, is there a way for doing that?

**Environment**
 - OS: Windows 10, Android 8.1 (Testing)
 - Yarn  v1.22.4
 - Node.js v10.16.3

**Comment by joeytwiddle** [comment]
You can include the password in the `ss://...` shadowsocks URI. Does that help?

https://shadowsocks.org/en/config/quick-guide.html#qrcode

**Comment by iamsid47** [comment]
@joeytwiddle Okay, so you mean that I should create a function which connects the device to the server by automatically putting in the ACCESS KEY, right?

**Comment by joeytwiddle** [comment]
@iamsid47 Yes you need to give Outline the address of a shadowsocks server.

When you have the hostname, port, and optional password, you can use the code on that page to generate the `ss://...` address.

**Comment by iamsid47** [comment]
@joeytwiddle Thanks for the help! Also, just a small question that how do I connect my Flutter application to the server. I'm really trying to figure this out but just don't know how to use it. I am having just one button on my Flutter app screen which is the 'Connect' button. So, can you help me with in?
