### ISSUE TITLE
yarn do src/electron/build --> /build/electron

### ISSUE THREAD

**Issue by mulsaem** [Jigsaw-Code/outline-client#793]
OS : Windows

yarn do src/electron/build

This file is created after execution.
But I don't know how to do it.

**Comment by joeytwiddle** [comment]
I guess you are referring to this documentation: https://github.com/Jigsaw-Code/outline-client#windows

That only does part of the build process.

For a full build (to build an `exe` file), do:

```
yarn do src/electron/package_windows
```

**Comment by alalamav** [comment]
I have updated the README with the latest Electron build and package in #795. @mulsaem, I'd only add that you can find the output of packaging in `/build/electron/dist`.

@joeytwiddle, I'm interested to understand what about the Electron v7 upgrade (per the commit you referenced: 9307ddc) is not working for you. 

Thanks!
