### ISSUE TITLE
[Feature Request] Add "proxy by rule" feature

### ISSUE THREAD

**Issue by obhasqr** [Jigsaw-Code/outline-client#8]
## Feature description

Add rules for URL/IP addresses so that they can connect **DIRECT**ly or through the **PROXY**, or even **REJECT** to connect.

### Why?
For some local applications, we may need to set them as "direct connect" due to speed or regional restrictions or security(they may collect VPS information and provide it to government agencies) reason and only need to proxy some blocked addresses.

For example, some people in China maintain a list of addresses blocked by the government, called gfwlist(https://github.com/gfwlist/gfwlist).
And some rules for 3rd ss/v2ray iOS client shadowrocket, like https://github.com/lhie1/Surge/blob/master/Shadowrocket.conf 

So could you add a feature that can subscribe to these online rules or manually add?
Thanks a lot.

**Comment by zongUMR** [comment]
@obhasqr It is neccessary for people who lives in China

**Comment by bemasc** [comment]
Thanks for the feature request.  Note that you can already use your favorite Shadowsocks client to connect to your Outline server, if you want features that are not present in the official Outline clients.

**Comment by obhasqr** [comment]
@zongUMR Yes, this is a useful feature to avoid manual turning ON/OFF frequently

**Comment by obhasqr** [comment]
@bemasc Thanks, I've tried it on a 3rd client on iOS. Anyway, that's a great news for people living in the wall when you announced launching Outline. Hope that the Outline is get stronger and stronger

**Comment by IanZhao** [comment]
Great work, Jigsaw LLC.

this would be great for China users, since a lot service in China also blocks request from outside of the country, e.g. a vpn through Japan vps wouldn't be able to watch videos on Youku. I think a similar configuration like the Surge App would be greatly appreciated (https://manual.nssurge.com/), I would like to contribute if no one is available for such feature.

**Comment by foxundermoon** [comment]
and rule by apps

**Comment by tony0918** [comment]
@trevj , May I ask any ETA for this feature? Thanks.

**Comment by trevj** [comment]
@tony0918 I'm afraid we don't have an ETA, sorry, although it is one of the features we would most like to implement. Doing so on all our platforms, however, is something we're still figuring out.

**Comment by zhgqthomas** [comment]
+1

**Comment by tony0918** [comment]
> I think the global pattern is a good one, and it allows more software to use proxies. I want to increase the proxy rule feature while still retaining global proxy mode, and proxies for different addresses should be configured inside the software, rather than being used by the browser to decide whether to use proxies.

I believe we are talking about adding PAC rule for the white/black list. So the outline may look for PAC config file for domain/IP redirection.

**Comment by AberSheeran** [comment]
@tony0918 I know that. I mean, it's stupid for other software to choose whether or not to use a proxy, just like the original shadowsocks. I agree with you.

**Comment by Sean-Wang** [comment]
Jigsaw have a schedule for the feature request? @alalamav @trevj

**Comment by xiaochunjimmy** [comment]
I Voted for this feature. is the a schedule for this feature? 
I'd prefer using Outline and turn it on/off by manual frequently rather than using Shadowsocks client. I do not like the user experience of Shadowsocks client.

**Comment by hadifarnoud** [comment]
while at it, add geo-location based rules. it's most useful. for example, most likely servers inside China do not need to go through a proxy.

**Comment by hadifarnoud** [comment]
I don't think it's doable though. Outline client creates a network interface and routes everything through that. It's very much like a openconnect vpn.

**Comment by stonedreamforest** [comment]
+1

**Comment by nankingrider** [comment]
This is a reasonable feature which should be implemented.

**Comment by ymn** [comment]
Would be a very useful feature. VPN by app or PAC rule

**Comment by wallena3** [comment]
+1

**Comment by wallena3** [comment]
+10086

**Comment by icearith** [comment]
any new outcomings of this feature requesting recently?

**Comment by dcb9** [comment]
Is there anybody still waiting for the feature?

**Comment by dcb9** [comment]
It seems that the simplest approach to this is by adding `args.push('--acl', 'acl-path.acl');` to process_manager.ts. ( not tested yet...)
https://github.com/Jigsaw-Code/outline-client/blob/fa465aac6f309385679ac9043788e0522f49254d/src/electron/process_manager.ts#L337

We also have to had a UI to manage rules. so we will be able to manage these rules by editing them manually or downloading a preset from an HTTP server.

Thank you guys for developing such a brilliant product!!!

**Comment by ttmobl** [comment]
+1

**Comment by maning00** [comment]
+1

**Comment by fortuna** [comment]
Thanks everyone for the input.

Let's move the discussion to this issue that I've created where we can discuss the different approaches: https://github.com/Jigsaw-Code/outline-client/issues/887
