### ISSUE TITLE
No profiles for 'org.outline.ios.client.VpnExtension' were found:  Xcode couldn't find any iOS App Development provisioning profiles matching 'org.outline.ios.client.VpnExtension'.

### ISSUE THREAD

**Issue by shuhaoSCode** [Jigsaw-Code/outline-client#813]
**Describe the issue**
A clear and concise description of what the issue is. If possible, paste the output from your terminal.

**Environment**
 - Node.js 14.4

**Additional context**
=== BUILD TARGET VpnExtension OF PROJECT Outline WITH CONFIGURATION Debug ===

Check dependencies
Code Signing Error: No profiles for 'org.outline.ios.client.VpnExtension' were found:  Xcode couldn't find any iOS App Development provisioning profiles matching 'org.outline.ios.client.VpnExtension'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
Code Signing Error: Code signing is required for product type 'App Extension' in SDK 'iOS 13.5'

** ARCHIVE FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
xcodebuild: Command failed with exit code 65
[22:55:57] 'cordovaCompile' errored after 4.76 s
[22:55:57] Error: exited with error code: 65
    at ChildProcess.onexit (/Users/w/code/vpn/outline-client/node_modules/end-of-stream/index.js:39:36)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:547:15)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
[22:55:57] 'build' errored after 2.32 min
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by wangjinwei0806** [comment]
手动改一下自动注册那边即可

**Comment by shuhaoSCode** [comment]
> 手动改一下自动注册那边即可

具体在哪里呢 不是专业ios开发有点搞不明白

**Comment by wangjinwei0806** [comment]
![image](https://user-images.githubusercontent.com/3974508/85861142-6ef8f700-b7f2-11ea-88b4-5f9fa74f63c8.png)
这代码不好编译，我折腾了半天才成功。。

**Comment by shuhaoSCode** [comment]
> ![image](https://user-images.githubusercontent.com/3974508/85861142-6ef8f700-b7f2-11ea-88b4-5f9fa74f63c8.png)
> 这代码不好编译，我折腾了半天才成功。。

我设置了还是不行哎

![Screen Shot 2020-07-01 at 8 36 22 PM](https://user-images.githubusercontent.com/31207768/86244420-882aea80-bbda-11ea-99b9-34938eafb6e5.png)

大神可以加一下联系方式嘛 有偿回答

**Comment by wangjinwei0806** [comment]
qq 21418925 或者 21418925@qq.com

**Comment by PR4SAN** [comment]
Getting exact same error. How to fix it. Can anyone help please.

**Comment by shuhaoSCode** [comment]
> Getting exact same error. How to fix it. Can anyone help please.

i alreay fix it.But outline use UIWebview，apple store only support wkwebview.

**Comment by fortuna** [comment]
FYI, the iOS client has already migrated to WKWebview

**Comment by alalamav** [comment]
As @shuhaoSCode mentioned, in order to deploy the project you need to create your own bundle identifiers and app groups for the Outilne and VpnExtension targets. Xcode should be able to provision the entitlements and sign the app automatically. You may need to have a Apple Developer Program membership to deploy to a device (the simulator is not supported).

Feel free to re-open this issue if you have more questions.
