### ISSUE TITLE
The following tasks did not complete:

### ISSUE THREAD

**Issue by GeonSik-Shin** [Jigsaw-Code/outline-client#814]
**Describe the issue**

**yarn gulp build --platform=android**

I'm about to build an Android version of the outline-client. 
However, the following error occurs when executing as shown in the document. 

How can I fix this?

```
[Done src/www/build]
+ echo '[Done src/www/build]'
[10:56:26] Finished 'buildWebApp' after 4.47 s
[10:56:26] Starting 'copyBabelPolyfill'...
'node_modules/babel-polyfill/dist/polyfill.min.js' -> 'www/babel-polyfill.min.js'
[10:56:26] Finished 'copyBabelPolyfill' after 31 ms
[10:56:26] Starting 'browserifyAndBabelify'...
[10:56:28] Finished 'browserifyAndBabelify' after 2.17 s
[10:56:28] Starting 'transpileBowerComponents'...
[10:56:28] The following tasks did not complete: build, <series>, <series>, transpileBowerComponents
[10:56:28] Did you forget to signal async completion?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Environment**
 - OS: Ubuntu 20.04 LTS
 - Yarn version : 1.22.4
 - Node.js version : v10.19.0
 - Gulp CLI version: 2.3.0
 - Gulp Local version: 4.0.2

**Comment by Mkurbanov** [comment]
me to

**Comment by Mkurbanov** [comment]
> **Describe the issue**
> 
> **yarn gulp build --platform=android**
> 
> I'm about to build an Android version of the outline-client.
> However, the following error occurs when executing as shown in the document.
> 
> How can I fix this?
> 
> ```
> [Done src/www/build]
> + echo '[Done src/www/build]'
> [10:56:26] Finished 'buildWebApp' after 4.47 s
> [10:56:26] Starting 'copyBabelPolyfill'...
> 'node_modules/babel-polyfill/dist/polyfill.min.js' -> 'www/babel-polyfill.min.js'
> [10:56:26] Finished 'copyBabelPolyfill' after 31 ms
> [10:56:26] Starting 'browserifyAndBabelify'...
> [10:56:28] Finished 'browserifyAndBabelify' after 2.17 s
> [10:56:28] Starting 'transpileBowerComponents'...
> [10:56:28] The following tasks did not complete: build, <series>, <series>, transpileBowerComponents
> [10:56:28] Did you forget to signal async completion?
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```
> 
> **Environment**
> 
> * OS: Ubuntu 20.04 LTS
> * Yarn version : 1.22.4
> * Node.js version : v10.19.0
> * Gulp CLI version: 2.3.0
> * Gulp Local version: 4.0.2

are you solved this problem?

**Comment by Mkurbanov** [comment]
After 3 hours i solved this problem.
Just type this to console :D
`bower install --allow-root`
