### ISSUE TITLE
Outline Windows Client 1.3.3 stops working on Windows 10

### ISSUE THREAD

**Issue by JackGraus** [Jigsaw-Code/outline-client#815]
Outline client version 1.3.3 works fine after installing in Windows 10. However after using for some time the client doesn't connect anymore.
This connection error can be solved by uninstalling Outline client and also uninstalling the 'TAP-Windows adapter' from Windows device manager with the option 'Delete driver software'. After reboot and reinstall Outline client is connecting correctly.

Desktop
 - Windows 10
 - Version Pro 20161.1000

Outline client
- Version 1.3.3

**Comment by egosha17** [comment]
Hi JackGraus, How are you?
Could you tell me,please how did you configure Cygwin, Node.js and Yarn to connect Outline Client on Windows OS. 
I will be greateful If you guide me step by step

**Comment by JackGraus** [comment]
Hello, I am using the Windows 10 outline client 1.3.3 build as delivered in Github. Not using Cygwin.

**Comment by egosha17** [comment]
Ok...thanks a lot...mine is windows 8.1 and doesn't connect on
Outline-client 1.3.3
I will try on Windows 10

**Comment by JackGraus** [comment]
This works for me now for client 1.3.3. But also for later versions after deleting all Hyper-V adapters from Windows device manager. Also the hidden Hyper-V devices and the ones in System devices. And after disabling Hyper-V services.
