### ISSUE TITLE
Outline-Client Configuration in Windows 8.1

### ISSUE THREAD

**Issue by egosha17** [Jigsaw-Code/outline-client#819]
I have been trying to connect Outline Client Almost a month but I could not. Could anyone Helpme please?
What am I missing?
Cygwin installed with rsync 
Node installed v12.18.2
Yarn installed v1.22.4
package.json created with https://github.com/Jigsaw-Code/outline-client/blob/master/package.json configuration.
but still I could not concluded installation.
![изображение](https://user-images.githubusercontent.com/67911482/87244664-2d09bb00-c458-11ea-9afc-de43b74d8b21.png)

**Comment by alalamav** [comment]
Hi @egosha17, I suggest you start by looking at the [cygwin install site](https://cygwin.com/install.html). In order to build Outline in cygwin, you should select the rsync and git packages in the cygwin installer.

**Comment by egosha17** [comment]
Already installed Cygwin but I could install Outline client 

$ yarn do src/electron/build
yarn run v1.22.4
error Command "do" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

 

> 
> 
> Hi @egosha17, I suggest you start by looking at the [cygwin install site](https://cygwin.com/install.html). In order to build Outline in cygwin, you should select the rsync and git packages in the cygwin installer.

Already installed Cygwin but I could not run below command

$ yarn do src/electron/build
yarn run v1.22.4
error Command "do" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by egosha17** [comment]
There is no any DO command in YARN

**Comment by alalamav** [comment]
The `do` command is defined in [package.json](https://github.com/Jigsaw-Code/outline-client/blob/master/package.json#L7). Make sure you are running the command within the repository directory.

**Comment by egosha17** [comment]
Thanks a lot for your help but still issues to fix.In this case








*esgergoshayev@goshayev ~$ yarn do src/electron/buildyarn run
v1.22.4warning package.json: No license field$ bash ./scripts/do_action.sh
src/electron/buildbash: ./scripts/do_action.sh: No such file or
directoryerror Command failed with exit code 127.info Visit
https://yarnpkg.com/en/docs/cli/run <https://yarnpkg.com/en/docs/cli/run>
for documentation about this command.*

**Comment by egosha17** [comment]
Done
