### ISSUE TITLE
cant connect on windows 10 latest update (2004)

### ISSUE THREAD

**Issue by buddudevelopers** [Jigsaw-Code/outline-client#822]
**Describe the bug**
I have used outline before on windows and i was eager to try it again but after installing on windows 10 the client refuses to connect and this message appears in the electron developer tools
`could not connect to server 78e122a9-8548-4422-8381-da1c8b392679:`

**To Reproduce**
1. install outline manager and outline client on windows 10 2004 update and create a digital ocean droplet.
2. click connect on the client after setting up the server in the outline manager
3. Connection repeatedly fails.

**Expected behavior**

**Screenshots**
https://imgur.com/UerLPTb
https://imgur.com/dkhdw3y

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser firefox

**Smartphone (please complete the following information):**

**Submit Feedback**
Please submit feedback through the app and label it with this issue number. [OK]

**Additional context**

**Comment by 27x2** [comment]
I'm having shame issue too, tested with my Iphone 7 it worked perfectly, but on my Windows 10 2004 always receive unexpected error occurred. I also uninstall & install outline client and TAP network driver, but still not work. Console tab also output like images of @buddudevelopers

**Comment by pmjcreations** [comment]
I am also facing this same issue.

Submitted feedback with reference number 00024519.

**Comment by buddudevelopers** [comment]
It seems like this could be a windows issue. Other vpn types are reporting connection issues. [like here](https://answers.microsoft.com/en-us/windows/forum/all/upgrade-to-windows-10-2004-vpn-l2tp-fail/d97f3dc0-f135-4ebe-a8a7-c6e7b6fe9ff9)

**Comment by pmjcreations** [comment]
A bit strange.

I tried on a 1903 and 1909 machine.

Both Windows version shows the same issue.

**Comment by 27x2** [comment]
I think the issue(s) are in this client version.

I read some issues before and figure out some versions of Outline-client had this issue before. I think only thing we can do is wait for the new version from dev team.

**Comment by pmjcreations** [comment]
I started using v1.3.3, which released on Mar 16.

I was using this v1.3.3 until a few days ago.

I had to re-install my Windows 10, and that's all  I remember 😁

**Comment by buddudevelopers** [comment]
I can confirm that you can use compatible clients to connect. [Like this one](https://github.com/shadowsocks/shadowsocks-windows/releases).  To use this you open Outline Manager and copy the access code to the clipboard `ss://Y2hh....[censored]...psZkhSTXlwVTc0anc=@134.XXX.XXX.28:1778/?outline=1` (use your own code). Then right click the shadow-socks icon in the system tray > Servers > Import Url From Clipboard. Click apply on the server dialog. To connect, right click shadow-socks again > System Proxy > Global. It should start working. It means the bug is in this version of outline-client. Unfortunately I dont know the client code well enough to debug it myself. For now use this until they fix

**Comment by pmjcreations** [comment]
Hi @buddudevelopers,

Well, that's very helpful.

I can confirm that using this method works for me. But Outline Client is still showing this error.

So, we can safely assume that this is the problem with the Outline Client version itself.

**Comment by pmjcreations** [comment]
I must update this thread.

Somehow it started working again with the same version without me doing anything.
