### ISSUE TITLE
Android client issues

### ISSUE THREAD

**Issue by 7urkm3n** [Jigsaw-Code/outline-client#826]
My android version is not stable, some movie websites dont work.

Sometimes it works instantly or need to refresh couple times browser, and in around 2-5min stops again.
It wasn't happening previously at all, we have been using it without an issue almost 15months. 

Only on Android devices.

Interesting part of this: on the `Intra` android app it works charmingly. `https://github.com/Jigsaw-Code/Intra`

**Smartphone:**
 - Device: Samsung S8 and Android Mi Box TV
 - OS: Android 9 and mi box 8.0.0
 - Browser: Samsung [Google Chrome] | Mi Box [VideoBox app]
 - Version: NA

**Additional context**
IOS devices work great and no complains at all.

Sample:
Websites: `https://www.dailymotion.com`, `https://filmix.co`, `https://www.kanal7.com`
VPS region: Russia (Moscow)
Devices: Android smartphone and Me Box TV. (on both the same issue, on IOS works charmingly).

**Comment by egosha17** [comment]
Salam 7urkm3n...
Outline bilen baglanşyly mesele bar
egoshayev@gmail.com  e ýazaýyň..

**Comment by fortuna** [comment]
Is this still an issue?

What version of the Outline Client are you using?

**Comment by egosha17** [comment]
No thanks

**Comment by 7urkm3n** [comment]
I could not validate it, since personally i use iPhone and never faced this issue but some of my friends still having the same issue. I'will test and give you a feedback.
