### ISSUE TITLE
Updating selectors after delegate addition failed 

### ISSUE THREAD

**Issue by 826327700** [Jigsaw-Code/outline-client#827]
**Describe the bug**
This plugin doesn't work in iOS 13.6, and show me some errors:

> Updating selectors after delegate addition failed with: Error Domain=NSCocoaErrorDomain Code=4097 "connection to service on pid 368 named com.apple.commcenter.coretelephony.xpc"

**Comment by fortuna** [comment]
Is this still an issue?
What plugin are you referring to?
Are are you trying to do?
