### ISSUE TITLE
Unsupported cipher after upgrade

### ISSUE THREAD

**Issue by gnomeby** [Jigsaw-Code/outline-client#847]
**Describe the bug**
After upgrade to 1.4.0 I see "Unsupported cipher" error but 1 minute ago with the previous version app it worked. Cipher id "aes-256-cfb".

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: 13.5.1, 13.6.1
 - Version 1.4.0

**Comment by gnomeby** [comment]
Switching to aes-256-gcm on the server solved the issue.

**Comment by lin010151** [comment]
Same here. I'm using xchacha20-ietf-poly1305, which turned unsupported after update to 1.4.0.

I'm using iPhone SE 2nd Gen with latest OS.

**Comment by 881997** [comment]
same，aes-256-cfb

**Comment by mgfjxxiexiaolong** [comment]
why unsupported aes-256-cfb ?  Will it return back?

**Comment by studentmain** [comment]
Shadowsocks stream cipher protocol has known security problem. All implementation SHOULD remove them.

**Comment by fortuna** [comment]
The Outline server never supported the stream ciphers, and we will no longer support it on the client.

Stream ciphers are bad practice that makes the user vulnerable and the server easy to detect. By dropping support we nudge the community into adopting better standards.
