### ISSUE TITLE
How can i change the project code on Android Studio?

### ISSUE THREAD

**Issue by Mkurbanov** [Jigsaw-Code/outline-client#861]
**How can i change the project code. more precisely, how to open a studio on android and compile the code.**

  i am using windows 7 and i had to use docker to compile. Yeah! I compiled the code. but i dont know how i can open the project and change layouts, java codes. i cant open the project on my windows. the question is, how can I calmly work with a project on an android studio. thanks for the wound! it is very important to me.

**Comment by alalamav** [comment]
@Mkurbanov, the Docker build image mounts the host's filesystem, so you should be able to open the project at `outline-client/platforms/android/` with Android Studio. Feel free to re-open if this is still an issue.
