### ISSUE TITLE
Crashing when launched

### ISSUE THREAD

**Issue by ghost** [Jigsaw-Code/outline-client#864]
I tried last version of outline client but keeps crashing
i tried to uninstall it in reinstall it not working
i tried old versions but i get js error
any help?

**Comment by fortuna** [comment]
What client OS and version are you referring to?

**Comment by msamsami** [comment]
> What client OS and version are you referring to?

Hi. I have the same issue. I use Windows 10 Enterprise (last update) and the Outline client v1.4.0.0. I kept reinstalling the app several times and it didn't work! It quickly crashes/disappears a few seconds after I run it.
