### ISSUE TITLE
How to connect or disconnect outline from command line or using python

### ISSUE THREAD

**Issue by AnergCorp001** [Jigsaw-Code/outline-client#866]
I am working in a location that needs to change ip address a lot, and doing it manually takes too long time
So how I connect and disconnect to my servers using python

I have searched on google but I found nothing useful

Thanks A lot

**Comment by studentmain** [comment]
Assume your application has SOCKS 5 proxy (HTTP proxy also works) support. Outline is shadowsocks. Most shadowsocks client provided a SOCKS 5 server. So you can open some shadowsocks client, listen on different local port, and switch between them.

**Comment by AnergCorp001** [comment]
I am new to programming Can you show me how to do it in python,
I have installed outline client on my computer, I just want to
connect/disconnect using python

**Comment by fortuna** [comment]
This is not a defect or a feature request.  Feel free to keep discussing, but I'll close the bug. Those discussions may be better on the Reddit community: https://www.reddit.com/r/outlinevpn/
