### ISSUE TITLE
Outline Windows Client 1.4.0 loses connectivity on Windows 10

### ISSUE THREAD

**Issue by leddt** [Jigsaw-Code/outline-client#877]
**Describe the bug**
While using the VPN, after a short period of time (under 30 minutes), the internet will stop working. Sites simply won't load, Slack won't update, etc. This happens consistently. I use this VPN with a few of my co-workers and they also experience this issue. We are using Windows 10. 

The VPN is hosted on a $5 DigitalOcean droplet. I have tried scaling it up to the $10 or $15 tiers but I experienced the same exact behavior. I also tried at night when I was sure that no other co-worker was using the VPN and it still happened.

**To Reproduce**
1. Connect to my VPN server
2. Use the internet for a while (5 to 30 minutes)
3. The internet stops working
4. Disconnect from the VPN
5. The internet works
6. `GOTO 1.`

**Expected behavior**
The internet should continue working without interruptions

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Mostly Chrome, but the problem is not limited to it
 - Version: Outline client v1.4.0

**Comment by chaitu87** [comment]
Same here. Only happens with Windows. Android, iOS, Mac all working fine.

**Comment by jordanyoungs** [comment]
I am experiencing the exact same issue, also on Windows 10 with Outline client v1.4.0

Are there any logs I could share that would help troubleshoot this issue?

**Comment by abdulllahBi** [comment]
yeah same I see a lot of these errors in Event Viewer and have the same disconnect problem

Source Outline Service

Failed to handle connection: System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
   at System.IO.Pipes.PipeStream.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.IO.Pipes.PipeStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Pipes.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at OutlineService.OutlineService.WriteResponse(ServiceResponse response)
   at OutlineService.OutlineService.HandleConnection(IAsyncResult result)

or

failed to delete LAN bypass routes: command exited with 0 (stdout: , stderr: The route deletion failed: Element not found.)

or


failed to unblock IPv6: command exited with 1 (stdout: Element not found., stderr: )

**Comment by leddt** [comment]
Hey, just wanted to mention that this is fixed for us in version 1.5.0 🎉
