### ISSUE TITLE
Allow for different data transfer limits per key

### ISSUE THREAD

**Issue by mks9467** [Jigsaw-Code/outline-client#879]
It would be cool if you could add different amounts of allowed data transfer per key so like 1 key could have 20gb and another could have 100gb but they are on the same server

**Comment by alalamav** [comment]
Hi @mks9467, thanks for the feature request. @JonathanDCohen is working on it and has made great progress.

**Comment by JonathanDCohen** [comment]
Thanks for the feature request!  https://github.com/Jigsaw-Code/outline-server/tree/cohenjon-per-key-limits-shadowbox has a draft, working version of shadowbox with this feature.  If you have a little bit of command line ability, you should be able to use the instructions on the readme to create a server from that branch which allows this functionality (but only from the command line, the UI hasn't been implemented yet)

**Comment by fortuna** [comment]
This has already been released to production.
