### ISSUE TITLE
Exclude apps in iOS and Android

### ISSUE THREAD

**Issue by al1b** [Jigsaw-Code/outline-client#88]

**Comment by trevj** [comment]
@al1b Thanks for the suggestion! I agree this would be a nice feature.

**Comment by trevj** [comment]
Just spotted that this is basically the same request as:
https://github.com/Jigsaw-Code/outline-client/issues/180

I guess we haven't decided yet whether it will be a whitelist or blacklist or whatever but let's continue tracking this general issue there.

**Comment by sanvit** [comment]
Any update please?

**Comment by trevj** [comment]
@sanvit I'm afraid not, other than we still very much want to do this.
