### ISSUE TITLE
how to mannually add vpn configiration file to my device settings-vpn form

### ISSUE THREAD

**Issue by linuxandroid-xyz** [Jigsaw-Code/outline-client#881]
how to mannually add vpn configiration file to my device settings-vpn form
i was not able to download outline client , that is why i am asking

**Comment by fortuna** [comment]
Unfortunately the Shadowsocks protocol is not standard and devices usually don't support it. That's why a client is needed.

What device are you talking about?

**Comment by usandarthur** [comment]
All of those devices with settings-vpn, can I have mobile ios or Android version of outline manager? How to build and compile my own mobile mobile ios or Android version of outline manager ?

**Comment by fortuna** [comment]
If the device supports Shadowsocks, you can enter the config from the access code URL.

The feature request for the mobile manager is at https://github.com/Jigsaw-Code/outline-server/issues/772
