### ISSUE TITLE
TLS fingerprint of outline

### ISSUE THREAD

**Issue by c1b3rd0rk** [Jigsaw-Code/outline-client#888]
I've seen utls mentioned. The forked page says utls is archived but maintained at another repo. However, it is unclear to me whether it is used by outline.  In case it is not I guess outline would be easy to fingerprint. Would it be possible to make the client-server TLS handshake customizable e.g. to look like a normal browser connection ?

**Comment by studentmain** [comment]
outline-client is electron, which is a real chromium browser

**Comment by c1b3rd0rk** [comment]
Has this always been the case or did they switch at some point to electron? Otherwise having utls in the repo would not make sense.  Where there any tests to see if the handshake is really the same?

**Comment by fortuna** [comment]
Thanks for your concern. Outline uses Shadowsocks, not TLS, so it's not fingerprintable like that.
