### ISSUE TITLE
Basic support for Online Config

### ISSUE THREAD

**Issue by alalamav** [Jigsaw-Code/outline-client#891]
Support online Shadowsocks server configurations per [SIP008 online config](https://github.com/shadowsocks/shadowsocks-org/issues/89). For the first feature iteration we will support online config https URLs with domain names and root authority certificates. Fetch the server configuration on connection start and only accept the basic JSON file format with a single server configuration, ie:

```
{
  "server": "example.com",
  "server_port": 1234,
  "password": "example",
  "method": "chacha20-ietf-poly1305",
  "remark": "Example Server"
}
```

**Comment by database64128** [comment]
The basic JSON document format is no longer a part of SIP008. Please refer to https://shadowsocks.org/en/wiki/SIP008-Online-Configuration-Delivery.html for specifics.

**Comment by alalamav** [comment]
I noticed that shadowsocks-android and shadowsocks-windows do support the basic file format. @database64128, do you know if it will be deprecated in the future per the new spec?

**Comment by database64128** [comment]
As a part of the refactoring process in shadowsocks-windows v5, I have reimplemented online config support to strictly follow the new spec. The basic file format is no longer supported.

**Comment by moranno** [comment]
Hope to see this implement soon.

**Comment by fortuna** [comment]
This has been launched this year: https://www.reddit.com/r/outlinevpn/wiki/index/dynamic_access_keys/
