### ISSUE TITLE
Outline VPN doesn't work on windows 10

### ISSUE THREAD

**Issue by shubhindia** [Jigsaw-Code/outline-client#895]
**Describe the bug**
I am unable to connect to my VPN server. It just says connecting and disconnects

**To Reproduce**
1. Go to 'outline VPN client'
2. Click on 'connect'
3. See error

**Expected behavior**
It should connect to VPN 

**Screenshots**
![image](https://user-images.githubusercontent.com/7694806/99264483-876fb980-2846-11eb-9746-f75260b51bc6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser: Chrome
 - Version: Latest

**Comment by fortuna** [comment]
What error are you getting?
What's the version of the client app?

**Comment by shubhindia** [comment]
I am using version 1.4.0 and getting below error 
![image](https://user-images.githubusercontent.com/7694806/99555878-ce94b080-29e6-11eb-928d-9581526a6699.png)
Let me know how can I get logs, I will be happy to provide

**Comment by shubhindia** [comment]
and getting this on release: daily-2020-11-18
![image](https://user-images.githubusercontent.com/7694806/99556530-a6598180-29e7-11eb-817c-a2b15d517871.png)

**Comment by CipherEA** [comment]
![image](https://user-images.githubusercontent.com/12973563/100123588-a1984000-2eb5-11eb-9625-67c4149e6130.png)

**Comment by shubhindia** [comment]
@CipherEA run installer as administrator

**Comment by CipherEA** [comment]
i did man , no use, 
Turned off  antivirus, firewall

**Comment by jeffhsta** [comment]
I am having the same issue, I use Windows 10 Pro with WSL 2.

I already reinstall e reboot my machine several times, mo success so far.

**Comment by shubhindia** [comment]
> I am having the same issue, I use Windows 10 Pro with WSL 2.
> 
> I already reinstall e reboot my machine several times, mo success so far.

I have stopped using it now. It was working so well that never felt need to change, but I have already switched to different VPN now. Don't even know how am I supposed to take logs, else would have definitely found something useful for devs at least.

**Comment by msamsami** [comment]
Hi. I had the same issue with the Outline client every time I installed another VPN client (e.g., Cisco AnyConnect, OpenVPN) on my Windows. The moment I uninstalled them, the Outline client worked perfectly fine (sometimes needed a reboot as well).

**Comment by Gushchin24** [comment]
> I am using version 1.4.0 and getting below error ![image](https://user-images.githubusercontent.com/7694806/99555878-ce94b080-29e6-11eb-928d-9581526a6699.png) Let me know how can I get logs, I will be happy to provide

@shubhindia check this solution if you're using an HP computer: [Solved! Outline VPN Client Does Not Work](https://h30434.www3.hp.com/t5/Notebook-Wireless-and-Networking/Outline-VPN-Client-Does-Not-Work/m-p/8453483/highlight/true#M194260)

**Comment by shubhindia** [comment]
I installed windows 11 recently and it works fine. Not sure what was the issue but since I am not facing it anymore, closing this now.

**Comment by hamedhajiloo** [comment]
Same issue!

**Comment by msamsami** [comment]
> Same issue!

Every time it happens, I fix it by reinstalling the program.
