### ISSUE TITLE
Please add xchacha20-ietf-poly1305 support

### ISSUE THREAD

**Issue by simonsmh** [Jigsaw-Code/outline-client#9]
Already defined here https://github.com/Jigsaw-Code/outline-client/blob/master/third_party/shadowsocks-libev/src/aead.c#L110
Since we can use Outline Client as Shadowsocks Client, its necessary to support as many ciphers as possible. Thanks for your amazing work.

**Comment by fortuna** [comment]
Is this an official Shadowsocks cipher? Any idea why it's not listed on https://shadowsocks.org/en/spec/AEAD-Ciphers.html?

**Comment by simonsmh** [comment]
Because xchacha20-ietf-poly1305 is only supported by libsodium, not OpenSSL, which is only supported by shadowsocks-libev.

**Comment by fortuna** [comment]
We're working on it: https://github.com/Jigsaw-Code/outline-shadowsocksconfig/pull/2

**Comment by alalamav** [comment]
xchacha20-ietf-poly1305 is supported in the clients as of #60. Thank you for the feedback, @simonsmh.

**Comment by lin010151** [comment]
xchacha20-ietf-poly1305 turned unsupported after update to 1.4.0.

I'm using iPhone SE 2nd Gen with latest OS.
