### ISSUE TITLE
Can't add server via IPv6

### ISSUE THREAD

**Issue by HippoBaro** [Jigsaw-Code/outline-client#91]
Currently, the client app doesn't allow adding a new key that specifies an IPv6 endpoint. The client refuses to parse the input, deemed invalid.

It would be nice to have IPv6 working going forward. It shouldn't be hard to fix, since ss-client support IPv6 out-of-the-box.

**Comment by trevj** [comment]
@HippoBaro Thanks for the suggestion - and apologies for the slow reply. I'm afraid adding IPv6 support isn't as easy as it looks because tun2socks does not support it. It is, however, of course a feature we would like to add.

**Comment by HippoBaro** [comment]
@trevj I am not sure this is true, https://github.com/ambrop72/badvpn/commit/ed6449d06af4d106ec3ca09aaf9f218362109747 seems to indicate that IPv6 support has been upstream for a while.

**Comment by trevj** [comment]
@HippoBaro Huh, you're right - and our copy of the code seems to include this. Thanks!

**Comment by mike1996** [comment]
please add ipv6 support

**Comment by TomGarden** [comment]
```
./install_server.sh 
> Verifying that Docker is installed .......... OK
> Verifying that Docker daemon is running ..... OK

Sorry! Something went wrong. If you can't figure this out, 
please copy and paste all this output into the Outline Manager screen, 
and send it to us, to see if we can help you.
```

my server is ipv6 , haven't ipv4

**Comment by 3ventic** [comment]
Has there been any movement on IPv6 support?

**Comment by TAMSHUI** [comment]
why still can't I connect via IPV6 address using Outline Client?  but I can ssh via ipv6 address to my outline server and connect to the outline server via outline manager via ipv6.

**Comment by maddyhof** [comment]
Closing in favor of #1422. We do support IPv6 for Android, macOS and iOS, but not for Electron clients (Windows and Linux).

**Comment by carloshwa** [comment]
I'm running version 1.11.0 of the mac client, and it does not allow me to add an IPv6 key. It reports:
> Invalid access key.
> Enter a valid access key (ss://) to add a server.

How is this supposed to work?

**Comment by carloshwa** [comment]
Thanks for the response, I'll file a report there. But I do see this specific check that prevents adding an IPV6 key. I tried commenting out, which allowed me to add my key to the client, but it still failed to connect.

https://github.com/Jigsaw-Code/outline-client/blob/60c800c91bfd62bac3961a40d1571023a86d5a9b/src/www/app/outline_server_repository/index.ts#L205
