### ISSUE TITLE
The application itself prohibits itself from using the VPN connection. 

### ISSUE THREAD

**Issue by akiyev** [Jigsaw-Code/outline-client#925]
**Describe the bug**
If you remove the ban from the application itself, then VPN does not work. 
`VpnService.Builder builder =
                    vpnService.newBuilder()
                            .setSession(vpnService.getApplicationName())
                            .setMtu(VPN_INTERFACE_MTU)
                            .addAddress(String.format(Locale.ROOT, VPN_INTERFACE_PRIVATE_LAN, "1"),
                                    VPN_INTERFACE_PREFIX_LENGTH)
                            .addDnsServer(dnsResolverAddress)
                            .addDisallowedApplication(vpnService.getPackageName());`

If you give permission to go through VPN traffic, then VPN does not work
i removed:
`.addDisallowedApplication(vpnService.getPackageName());`

Android version

**Comment by alalamav** [comment]
@akiyev, this is working as intended. We need Outline's traffic to bypass the VPN in order to prevent a routing loop.
What problem are you trying to solve?

**Comment by akiyev** [comment]
I am trying to make a browser with Outline VPN. This should be one application. How can I implement this?

**Comment by akiyev** [comment]
> @akiyev, this is working as intended. We need Outline's traffic to bypass the VPN in order to prevent a routing loop.
> What problem are you trying to solve?

I am trying to make a browser with Outline VPN. This should be one application. How can I implement this?

**Comment by parthvirani95** [comment]
Is there any solution on this?, i am also making one web browser with outline VPN, and required this fix to work further in browser, else there is no meaning of using Outline VPN in browser app.

This is argnt, and help will be appreciated, great VPN, great SDK.
