### ISSUE TITLE
Build failed for iOS

### ISSUE THREAD

**Issue by spareyaya** [Jigsaw-Code/outline-client#926]
**Describe the issue**
I build the project according to the document. But when I open it in xcode and build it, the following error occurs. Here is the error:

/Users/apple/program/xcode/outline-client/platforms/ios/Outline/Resources/vpn/OutlineTunnelStore.swift:17:8: Module compiled with Swift 5.3 cannot be imported by the Swift 5.3.2 compiler: /Users/apple/program/xcode/outline-client/platforms/ios/Outline/Plugins/cordova-plugin-outline/CocoaLumberjackSwift.framework/Modules/CocoaLumberjackSwift.swiftmodule/arm64-apple-ios.swiftmodule

**Environment**
 - MacOS: 10.15.7
 - xcode version: 12.3
 - iOS: iPhone 8 plus with iOS 14.2

How should I do to solve it?

**Comment by CoderJin** [comment]
rebuild CocoaLumberjackSwift

**Comment by joeytwiddle** [comment]
This issue has appeared [a few times](https://github.com/Jigsaw-Code/outline-client/issues?q=is%3Aissue+%22cannot+be+imported+by+the+Swift%22) before.

#597 looks like it has the most helpful instructions.

**Comment by JonathanDCohen** [comment]
You can build with Xcode 11 and it should work, however https://github.com/Jigsaw-Code/outline-client/pull/889 was supposed to have fixed this issue.  @alalamav you know what could be going on?
