### ISSUE TITLE
already exists and is not an empty directory. error on macOS Catalina 10.15 

### ISSUE THREAD

**Issue by ChenMoGe2** [Jigsaw-Code/outline-client#929]
Hello,I have an issue abount outline-client yarn build.My Mac system is macOS Catalina 10.15 and xcode is 11.0.When I use yarn to build the project,it has a npm error say destination path '/Users/xxx/.npm/_cacache/tmp/git-clone-ec795e26/.git' already exists and is not an empty directory.But there are no any files under '/Users/xxx/.npm/_cacache/tmp/*'.I hope someone know how to solute the problem and tell me how to do.Or someone else who build success can tell me what mac and xcode system you have.Thank you very much!

**Comment by ebj15** [comment]
Hello,
I have been getting the same problem. Someone Do cant found a solution?

tks
EBJ

**Comment by maddyhof** [comment]
We no longer use yarn. Can you please try again with the new setup instructions in the README?
