### ISSUE TITLE
Last update is broken (Mac OS)

### ISSUE THREAD

**Issue by ZergZe** [Jigsaw-Code/outline-client#93]
After last mac os client application update (from Apple App Store) the app shows just white windows with nothing on it.
Mac Os 10.11.6.

**Comment by ZergZe** [comment]
On my Mac the outline-client was not forgetting servers (on previous version).

But, current version still starts with empty screen only.
Application re-installation does not help.

Is there any info i can provide you to help to reproduce it? (if i'm the only who have it)

**Comment by alalamav** [comment]
Thank you for the feedback, @ZergZe and sorry that you're experiencing this issue. 
To make sure I understand, is the issue that the servers are being deleted or that the UI is not rendering?

**Comment by ZergZe** [comment]
Sorry for being unclear.
I see icon it tray (that is ok). 
When i press the icon, popup window appears.
This window has no UI elements. Only background color that fills whole the popup window shape.
This is only that i see:
![img](https://snag.gy/BlLj0g.jpg)

I can't even try to check if there any servers there or not.
I can do nothing but toggle this popup window on/off.
It start right after last outline-client update.

**Comment by ZergZe** [comment]
also i have tried to:
1. uninstall client app
2. relocate ~/Library/Containers/org.outline.macos.client/
3. install client app again
no effect

**Comment by vedmaque** [comment]
also have this issue on MacOS 10.11.6

**Comment by alalamav** [comment]
Thanks everyone for the feedback. I believe #116 fixes this issue. I will release the macOS client as soon as it is merged.

**Comment by ZergZe** [comment]
@alalamav Thanks for the update!
But, unfortunately it did not help, at least for me. (have just updated to 1.1.0)

**Comment by alalamav** [comment]
Apologies for the confusion. v1.1.0 was released prior to the fix. The fix will go out in __v1.1.1__, today or tomorrow.

**Comment by ZergZe** [comment]
Sorry for bothering, but is there any chance for update?

**Comment by prabur** [comment]
This doesn't seem to be fixed, any idea when 1.1.1 will be release @alalamav ?

**Comment by alalamav** [comment]
Apologies for the delay. We are working to get v1.1.1 released as soon as possible. Thank you for your patience.

**Comment by prabur** [comment]
It's been weeks with this issue, and there's no way to resolve it. I've got more users having this issue on a daily basis and uninstaling / reinstalling is just not helping for whatever reason. Is there a DMG i could get my hands on rather than waiting for the App Store version since there doesn't seem to be an end in sight?

**Comment by alalamav** [comment]
The macOS client v1.1.1 has been released. It should now work on macOS 10.11. Apologies for the delay and thank you for your patience.

**Comment by ZergZe** [comment]
I will back up locally every new updated file:)
