### ISSUE TITLE
already exists and is not an empty directory. error on macOS Catalina 10.15

### ISSUE THREAD

**Issue by ChenMoGe2** [Jigsaw-Code/outline-client#930]
各位好,我遇到了一个问题关于编译outline-client的。我使用的系统版本是macOS Catalina 10.15，使用的xcode版本是11.0。当我使用yarn编译时，会出现错误destination path '/Users/xxx/.npm/_cacache/tmp/git-clone-ec795e26/.git' already exists and is not an empty directory.但是当我使用ls命令的时候/Users/xxx/.npm/_cacache/tmp这个文件夹下没有任何的文件或目录。不知哪位大神遇到这个问题能帮小弟看下，或者编译通过的大神能否告诉小弟下使用的mac版本以及xcode版本，谢谢！

**Comment by fortuna** [comment]
This seems to be a duplicate of https://github.com/Jigsaw-Code/outline-client/issues/929
