### ISSUE TITLE
iOS build Success but I can not connect vpn and  the VPN flag is not displayed

### ISSUE THREAD

**Issue by weweMM** [Jigsaw-Code/outline-client#931]
Xcode runs successfully and runs to my iphone   but can not connect VPN  and the vpn flag is not displayed.

The log : VpnStartFailure Failed to report events. Sentry not initialized.

MacOS: 10.15.7
xcode version: 12.3
iOS: iPhone 12 with iOS 14.3

**Comment by fortuna** [comment]
It seems related to https://github.com/Jigsaw-Code/outline-client/issues/850

**Comment by maddyhof** [comment]
Closing in favor of #850
