### ISSUE TITLE
ios  Failed to start VPN

### ISSUE THREAD

**Issue by weweMM** [Jigsaw-Code/outline-client#932]
OutlineVPN.swift, line 364   method (sendProviderMessage(_ messageData: Data, responseHandler: ((Data?) -> Void)? = nil))   the handler have no response,vpn connect failure.
Is parameter ‘data’ missing attributes，or some other mistake 

What should I do to connect to the VPN successfully

MacOS: 10.15.7
xcode version: 12.3
iOS: iPhone 8 plus with iOS 14.2

Thank you very much for answering this question

**Comment by fortuna** [comment]
It seems related to https://github.com/Jigsaw-Code/outline-client/issues/850

**Comment by maddyhof** [comment]
Closing as duplicate, in favor of #850
