### ISSUE TITLE
How to prevent exposure of real IP

### ISSUE THREAD

**Issue by kls1361** [Jigsaw-Code/outline-client#938]
When disconnecting in use, how to disconnect the network to prevent exposure of the real IP

**Comment by joeytwiddle** [comment]
Is this happening to you?

I thought when there was an unexpected disconnect, Outline would completely block the network, until you open the Outline app.

Are you experiencing a fall back to the normal network?

**Comment by JonathanDCohen** [comment]
We don't intentionally block anything as far as I know.  @kls1361 do you mean that you're afraid that you will ezpose your IP address somewhere when you disconnect from your Outline server?
