### ISSUE TITLE
windows client opens and after closing

### ISSUE THREAD

**Issue by burak-ayd** [Jigsaw-Code/outline-client#948]
I open the program, it closes as soon as the window comes up. I uninstalled and reinstalled but the problem did not fix.  What should I do?

**Comment by cjhenck** [comment]
What Windows & Outline Client versions are you using?

**Comment by cjhenck** [comment]
May be related to #842

**Comment by Zac10ck** [comment]
I am also having the same issue , I tried uninstalling and reinstalling it back  but still issue persist 

I clicked on the button it opens for 1 or 2 second and then automatically closes the window
outline services are running in the background

**Comment by abdulllahBi** [comment]
I am also having the same issue.

**Comment by Zac10ck** [comment]
Found a solutions - Downloaded old version and its working fine

https://github.com/Jigsaw-Code/outline-client/releases/download/daily-2019-02-04/Outline-Client.exe

**Comment by Zac10ck** [comment]
> I am also having the same issue.

Found a solutions - Downloaded old version and its working fine

https://github.com/Jigsaw-Code/outline-client/releases/download/daily-2019-02-04/Outline-Client.exe

**Comment by j0k** [comment]
> > I am also having the same issue.
> 
> Found a solutions - Downloaded old version and its working fine
> 
> https://github.com/Jigsaw-Code/outline-client/releases/download/daily-2019-02-04/Outline-Client.exe

That solution works fine in March 2026.
