### ISSUE TITLE
Can I Make My Own Client?

### ISSUE THREAD

**Issue by mtgsquad** [Jigsaw-Code/outline-client#955]
The issue tracker is not for questions. Please ask questions at support@getoutline.org.
Am I Allowed To Copy The App And Just Customize It??

**Comment by alalamav** [comment]
Outline is licensed under the [Apache License 2.0](https://github.com/Jigsaw-Code/outline-client/blob/master/LICENSE). You may modify and distribute the app according to the conditions specified on the license.

Disclaimer: I am not a lawyer and this is not legal advice.
