### ISSUE TITLE
No connect button in appimage build

### ISSUE THREAD

**Issue by molitona** [Jigsaw-Code/outline-client#979]
I don't see any connect button on your last appimage build after pasting key?

![ff](https://user-images.githubusercontent.com/35532337/108569432-2c010c00-730c-11eb-9bc9-25469522dbcc.png)

**Comment by fortuna** [comment]
The "Add Server" button only appears after you paste a valid link on the access key box.
You can use this fake key to test: `ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTp0ZXN0QDE5Mi4xNjguMTAwLjE6ODg4OA#example-server`

**Comment by molitona** [comment]
![gg](https://user-images.githubusercontent.com/35532337/109056585-e57f2900-76e0-11eb-85df-af43d48e9c2b.png)
I already did that and no button showing !

**Comment by JonathanDCohen** [comment]
Is this a daily build?  I ran into this issue a couple weeks ago and fixed it with https://github.com/Jigsaw-Code/outline-client/pull/961

**Comment by molitona** [comment]
yes, it's a daily build. How have you fixed it ?

**Comment by JonathanDCohen** [comment]
It was caused by rendering erroring out from the renderer process needing the app name and not getting it from a deprecated Electron feature.

@alalamav made a couple more fixes today, could you try the binary from https://github.com/Jigsaw-Code/outline-client/releases/tag/linux-v1.3.0 and see if it works for you?

**Comment by molitona** [comment]
It's working fine now.

-------- Original Message --------

**Comment by JonathanDCohen** [comment]
Awesome, thanks for reporting the issue!

**Comment by molitona** [comment]
Unfortunately another issue. after disconnecting from VPN and closing the app I cannot get back my regular connection. Outline interface (outline-tun0) still exist.

-------- Original Message --------
