### ISSUE TITLE
Menu's "Privacy" and "Data collection" links do not work properly on iOS client (at least on iPad)

### ISSUE THREAD

**Issue by ricardbejarano** [Jigsaw-Code/outline-client#98]
Issue was detected on an iPad Air 2 running Outline 1.0.2 on iOS 11.3.1

**Comment by trevj** [comment]
@bjrnio The links work for me with Outline 1.1.2 on iOS 11.4.1. I can see that a somewhat...**long** press is necessary for the link to open (with a "short" click all that happens is the menu closes). Can you please confirm that's the case for you too and I will change the title of this bug.

**Comment by bjrnio** [comment]
> I can see that a somewhat...long press is necessary for the link to open (with a "short" click all that happens is the menu closes)

I just checked, this is true. Short clicks close the menu and a longer click opens the link.

**Comment by trevj** [comment]
Thanks @bjrnio. I believe @alalamav was working on a fix for this so I'll re-assign.
