### ISSUE TITLE
Error "Outline is not properly installed" on Linux

### ISSUE THREAD

**Issue by 0xNeu** [Jigsaw-Code/outline-client#983]
**Describe the bug**
Outline won't connect to a Shadowsocks server, showing an error that says `Sorry, it looks like Outline is not properly installed. Please try installing it again, If that doesn't work, please submit feedback through the app`

**To Reproduce**
- Download the GNU/Linux .AppImage version 1.3
- Run the application
- Add any `ss://` server
- Click on Connect

**Expected behavior**
Application creates a VPN connection.

**Screenshots**
![Screenshot_20210301_230239](https://user-images.githubusercontent.com/18480836/109549684-8ad03d80-7ae3-11eb-9068-b5e1545e91d9.png)

**Client System (please complete the following information):**
 - Outline Client Version : 1.3
 - Your Operating System: Solus OS 4.2 (Also tried on Linux Mint 19.3, same results)
 
**Submit Feedback**
Please submit feedback through the app and label it with this issue number.

**Additional context**
Here's the Terminal output when I execute the AppImage from there:
```
WINDOW DECORATIONS RELOADED
loading web app from file:///tmp/.mount_OutlinKT77tk/resources/app.asar/www/electron_index.html?appName=Outline
(node:1536) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
Could not load active tunnel:  [Error: ENOENT: no such file or directory, open '/home/USERNAME/.config/Outline/connection_store'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/USERNAME/.config/Outline/connection_store'
}
Checking for update
Generated new staging user ID: 1c1735c6-e653-5302-a0cf-9931b6ae6532
Update for version 1.3.0 is not available (latest version: 1.3.0, downgrade is disallowed).
(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.
Outline is starting
connecting to 1ddfe7ba-5405-4762-afad-5f556149fd44...
(node:1536) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
UDP support: true
(re-)installing routing daemon
copying service files to /tmp/Dk78Rj
[EXIT - badvpn-tun2socks]: Exited with code 1
a helper has exited, disconnecting
could not stop routing: Cannot call write after a stream was destroyed
[EXIT - ss-local]: Exited with code 0
Promise "DNS lookup" resolved before 10000 ms.
could not connect: h (routing daemon is not running)
^Ccould not stop routing: Cannot call write after a stream was destroyed
could not stop routing: Cannot call write after a stream was destroyed
Terminated

```

**Comment by FatGrizzly** [comment]
I am having this bug too, I can't connect either

**Comment by itsluispatricio** [comment]
didn't think i would see you here @FatGrizzly

**Comment by FatGrizzly** [comment]
> didn't think i would see you here @FatGrizzly

Umm? Who are you? if you have anything to say contact me via soundar@secret.fyi

**Comment by SwarnimDoegar** [comment]
I had the same issue in solus. Outline was trying to copy some file to /usr/local/sbin dir which does not exist. Manually created this directory and it works fine now.

**Comment by AnonyMousGroup7** [comment]
> I had the same issue in solus. Outline was trying to copy some file to /usr/local/sbin dir which does not exist. Manually created this directory and it works fine now.

Please tell us which files to copy

**Comment by PanHH** [comment]
I also got the same problem.
![1640252199](https://user-images.githubusercontent.com/26243670/147222455-d3d58893-9b86-46e7-bd5c-8411e9a65164.png)

**Comment by Sentoki** [comment]
Have same problem. Its almost a year from first message.

**Comment by TorhamDev** [comment]
@PanHH 
Hi,
I had this error a long time ago

You have to reinstall the outline

**Comment by pjmd89** [comment]
> You have to reinstall the outline

hello,
i reinstalled but the error persists

**Comment by Sentoki** [comment]
> > You have to reinstall the outline
> 
> hello, i reinstalled but the error persists

Same thing.

**Comment by newqwes** [comment]
I also tried to solve this problem. I have two computers, one laptop (Ubuntu 20.04) another PC (Ubuntu 18.04.6). On the laptop, everything works as it should, I do the same thing only on the PC, then an error occurs. I tried to change permissions, install different versions of the application client, delete the file located on the path / usr / local / sbin, reboot the system, update, use other ss keys, none of this helped. Googled there is also nothing. I think it's problematic in the Ubuntu version. What versions of linux do you @Sentoki @pjmd89 @hummblebee @PanHH  have?

**Comment by newqwes** [comment]
How the solution from me will be found, I will write about it right there.

**Comment by Sentoki** [comment]
@newqwes ubuntu 20.04

**Comment by TorhamDev** [comment]
@Sentoki 
@newqwes 
@pjmd89 

Hi guys
I also had this problem and I could not solve it
I stopped using outline and used openvpn
openvpn was very good for me
And I can use it on my entire operating system using my desktop network manager and the whole operating system can be passed through the Vpn tunnel

**Comment by PanHH** [comment]
@TorhamDev 
@newqwes 

> You have to reinstall the outline

I had reinstalled several times, this problem persists. I used the version of Ubuntu 18.04.4 LTS.

But I can use the outline on my Android and IOS mobile phone very well.

**Comment by newqwes** [comment]
> @Sentoki @newqwes @pjmd89
> 
> Hi guys I also had this problem and I could not solve it I stopped using outline and used openvpn openvpn was very good for me And I can use it on my entire operating system using my desktop network manager and the whole operating system can be passed through the Vpn tunnel

I'm already thinking about **switching** to openVPN

**Comment by aaaamirabbas** [comment]
This problem exists in the following versions and I tested it.

**Ubuntu 20.04
Ubuntu 21.10
Ubuntu 22.04
PopOS 22.04**

Please fix this bug.

**Comment by efimmatytsin** [comment]
Fedora 35 same

**Comment by masta0f1eave** [comment]
Also stumbled across this issue with Outline Client version 1.7.0 on Manjaro Linux.
`Linux workstation 5.15.41-1-MANJARO #1 SMP PREEMPT Wed May 18 09:20:01 UTC 2022 x86_64 GNU/Linux`
Could connect to my server after creating file `/home/$user/.config/Outline/connection_store`

**Comment by Reysb** [comment]
I'm getting the same error now with Ubuntu 18.04. The servers I use work properly on my iPhone and I was able to connect with Outline until the last week. But I had to re-install my Ubuntu 18.04 this week and after that, I am not able to connect and get this exact error. Was anybody able to solve this issue?

**Comment by Vasyka** [comment]
@Reysb Also fixed the problem on Manjaro 21.3 just by creating file `/home/$user/.config/Outline/connection_store`. Outline Client version 1.7.2. Does it work for Ubuntu?

**Comment by CoolAller** [comment]
> Does it work for Ubuntu?
No, it does not work.

**Comment by maddyhof** [comment]
Thanks for reaching out! Please try with the latest versions of Outline and open a new issue if the problem persists. Please note that we only support Debian-based Linux distros.
