### ISSUE TITLE
Would it be better to be a NetworkManager VPN plugin?

### ISSUE THREAD

**Issue by anquan123** [Jigsaw-Code/outline-client#986]
NetworkManager VPN plugins
-- | --
NetworkManager-fortisslvpn (releases) | Fortinet SSLVPN compatible
NetworkManager-libreswan (releases) | IPsec IKEv1 VPN, Cisco compatible
NetworkManager-pptp (releases) | PPTP, Microsoft compatible
NetworkManager-openconnect (releases) | Cisco AnyConnect, Juniper
NetworkManager-openvpn (releases) | OpenVPN
NetworkManager-vpnc (releases) | IPsec VPN, Cisco compatible
WireGuard | NetworkManager 1.16.0+ supports WireGuard natively and not as VPN plugin
**NetworkManager-outline(releases)  developed by Jigsaw.Use the popular Shadowsocks protocol**

**Comment by x09** [comment]
NetworkManager-outline is available?
