### ISSUE TITLE
cann't add aes-256-cfb encryption shadowsocks server 不支持aes-256-cfb加密方式的ss服务器

### ISSUE THREAD

**Issue by andyhebear** [Jigsaw-Code/outline-client#997]
my shadowsocks server : ss://YWVzLTI1Ni1jZmI6YmFubmVkYm9vay5vcmdAMzguMTAwLjIyOS44NDozOQ==

my android and ios phone cann't add this ss return shadowsockes不支持改加密方式 aes-256-cfb

安卓手机与苹果手机不能添加该服务器，提示 不支持改加密方式aes-256-cfb

**Comment by alalamav** [comment]
Hi @andyhebear, Outline does not support non-AEAD ciphers because they are not secure. We recommend we update your access keys to use one of these AEAD ciphers: chacha20-ietf-poly1305, aes-128-gcm, aes-192-gcm, aes-256-gcm.
